Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ExchangeRates__c.object
<CustomObject>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseCurrency__c</fullName>
        <label>BaseCurrency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>USD__c</fullName>
        <label>USD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>ExchangeRate</label>
    <nameField>
        <displayFormat>ER-{000000000}</displayFormat>
        <label>ExchangeRates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExchangeRates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_Display_Currency__c</fullName>
        <inlineHelpText>Choose the most likely Currency your client will want to pay in (based on their Country of Residence) The client can change this in the MembersClub if they desire, but will be unable to change once the Quotation goes to stage &quot;Raised Booking Confirmation&quot;</inlineHelpText>
        <label>Client Display Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exchange_Currency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Itinerary_Summary__c</fullName>
        <inlineHelpText>This is the intro text that will show on this quotation in the Members Club (and also to be used on your covering email) Make sure this is specific to the quotation you are offering and adding value and insight.</inlineHelpText>
        <label>Quotation Intro Note to Customer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ROE_EUR_to_CC__c</fullName>
        <label>ROE Euro to Client Currency</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ROE_USD_to_CC__c</fullName>
        <label>ROE USD to Client Currency</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ROE_ZAR_to_CC__c</fullName>
        <label>ROE ZAR to Client Currency</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TravelStartDate__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_EmailUtilService.cls
@isTest
private class Test_EmailUtilService {
	static List<Opportunity> opportunitys = new List<Opportunity>();
    static List<Account> accounts = new List<Account>();
    static List<Passenger__c> passengers = new List<Passenger__c>();
    static List<Quotations__c> Quotations = new List<Quotations__c>();
    static List<ExchangeRates__c> exchangeRates = new List<ExchangeRates__c>();
     static Integer recordCount = 2;
    
    @testSetup static void setupInsertData()
    {
        User us = TestDataFactory.createUser(true, '', true);
        System.runAs(us){
            Account accountRec = new Account();
            accountRec.Name = 'Unit Test Account';
            accountRec.BillingStreet = '123 Unit Test Street';
            accountRec.BillingCity='Dallas';
            accountRec.BillingState = 'TX';
            accountRec.BillingPostalCode = '75006';
            accountRec.BillingCountry='US';
            accountRec.Industry = 'Commerical';
            accountRec.Newsletter__c= true;
            accounts.add(accountRec);
            DAL_BaseObject.InsertDBObjects(accounts);
            
            Map<String,Object>  accountOpportunityMap = new Map<String,Object>();
            for(Account acc:accounts)
            {
                accountOpportunityMap.put('AccountId', acc.ID);
                accountOpportunityMap.put('StageName', 'Prospect');
                accountOpportunityMap.put('Client_Display_Currency__c','USD');
            }
            Map<String,Object>  accountOpportunityMap1 = new Map<String,Object>();
            for(Account acc:accounts)
            {
                accountOpportunityMap1.put('AccountId', acc.ID);
                accountOpportunityMap1.put('StageName', 'Prospect');
                accountOpportunityMap1.put('Client_Display_Currency__c','AUD');
            }
            Map<String,Object>  accountOpportunityMap2 = new Map<String,Object>();
            for(Account acc:accounts)
            {
                accountOpportunityMap2.put('AccountId', acc.ID);
                accountOpportunityMap2.put('StageName', 'Prospect');
                accountOpportunityMap2.put('Client_Display_Currency__c','EUR');
            }
            Map<String,Object>  accountOpportunityMap3 = new Map<String,Object>();
            for(Account acc:accounts)
            {
                accountOpportunityMap3.put('AccountId', acc.ID);
                accountOpportunityMap3.put('StageName', 'Prospect');
                accountOpportunityMap3.put('Client_Display_Currency__c','GBP');
            }
            
            //USD
            Map<String,Object> exchangeRateMap = new Map<String,Object>();
            exchangeRateMap.put('BaseCurrency__c','USD');
            exchangeRateMap.put('USD__c',1.0d);
            //AUD
            Map<String,Object> exchangeRateMap1 = new Map<String,Object>();
            exchangeRateMap1.put('BaseCurrency__c','AUD');
            exchangeRateMap1.put('AUD__c',1.0d);
            //EUR
            Map<String,Object> exchangeRateMap2 = new Map<String,Object>();
            exchangeRateMap2.put('BaseCurrency__c','EUR');
            exchangeRateMap2.put('EUR__c',1.0d);
            //GBP
            Map<String,Object> exchangeRateMap3 = new Map<String,Object>();
            exchangeRateMap3.put('BaseCurrency__c','GBP');
            exchangeRateMap3.put('GBP__c',1.0d);
            
            for(Integer i = 0 ; i <recordCount; i++)
            {
                exchangeRates.add((ExchangeRates__c) TestDataFactory.operationOnObjectRecord(null, 'ExchangeRates__c', exchangeRateMap));
            }
            for(Integer i = 0 ; i <recordCount; i++)
            {
                exchangeRates.add((ExchangeRates__c) TestDataFactory.operationOnObjectRecord(null, 'ExchangeRates__c', exchangeRateMap1));
            }
            for(Integer i = 0 ; i <recordCount; i++)
            {
                exchangeRates.add((ExchangeRates__c) TestDataFactory.operationOnObjectRecord(null, 'ExchangeRates__c', exchangeRateMap2));
            }
            for(Integer i = 0 ; i <recordCount; i++)
            {
                exchangeRates.add((ExchangeRates__c) TestDataFactory.operationOnObjectRecord(null, 'ExchangeRates__c', exchangeRateMap3));
            }
            DAL_BaseObject.InsertDBObjects(exchangeRates);
            
            //New Opportunity One
            for(Integer i = 0 ; i <recordCount; i++)
            {
                opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap));
            }
            //New Opportunity Two
            for(Integer i = 0 ; i <recordCount; i++)
            {
                opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap1));
            }
            //New Opportunity Three
            for(Integer i = 0 ; i <recordCount; i++)
            {
                opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap2));
            }
            //New Opportunity Four
            for(Integer i = 0 ; i <recordCount; i++)
            {
                opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap3));
            }
            DAL_BaseObject.InsertDBObjects(opportunitys);
            
            //For Quotation One
            Map<String,Object>  opportunityQuotationMap = new Map<String,Object>();
            opportunityQuotationMap.put('Opportunity__c', opportunitys[0].ID);
            opportunityQuotationMap.put('TravelStartDate__c',system.today());
            opportunityQuotationMap.put('TravelEndDate__c',system.today().addDays(3));
            opportunityQuotationMap.put('Itinerary_Summary__c','21123');
            opportunityQuotationMap.put('ROE_ZAR_to_CC__c',2);
            opportunityQuotationMap.put('ROE_USD_to_CC__c',2);
            opportunityQuotationMap.put('ROE_EUR_to_CC__c',2);
            
            //For Quotation Two
            Map<String,Object>  opportunityQuotationMap1 = new Map<String,Object>();
            opportunityQuotationMap1.put('Opportunity__c', opportunitys[1].ID);
            opportunityQuotationMap1.put('TravelStartDate__c',system.today());
            opportunityQuotationMap1.put('TravelEndDate__c',system.today().addDays(3));
            opportunityQuotationMap1.put('Itinerary_Summary__c','21123');
            opportunityQuotationMap1.put('ROE_ZAR_to_CC__c',2);
            opportunityQuotationMap1.put('ROE_USD_to_CC__c',2);
            opportunityQuotationMap1.put('ROE_EUR_to_CC__c',2);
            
            //For Quotation Three
            Map<String,Object>  opportunityQuotationMap2 = new Map<String,Object>();
            opportunityQuotationMap2.put('Opportunity__c', opportunitys[2].ID);
            opportunityQuotationMap2.put('TravelStartDate__c',system.today());
            opportunityQuotationMap2.put('TravelEndDate__c',system.today().addDays(3));
            opportunityQuotationMap2.put('Itinerary_Summary__c','21123');
            opportunityQuotationMap2.put('ROE_ZAR_to_CC__c',2);
            opportunityQuotationMap2.put('ROE_USD_to_CC__c',2);
            opportunityQuotationMap2.put('ROE_EUR_to_CC__c',2);
            
            //For Quotation Four
            Map<String,Object>  opportunityQuotationMap3 = new Map<String,Object>();
            opportunityQuotationMap3.put('Opportunity__c', opportunitys[0].ID);
            opportunityQuotationMap3.put('TravelStartDate__c',system.today());
            opportunityQuotationMap3.put('TravelEndDate__c',system.today().addDays(3));
            opportunityQuotationMap3.put('Itinerary_Summary__c','21123');
            opportunityQuotationMap3.put('ROE_ZAR_to_CC__c',2);
            opportunityQuotationMap3.put('ROE_USD_to_CC__c',2);
            opportunityQuotationMap3.put('ROE_EUR_to_CC__c',2);
            
            Map<String,Object>  accountMap = new Map<String,Object>();
            accountMap.put('Opportunity__c' ,opportunitys[0].id );
            
            for(Integer i = 0 ; i <recordCount; i++)
            {
                passengers.add((Passenger__c) TestDataFactory.operationOnObjectRecord(null, DAL_Passenger.OBJECT_NAME, accountMap));
            }
            DAL_BaseObject.InsertDBObjects(passengers);
            
            //New Quotations One
            for(Integer i = 0 ; i <recordCount; i++)
            {
                Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap));
            }
            //New Quotations Two
            for(Integer i = 0 ; i <recordCount; i++)
            {
                Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap1));
            }
            //New Quotations Three
            for(Integer i = 0 ; i <recordCount; i++)
            {
                Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap2));
            }
            //New Quotations Four
            for(Integer i = 0 ; i <recordCount; i++)
            {
                Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap3));
            }
           
            BaseTriggerHandler.bypass('OpportunityTriggerHandler');
            DAL_BaseObject.InsertDBObjects(Quotations);
            BaseTriggerHandler.clearBypass('OpportunityTriggerHandler');
        }
    }
    
    @isTest static void sendEmailTest(){
        List<Quotations__c> quotations = [SELECT Id FROM Quotations__c];
        Set<Id> confirmedQuotaionsIds = new Set<Id>();
        Map<Id,String> quotationIdEmailMap = new Map<Id,String>();
        for(Quotations__c quotation:quotations){
            confirmedQuotaionsIds.add(quotation.Id);
            quotationIdEmailMap.put(quotation.Id,quotation.Id);
        }
        Test.startTest();
        EmailUtilService.sendEmail(confirmedQuotaionsIds,quotationIdEmailMap);
        Test.stopTest();
    } 
    
}