Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credit_Status__c</fullName>
        <label>Credit Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_CustomLightningActionApxCtrl.cls
@isTest
private class Test_CustomLightningActionApxCtrl {
    public static List<Account> accounts = new List<Account>();
    @testSetup static void setupInsertData()
    {
        User us = TestDataFactory.createUser(true, '', true);
        System.runAs(us){
            Account accountRec = new Account();
            accountRec.Name = 'Unit Test Account';
            accountRec.BillingStreet = '123 Unit Test Street';
            accountRec.BillingCity='Dallas';
            accountRec.BillingState = 'TX';
            accountRec.BillingPostalCode = '75006';
            accountRec.BillingCountry='US';
            accountRec.Industry = 'Commerical';
            accountRec.Newsletter__c= true;
            accountRec.Credit_Status__c = 'red';
            accounts.add(accountRec);
            DAL_BaseObject.InsertDBObjects(accounts);
        }
    }
    
    @isTest static void Test_AllMethodsOne(){
        List<Account> accountRecords = [SELECT Id,Credit_Status__c FROM Account];
        Test.startTest();
            CustomLightningActionApxCtrl.creditStatusConfirmConditionalCheck(accountRecords[0].Id);
        	CustomLightningActionApxCtrl.creditStatusRedirectCheck(accountRecords[0].Id);
        	CustomLightningActionApxCtrl.stupidStaticMethod(accountRecords[0].Id);
        	CustomLightningActionApxCtrl.createSalesOrder(accountRecords[0].Id);
        Test.stopTest();
    }
    
    @isTest static void Test_AllMethodsTwo(){
        Test.startTest();
            CustomLightningActionApxCtrl.creditStatusConfirmConditionalCheck('1231312312');
        	CustomLightningActionApxCtrl.creditStatusRedirectCheck('123131231');
        	CustomLightningActionApxCtrl.stupidStaticMethod('123123213123');
        Test.stopTest();
    }
}