Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Consultant_Target_Monthly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant_Gross_Profit_Target__c</fullName>
        <label>Consultant Convsersion Ratio Target</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Monthly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gross_Profit_Target__c</fullName>
        <label>Consultant Gross Profit Target</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Month</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If a consultant has just started with Safari365 (or is a trainee in forst 3 months) this allows for a staggered ( 25%, 50%, 75% etc) lead-in of the normal monthly target for the initial 3 months.</inlineHelpText>
        <label>Override Monthly GP Required (Lead-In)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. GP Setup (Monthly)</label>
    <nameField>
        <displayFormat>CTM-{00000000}</displayFormat>
        <label>ID - Individ Cons. GP</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. GP Setup (Monthly)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Ages_of_Children__c</fullName>
        <label>Ages of Children</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consultant_Target_Monthly__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Target Monthly</label>
        <referenceTo>Consultant_Target_Monthly__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <label>Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Adults__c</fullName>
        <label>Number of Adults</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Children__c</fullName>
        <label>Number of Children</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_OpportunityTriggerHandler.cls
@isTest
private class Test_OpportunityTriggerHandler {

    static List<Account> testAccountsList;
    static List<Opportunity> testOpportunityRec;
    public static List<Consultant_Target_Monthly__c>  consultantTargetMonthlys = new List<Consultant_Target_Monthly__c>();
    static Integer recordCount = 1;
    public static void setupTestData(){
       
       User us = TestDataFactory.createUser(true, '', true);
       System.runAs(us){
       testAccountsList = new List<Account>();
       testOpportunityRec = new List<Opportunity>();
       
       Account accountRec = new Account();
       accountRec.Name = 'Unit Test Account';
       accountRec.BillingStreet = '123 Unit Test Street';
       accountRec.BillingCity='Dallas';
       accountRec.BillingState = 'TX';
       accountRec.BillingPostalCode = '75006';
       accountRec.BillingCountry='US';
       accountRec.Industry = 'Commerical';
       accountRec.Newsletter__c= true;
       testAccountsList.add(accountRec);
       
       insert testAccountsList;
       
       Opportunity opptyRec = new Opportunity();
       opptyRec.AccountId = testAccountsList[0].Id;
       opptyRec.Name = 'Unit Test Opportuntiy';
       opptyRec.CloseDate = System.Today();
       opptyRec.StageName = 'Prospect';
       opptyRec.ownerId = us.Id;
       testOpportunityRec.add(opptyRec);
       
       insert testOpportunityRec;
       
	    Map<String,Object> consultantTargetMonthlyMap = new Map<String,Object>();
	    consultantTargetMonthlyMap.put('Month__c',String.valueof(system.today().month()));
	    consultantTargetMonthlyMap.put('Year__c',String.valueof(system.today().year()));
	    consultantTargetMonthlyMap.put('Consultant__c',us.id);
	    consultantTargetMonthlyMap.put('Override__c',true);
	    consultantTargetMonthlyMap.put('Gross_Profit_Target__c',1000);
	    consultantTargetMonthlyMap.put('Consultant_Gross_Profit_Target__c',10);
	    for(Integer i = 0 ; i <recordCount; i++)
	    {
	        consultantTargetMonthlys.add((Consultant_Target_Monthly__c) TestDataFactory.operationOnObjectRecord(null, 'Consultant_Target_Monthly__c', consultantTargetMonthlyMap));
	    }
	    DAL_BaseObject.InsertDBObjects(consultantTargetMonthlys);
            
       }
    }
    
    public static testmethod void updateOpportunity(){
        
         User us = TestDataFactory.createUser(true, '', true);
       System.runAs(us){
        setupTestData();
        Test.startTest();
        
        testOpportunityRec[0].Number_of_Adults__c = 25;
        testOpportunityRec[0].Number_of_Children__c = 20;
       
        testOpportunityRec[0].Ages_of_Children__c = '12';
        testOpportunityRec[0].stagename= 'Money in the Bank';
        testOpportunityRec[0].Arrival_Date__c=System.Today();
        
       Opportunity opptyRec = new Opportunity();
       opptyRec.AccountId = testAccountsList[0].Id;
       opptyRec.Name = 'Unit Test Opportuntiy2';
       opptyRec.CloseDate = System.Today();
       opptyRec.StageName = 'Prospect';
       testOpportunityRec.add(opptyRec);
       
        upsert testOpportunityRec;
        Test.stopTest();
       }
    }
    
    
     public static testmethod void updateOpportunity2(){
        
        User us = TestDataFactory.createUser(true, '', true);
        System.runAs(us){
	        setupTestData();
	        Test.startTest();
	        
	        testOpportunityRec[0].Number_of_Adults__c = 25;
	        testOpportunityRec[0].Number_of_Children__c = 20;
	        testOpportunityRec[0].Ages_of_Children__c = '12';
	        testOpportunityRec[0].stagename= 'Closed Won Deal';
	        testOpportunityRec[0].Arrival_Date__c=System.Today();
	        testOpportunityRec[0].Amount=100;
	        testOpportunityRec[0].Gross_Profit__c=80;
	       
	        update testOpportunityRec;
	        Test.stopTest();
        }
    }
    
    public static testmethod void deleteOpportunity2(){
        
        User us = TestDataFactory.createUser(true, '', true);
        System.runAs(us){
            setupTestData();
            Test.startTest();
            
            testOpportunityRec[0].Number_of_Adults__c = 25;
            testOpportunityRec[0].Number_of_Children__c = 20;
            testOpportunityRec[0].Ages_of_Children__c = '12';
            testOpportunityRec[0].stagename= 'Closed Won Deal';
            testOpportunityRec[0].Arrival_Date__c=System.Today();
            testOpportunityRec[0].Amount=100;
            testOpportunityRec[0].Gross_Profit__c=80;
            update testOpportunityRec;
            delete testOpportunityRec;
            Test.stopTest();
        }
    }
}