Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_Display_Currency__c</fullName>
        <inlineHelpText>Choose the most likely Currency your client will want to pay in (based on their Country of Residence) The client can change this in the MembersClub if they desire, but will be unable to change once the Quotation goes to stage &quot;Raised Booking Confirmation&quot;</inlineHelpText>
        <label>Client Display Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exchange_Currency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Iternary_Language__c</fullName>
        <inlineHelpText>Select the correct language to display in the Members Club and for the Itinerary Document</inlineHelpText>
        <label>Itinerary Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>En</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>De</fullName>
                </value>
                <value>
                    <fullName>Pt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Itinerary_Summary__c</fullName>
        <inlineHelpText>This is the intro text that will show on this quotation in the Members Club (and also to be used on your covering email) Make sure this is specific to the quotation you are offering and adding value and insight.</inlineHelpText>
        <label>Quotation Intro Note to Customer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TravelStartDate__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Wetu_Identifier__c</fullName>
        <inlineHelpText>This is the unique WETU URL string if you want to duplicate this exact Members Club itinerrary display. You can override this field with an updated URL string as required (proceed with caution as the quotes need to be identical)</inlineHelpText>
        <label>WETU Identifier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_WS_GetGoogleDocUrl.cls
@isTest
private class Test_WS_GetGoogleDocUrl {
	public static List<Opportunity> opportunitys = new List<Opportunity>();
    public static List<Account> accounts = new List<Account>();
    public static List<Passenger__c> passengers = new List<Passenger__c>();
    public static List<Quotations__c> Quotations = new List<Quotations__c>();
    public static List<GoogleDoc> googleDocuments = new List<GoogleDoc>();
    
    public static Integer recordCount = 1;
    
    @testSetup static void setupInsertData()
    {
        User us = TestDataFactory.createUser(true, '', true);
        System.runAs(us){
            Account accountRec = new Account();
            accountRec.Name = 'Unit Test Account';
            accountRec.BillingStreet = '123 Unit Test Street';
            accountRec.BillingCity='Dallas';
            accountRec.BillingState = 'TX';
            accountRec.BillingPostalCode = '75006';
            accountRec.BillingCountry='US';
            accountRec.Industry = 'Commerical';
            accountRec.Newsletter__c= true;
            accounts.add(accountRec);
            DAL_BaseObject.InsertDBObjects(accounts);
            
            Map<String,Object>  accountOpportunityMap = new Map<String,Object>();
            for(Account acc:accounts)
            {
                accountOpportunityMap.put('AccountId', acc.ID);
                accountOpportunityMap.put('StageName', 'Prospect');
                accountOpportunityMap.put('Client_Display_Currency__c','USD');
            }
            
            for(Integer i = 0 ; i <recordCount; i++)
            {
                opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap));
            }
            DAL_BaseObject.InsertDBObjects(opportunitys);
            
            Map<String,Object>  opportunityQuotationMap = new Map<String,Object>();
            Map<String,Object>  accountMap = new Map<String,Object>();
            for(Opportunity opp:opportunitys)
            {
                opportunityQuotationMap.put('Opportunity__c', opp.ID);
                opportunityQuotationMap.put('TravelStartDate__c',system.today());
                opportunityQuotationMap.put('TravelEndDate__c',system.today().addDays(3));
                opportunityQuotationMap.put('Iternary_Language__c','En');
                opportunityQuotationMap.put('Itinerary_Summary__c','how are you I am good');
                opportunityQuotationMap.put('Wetu_Identifier__c','abcedeccc');
                accountMap.put('Opportunity__c' ,opp.id );
            }
            
            for(Integer i = 0 ; i <recordCount; i++)
            {
                passengers.add((Passenger__c) TestDataFactory.operationOnObjectRecord(null, DAL_Passenger.OBJECT_NAME, accountMap));
            }
            DAL_BaseObject.InsertDBObjects(passengers);
            
            for(Integer i = 0 ; i <recordCount; i++)
            {
                Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap));
            }
            DAL_BaseObject.InsertDBObjects(Quotations);
            
            String urlLink = 'https://docs.google.com/spreadsheets/d/1sW8Fl_Zo6kjfOhVYxAMwjha9AT19GQ6VReP5mLMOFXE/edit?usp=drivesdk';
            Map<String,Object> googleDocMap = new Map<String,Object>();
            googleDocMap.put('Url',urlLink);
            googleDocMap.put('ParentId',Quotations[0].Id);
            googleDocMap.put('Name','Client Facing Documentation');
            
            for(Integer i = 0 ; i <recordCount; i++)
            {
                googleDocuments.add((GoogleDoc) TestDataFactory.operationOnObjectRecord(null, 'GoogleDoc', googleDocMap));
            }
            DAL_BaseObject.InsertDBObjects(googleDocuments);
        }
    }
    
    @isTest static void testingMethodOneTest(){
        GoogleDoc GoogleDocRecord = [SELECT Id, Url, ParentId, Name, IsDeleted, OwnerId FROM GoogleDoc limit 1];
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        RestContext.request = req;
        RestContext.response = res;
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new GoogleDriveMockResponse());
        WS_GetGoogleDocUrl.getGoogleDocUrl(GoogleDocRecord.Id);
        Test.stopTest();
    }
    
    @isTest static void testingMethodTwoTest(){
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        RestContext.request = req;
        RestContext.response = res;
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new GoogleDriveMockResponse());
        WS_GetGoogleDocUrl.getGoogleDocUrl('0980E0000004CGsQAM');
        Test.stopTest();
    }
}