Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/CRM__c.object
<CustomObject>
    <fields>
        <fullName>CODE__c</fullName>
        <externalId>true</externalId>
        <label>CODE</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>CRM</label>
    <nameField>
        <displayFormat>CRM-{00000000}</displayFormat>
        <label>CRM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/DB4__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DB4</label>
    <nameField>
        <displayFormat>DB-{00000000}</displayFormat>
        <label>DB4 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DB4s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ExchangeRates__c.object
<CustomObject>
    <fields>
        <fullName>BaseCurrency__c</fullName>
        <label>BaseCurrency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>ExchangeRate</label>
    <nameField>
        <displayFormat>ER-{000000000}</displayFormat>
        <label>ExchangeRates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExchangeRates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_Display_Currency__c</fullName>
        <inlineHelpText>Choose the most likely Currency your client will want to pay in (based on their Country of Residence) The client can change this in the MembersClub if they desire, but will be unable to change once the Quotation goes to stage &quot;Raised Booking Confirmation&quot;</inlineHelpText>
        <label>Client Display Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exchange_Currency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opt__c.object
<CustomObject>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>OPT</label>
    <nameField>
        <displayFormat>OPT-{0000000}</displayFormat>
        <label>OPT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/PassengerQuotationMapping__c.object
<CustomObject>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PassengerQuotationMapping</label>
    <nameField>
        <displayFormat>PQM-{00000000}</displayFormat>
        <label>PassengerQuotationMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PassengerQuotationMappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/QuotationLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Line_Item_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nett_Cost_in_EUR__c</fullName>
        <label>Nett Cost in EUR</label>
        <summarizedField>ServiceLineItem__c.Nett_Cost_in_EUR__c</summarizedField>
        <summaryForeignKey>ServiceLineItem__c.QuotationLine__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nett_Cost_in_USD__c</fullName>
        <label>Nett Cost in USD</label>
        <summarizedField>ServiceLineItem__c.Nett_Cost_in_USD__c</summarizedField>
        <summaryForeignKey>ServiceLineItem__c.QuotationLine__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipName>QuotationLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sale_in_Eur__c</fullName>
        <label>Sale in Eur</label>
        <summarizedField>ServiceLineItem__c.Sale_in_Eur__c</summarizedField>
        <summaryForeignKey>ServiceLineItem__c.QuotationLine__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sale_in_USD__c</fullName>
        <label>Sale in USD</label>
        <summarizedField>ServiceLineItem__c.Sale_in_USD__c</summarizedField>
        <summaryForeignKey>ServiceLineItem__c.QuotationLine__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Quotation Line Item</label>
    <nameField>
        <label>Quotation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>TEXT(  Opportunity__r.Client_Display_Currency__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>On the Opportunity level, choose the most likely Client Display Currency (one of the supported Global Currencies)  Your client is able to change their preferred currency in the Members Club, you will need to raise Booking Confirmation in this Currency.</inlineHelpText>
        <label>Client Display Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ROE_EUR_to_CC__c</fullName>
        <label>ROE Euro to Client Currency</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ROE_USD_to_CC__c</fullName>
        <label>ROE USD to Client Currency</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ROE_ZAR_to_CC__c</fullName>
        <label>ROE ZAR to Client Currency</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sale_In_USD__c</fullName>
        <label>Sale In USD</label>
        <summarizedField>QuotationLineItem__c.Sale_in_USD__c</summarizedField>
        <summaryForeignKey>QuotationLineItem__c.Quotation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sale_in_EUR__c</fullName>
        <label>Total Sale in EUR</label>
        <summarizedField>QuotationLineItem__c.Sale_in_Eur__c</summarizedField>
        <summaryForeignKey>QuotationLineItem__c.Quotation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TravelStartDate__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Service_Line_Item_ChargeType__c.object
<CustomObject>
    <description>This object will have the details for Service Line Items. The details this object will have are Charge Type, Currency, Nett Cost, Markup (%) and Total.</description>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Cur</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Currency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nett_Cost__c</fullName>
        <label>Nett</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Sale</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service Line Item ChargeType</label>
    <nameField>
        <displayFormat>SLICT-{00000000}</displayFormat>
        <label>Service Line Item Charge Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Item ChargeTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Nett_Cost__c</fullName>
        <label>Nett Cost in Zar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nett_Cost_in_EUR__c</fullName>
        <label>Nett Cost in EUR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nett_Cost_in_USD__c</fullName>
        <label>Nett Cost in USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuotationLine__c</fullName>
        <label>Quotation Line</label>
        <referenceTo>QuotationLineItem__c</referenceTo>
        <relationshipName>ServiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sale_in_Eur__c</fullName>
        <label>Sale in Eur</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sale_in_USD__c</fullName>
        <label>Sale in USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Sale in Zar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Service Line Item</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceLine Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItemPassengersMapping__c.object
<CustomObject>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>ServiceLineItemPassengersMappings</relationshipLabel>
        <relationshipName>ServiceLineItemPassengersMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ServiceLineItemPassengersMapping</label>
    <nameField>
        <displayFormat>SLIP-{00000000}</displayFormat>
        <label>ServiceLineItemPassengersMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceLineItemPassengersMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_QuotationPricingController.cls
@isTest
private class Test_QuotationPricingController {
    
    static List<Opportunity> opportunitys = new List<Opportunity>();
    static List<Account> accounts = new List<Account>();
    static List<Passenger__c> passengers = new List<Passenger__c>();
    static List<Quotations__c> Quotations = new List<Quotations__c>();
    static List<Service_Line_Item_ChargeType__c> serviceChargeTypes = new List<Service_Line_Item_ChargeType__c>();
    static QuotationBuilderDatabaseQueries dbQueries = new QuotationBuilderDatabaseQueries();
    static List<Opt__c>  opts = new List<Opt__c>();
    static List<SRV__c>  srvs = new List<SRV__c>();
    static List<OPT__c>  db4opts = new List<OPT__c>();
    static List<DB4__c>  db4s= new List<DB4__c>();
    static List<CRM__c>  crms = new List<CRM__c>();
    static List<SOD__c>  sods= new List<SOD__c>();
    static List<PassengerQuotationMapping__c> passengerQuotations = new List<PassengerQuotationMapping__c>();
    static List<ServiceLineItem__c> slis = new List<ServiceLineItem__c>();
    static List<ServiceLineItemPassengersMapping__c> sliPassengers = new List<ServiceLineItemPassengersMapping__c>();
    static Integer recordCount = 1;
    static List<QuotationLineItem__c> getQuotationLineItemList = null;
    static List<QuotationLineItem__c> QuotationsLineItem = new List<QuotationLineItem__c>();
    static List<ExchangeRates__c> exchangeRates = new List<ExchangeRates__c>();
    
    static void setupInsertData()
    {
        User us = TestDataFactory.createUser(true, 'TH_Quotations', true);
        System.runAs(us){
        	 BaseTriggerHandler.bypass('TH_Quotations');
            //New Accounts
            Account accountRec = new Account();
            accountRec.Name = 'Unit Test Account';
            accountRec.BillingStreet = '123 Unit Test Street';
            accountRec.BillingCity='Dallas';
            accountRec.BillingState = 'TX';
            accountRec.BillingPostalCode = '75006';
            accountRec.BillingCountry='US';
            accountRec.Industry = 'Commerical';
            accountRec.Newsletter__c= true;
            accounts.add(accountRec);
            
            DAL_BaseObject.InsertDBObjects(accounts);
            
            Map<String,Object>  accountOpportunityMap = new Map<String,Object>();
            for(Account acc:accounts)
            {
                accountOpportunityMap.put('AccountId', acc.ID);
                accountOpportunityMap.put('StageName', 'Prospect');
                accountOpportunityMap.put('Client_Display_Currency__c','USD');
            }
            Map<String,Object>  accountOpportunityMap1 = new Map<String,Object>();
            for(Account acc:accounts)
            {
                accountOpportunityMap1.put('AccountId', acc.ID);
                accountOpportunityMap1.put('StageName', 'Prospect');
                accountOpportunityMap1.put('Client_Display_Currency__c','AUD');
            }
            Map<String,Object>  accountOpportunityMap2 = new Map<String,Object>();
            for(Account acc:accounts)
            {
                accountOpportunityMap2.put('AccountId', acc.ID);
                accountOpportunityMap2.put('StageName', 'Prospect');
                accountOpportunityMap2.put('Client_Display_Currency__c','EUR');
            }
            Map<String,Object>  accountOpportunityMap3 = new Map<String,Object>();
            for(Account acc:accounts)
            {
                accountOpportunityMap3.put('AccountId', acc.ID);
                accountOpportunityMap3.put('StageName', 'Prospect');
                accountOpportunityMap3.put('Client_Display_Currency__c','GBP');
            }
            
            //New Exchange Rates
            Map<String,Object> exchangeRateMap = new Map<String,Object>();
            exchangeRateMap.put('BaseCurrency__c','ZAR');
            for(Integer i = 0 ; i <recordCount; i++)
            {
                exchangeRates.add((ExchangeRates__c) TestDataFactory.operationOnObjectRecord(null, 'ExchangeRates__c', exchangeRateMap));
            }
            DAL_BaseObject.InsertDBObjects(exchangeRates);
            
            //New Opportunity One
            for(Integer i = 0 ; i <recordCount; i++)
            {
                opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap));
            }
            //New Opportunity Two
            for(Integer i = 0 ; i <recordCount; i++)
            {
                opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap1));
            }
            //New Opportunity Three
            for(Integer i = 0 ; i <recordCount; i++)
            {
                opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap2));
            }
            //New Opportunity Four
            for(Integer i = 0 ; i <recordCount; i++)
            {
                opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap3));
            }
            DAL_BaseObject.InsertDBObjects(opportunitys);
            
            //For Quotation One
            Map<String,Object>  opportunityQuotationMap = new Map<String,Object>();
            opportunityQuotationMap.put('Opportunity__c', opportunitys[0].ID);
            opportunityQuotationMap.put('TravelStartDate__c',system.today());
            opportunityQuotationMap.put('TravelEndDate__c',system.today().addDays(3));
            opportunityQuotationMap.put('ROE_ZAR_to_CC__c',2);
            opportunityQuotationMap.put('ROE_USD_to_CC__c',2);
            opportunityQuotationMap.put('ROE_EUR_to_CC__c',2);
            
            //For Quotation Two
            Map<String,Object>  opportunityQuotationMap1 = new Map<String,Object>();
            opportunityQuotationMap1.put('Opportunity__c', opportunitys[1].ID);
            opportunityQuotationMap1.put('TravelStartDate__c',system.today());
            opportunityQuotationMap1.put('TravelEndDate__c',system.today().addDays(3));
            opportunityQuotationMap1.put('ROE_ZAR_to_CC__c',2);
            opportunityQuotationMap1.put('ROE_USD_to_CC__c',2);
            opportunityQuotationMap1.put('ROE_EUR_to_CC__c',2);
            
            //For Quotation Three
            Map<String,Object>  opportunityQuotationMap2 = new Map<String,Object>();
            opportunityQuotationMap2.put('Opportunity__c', opportunitys[2].ID);
            opportunityQuotationMap2.put('TravelStartDate__c',system.today());
            opportunityQuotationMap2.put('TravelEndDate__c',system.today().addDays(3));
            opportunityQuotationMap2.put('ROE_ZAR_to_CC__c',2);
            opportunityQuotationMap2.put('ROE_USD_to_CC__c',2);
            opportunityQuotationMap2.put('ROE_EUR_to_CC__c',2);
            
            //For Quotation Four
            Map<String,Object>  opportunityQuotationMap3 = new Map<String,Object>();
            opportunityQuotationMap3.put('Opportunity__c', opportunitys[0].ID);
            opportunityQuotationMap3.put('TravelStartDate__c',system.today());
            opportunityQuotationMap3.put('TravelEndDate__c',system.today().addDays(3));
            opportunityQuotationMap3.put('ROE_ZAR_to_CC__c',2);
            opportunityQuotationMap3.put('ROE_USD_to_CC__c',2);
            opportunityQuotationMap3.put('ROE_EUR_to_CC__c',2);
            
            Map<String,Object>  accountMap = new Map<String,Object>();
            accountMap.put('Opportunity__c' ,opportunitys[0].id );
            
            //New Passengers
            for(Integer i = 0 ; i <recordCount; i++)
            {
                passengers.add((Passenger__c) TestDataFactory.operationOnObjectRecord(null, DAL_Passenger.OBJECT_NAME, accountMap));
            }
            DAL_BaseObject.InsertDBObjects(passengers);
            
            //New Quotations One
            for(Integer i = 0 ; i <recordCount; i++)
            {
                Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap));
            }
            //New Quotations Two
            for(Integer i = 0 ; i <recordCount; i++)
            {
                Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap1));
            }
            //New Quotations Three
            for(Integer i = 0 ; i <recordCount; i++)
            {
                Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap2));
            }
            //New Quotations Four
            for(Integer i = 0 ; i <recordCount; i++)
            {
                Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap3));
            }
            
            DAL_BaseObject.InsertDBObjects(Quotations);
            
            
            //Quotation Line Item
            Map<String,Object>  QuotationQuotationLinitemMap = new Map<String,Object>();
            Integer rc=4;
            for(Integer i = 0 ; i <rc; i++)
            {
                QuotationQuotationLinitemMap.put('Name','QLI-'+i);
                QuotationQuotationLinitemMap.put('Quotation__c',Quotations[i].Id);
                QuotationQuotationLinitemMap.put('Line_Item_Date__c',Date.today());
                
                QuotationsLineItem.add((QuotationLineItem__c) TestDataFactory.operationOnObjectRecord(null, 'QuotationLineItem__c',QuotationQuotationLinitemMap ));
            }
            DAL_BaseObject.InsertDBObjects(QuotationsLineItem);   
            
            //New PassengerQuotationMapping
            Map<String,Object>  passengerQuotationMapingMap = new Map<String,Object>();
            passengerQuotationMapingMap.put('Passenger__c',passengers[0].Id);
            passengerQuotationMapingMap.put('Quotation__c',Quotations[0].Id);
            for(Integer i = 0 ; i <recordCount; i++)
            {
                passengerQuotations.add((PassengerQuotationMapping__c) TestDataFactory.operationOnObjectRecord(null, 'PassengerQuotationMapping__c', passengerQuotationMapingMap));
            }
            DAL_BaseObject.InsertDBObjects(passengerQuotations);
            
            getQuotationLineItemList= dbQueries.GetQuotationLineItemList(Quotations[0].id);
            
            Map<String, Object> quoationServiceLineMap =new Map<String, Object>();
            for(QuotationLineItem__c quoli: getQuotationLineItemList)
            {
                quoationServiceLineMap.put('QuotationLine__c',quoli.Id);
                quoationServiceLineMap.put('Total__c',22.22);
                quoationServiceLineMap.put('Sale_in_USD__c',22.22);
                quoationServiceLineMap.put('Sale_in_Eur__c',22.22);
                quoationServiceLineMap.put('Nett_Cost__c',22.22);
                quoationServiceLineMap.put('Nett_Cost_in_USD__c',22.22);
                quoationServiceLineMap.put('Nett_Cost_in_EUR__c',22.22);
            }
            
            //New SRV
            for(Integer i = 0 ; i <recordCount; i++)
            {
                srvs.add((SRV__c) TestDataFactory.operationOnObjectRecord(null, 'SRV__c', null));
            }
            insert srvs;
            
            //New Service
            Map<String,Object>  srvOptMap = new Map<String,Object>();
            for(SRV__c srv: srvs)
            {
                srvOptMap.put('Service__c',srvs[0].CODE__c);
            }
            
            //New OPT
            for(Integer i = 0 ; i <recordCount; i++)
            {
                opts.add((Opt__c) TestDataFactory.operationOnObjectRecord(null, DAL_OPT.OBJECT_NAME, srvOptMap));
            }
            insert opts;
            
            //New Service Line Items
            Map<String,Object> serviceLineItemkeyValueMap1 = new Map<String,Object>();
            serviceLineItemkeyValueMap1.put('Service_Detail__c','Luxury Safari Tent');
            serviceLineItemkeyValueMap1.put('QuotationLine__c',getQuotationLineItemList[0].Id);
            serviceLineItemkeyValueMap1.put('Service_Status__c','Not Booked');
            serviceLineItemkeyValueMap1.put('Provisional_Booking_Expiry_Date__c',system.today());
            serviceLineItemkeyValueMap1.put('Override_details__c',false);
            serviceLineItemkeyValueMap1.put('Room_Configuration__c','TWIN AVAIL');
            serviceLineItemkeyValueMap1.put('Service_Type__c','Accommodation');
            serviceLineItemkeyValueMap1.put('ServiceLocation__c','Timbavati Game Reserve');
            serviceLineItemkeyValueMap1.put('SupplierName__c','Simbavati Hilltop Lodge');
            serviceLineItemkeyValueMap1.put('Selected_OPT_Code__c',opts[0].Code__c);
            serviceLineItemkeyValueMap1.put('Service_Date__c',System.today());
            
            serviceLineItemkeyValueMap1.put('Wetu_Start_Location__c','a');
            serviceLineItemkeyValueMap1.put('Wetu_End_Location__c','b');
            serviceLineItemkeyValueMap1.put('Basis__c','x');
            serviceLineItemkeyValueMap1.put('Reservation_Number__c','a');
            serviceLineItemkeyValueMap1.put('Service_Duration__c',1);
            serviceLineItemkeyValueMap1.put('ClientNotes__c',' ');
            serviceLineItemkeyValueMap1.put('Crm_Code__c','SIM005');
            
            serviceLineItemkeyValueMap1.put('Total__c',5);
            serviceLineItemkeyValueMap1.put('Photobooks_Sale_in_ZAR__c',5);
            serviceLineItemkeyValueMap1.put('Insurance_Sale_in_ZAR__c',5);
            
            serviceLineItemkeyValueMap1.put('Sale_in_USD__c',5);
            serviceLineItemkeyValueMap1.put('Photobooks_Sale_in_USD__c',5);
            serviceLineItemkeyValueMap1.put('Insurance_Sale_in_USD__c',5);
            
            serviceLineItemkeyValueMap1.put('Sale_in_Eur__c',5);
            
            for(Integer i = 0 ; i <recordCount; i++)
            {
                slis.add((ServiceLineItem__c) TestDataFactory.operationOnObjectRecord(null, 'ServiceLineItem__c', serviceLineItemkeyValueMap1));
            }
            
            DAL_BaseObject.InsertDBObjects(slis);
            
            //New ServiceLine Item Passengers Mapping
            Map<String,Object>  passengerSLIMapingMap = new Map<String,Object>();
            passengerSLIMapingMap.put('Passenger__c',passengers[0].Id);
            passengerSLIMapingMap.put('Service_Line_Item__c',slis[0].Id);
            for(Integer i = 0 ; i <recordCount; i++)
            {
                sliPassengers.add((ServiceLineItemPassengersMapping__c) TestDataFactory.operationOnObjectRecord(null, 'ServiceLineItemPassengersMapping__c', passengerSLIMapingMap));
            }
            DAL_BaseObject.InsertDBObjects(sliPassengers);
            BaseTriggerHandler.clearBypass('TH_Quotations');
            
             //New Service Line Item ChargeType Mapping
            Map<String,Object>  serviceLineItemChargeTypeMap = new Map<String,Object>();
            serviceLineItemChargeTypeMap.put('Total__c',5000);
            serviceLineItemChargeTypeMap.put('Selected_Passenger__c',passengers[0].Id);
            serviceLineItemChargeTypeMap.put('Service_Line_Item__c',slis[0].Id);
            serviceLineItemChargeTypeMap.put('Currency__c','USD');
            for(Integer i = 0 ; i <recordCount; i++)
            {
                serviceChargeTypes.add((Service_Line_Item_ChargeType__c) TestDataFactory.operationOnObjectRecord(null, 'Service_Line_Item_ChargeType__c', serviceLineItemChargeTypeMap));
            }
            
            //New Service Line Item ChargeType Mapping
            Map<String,Object>  serviceLineItemChargeTypeMap2 = new Map<String,Object>();
            serviceLineItemChargeTypeMap2.put('Total__c',5000);
            serviceLineItemChargeTypeMap2.put('Selected_Passenger__c',passengers[0].Id);
            serviceLineItemChargeTypeMap2.put('Service_Line_Item__c',slis[0].Id);
            serviceLineItemChargeTypeMap2.put('Currency__c','ZAR');
            for(Integer i = 0 ; i <recordCount; i++)
            {
                serviceChargeTypes.add((Service_Line_Item_ChargeType__c) TestDataFactory.operationOnObjectRecord(null, 'Service_Line_Item_ChargeType__c', serviceLineItemChargeTypeMap2));
            }
            
            //New Service Line Item ChargeType Mapping
            Map<String,Object>  serviceLineItemChargeTypeMap3 = new Map<String,Object>();
            serviceLineItemChargeTypeMap3.put('Total__c',5000);
            serviceLineItemChargeTypeMap3.put('Selected_Passenger__c',passengers[0].Id);
            serviceLineItemChargeTypeMap3.put('Service_Line_Item__c',slis[0].Id);
            serviceLineItemChargeTypeMap3.put('Currency__c','EUR');
            for(Integer i = 0 ; i <recordCount; i++)
            {
                serviceChargeTypes.add((Service_Line_Item_ChargeType__c) TestDataFactory.operationOnObjectRecord(null, 'Service_Line_Item_ChargeType__c', serviceLineItemChargeTypeMap3));
            }
            
            DAL_BaseObject.InsertDBObjects(serviceChargeTypes);
        }   
    }
    
    static testMethod void testMethodOneTest()  
    {
        setupInsertData();
        //Quotation One currency USD
        String quotationId = Quotations[0].Id;
        List<QuotationLineItem__c> quoLineItem = [ select Id,Quotation__c FROM QuotationLineItem__c where Quotation__c = :quotationId];
        List<Id> qliId = new List<Id>();
        for(QuotationLineItem__c qli:quoLineItem){
            qliId.add(qli.Id);
        }
        List<ServiceLineItem__c> serLineItem = [select Id,Name,Service_Status__c,Reservation_Number__c FROM ServiceLineItem__c where QuotationLine__c In :qliId];
        List<ServiceLineItem__c> serLineItemList = new List<ServiceLineItem__c>();
        Integer i=1;
        for(ServiceLineItem__c sli:serLineItem){
            sli.Service_Status__c = 'Confirmed';
            sli.Reservation_Number__c = 'Confirmed_'+i;
            serLineItemList.add(sli);
            i++;
        }
        BaseTriggerHandler.bypass('TH_Quotations');
        update serLineItemList;
        Test.startTest();
        QuotationPricingController.getQuotationPricingDetails(quotationId);
        QuotationPricingController.updateQuotataionSalesValue(quotationId,2,3,4,1,2,'2018-02-20','2018-02-20');
        Test.stopTest();
        BaseTriggerHandler.clearBypass('TH_Quotations');	
        
    }
    
    static testMethod void testMethodTwoTest()  
    {
        setupInsertData();
        //Quotation Two Currency AUD
        String quotationId = Quotations[1].Id;
        List<QuotationLineItem__c> quoLineItem = [ select Id,Quotation__c FROM QuotationLineItem__c where Quotation__c = :quotationId];
        List<Id> qliId = new List<Id>();
        for(QuotationLineItem__c qli:quoLineItem){
            qliId.add(qli.Id);
        }
        List<ServiceLineItem__c> serLineItem = [select Id,Name,Service_Status__c,Reservation_Number__c FROM ServiceLineItem__c where QuotationLine__c In :qliId];
        List<ServiceLineItem__c> serLineItemList = new List<ServiceLineItem__c>();
        Integer i=1;
        for(ServiceLineItem__c sli:serLineItem)
        {
            sli.Service_Status__c = 'Confirmed';
            sli.Reservation_Number__c = 'Confirmed_'+i;
            serLineItemList.add(sli);
            i++;
        }
        BaseTriggerHandler.bypass('TH_Quotations');
        update serLineItemList;
        Test.startTest();
        QuotationPricingController.getQuotationPricingDetails(quotationId);
        QuotationPricingController.updateQuotataionSalesValue(quotationId,2,3,4,1,2,'2018-02-20','2018-02-20');
        Test.stopTest();
        BaseTriggerHandler.clearBypass('TH_Quotations');	
        
    }
    
    static testMethod void testMethodThreeTest()  
    {
        setupInsertData();
        //Quotation Three Currency EUR
        String quotationId = Quotations[2].Id;
        List<QuotationLineItem__c> quoLineItem = [ select Id,Quotation__c FROM QuotationLineItem__c where Quotation__c = :quotationId];
        List<Id> qliId = new List<Id>();
        for(QuotationLineItem__c qli:quoLineItem){
            qliId.add(qli.Id);
        }
        List<ServiceLineItem__c> serLineItem = [select Id,Name,Service_Status__c,Reservation_Number__c FROM ServiceLineItem__c where QuotationLine__c In :qliId];
        List<ServiceLineItem__c> serLineItemList = new List<ServiceLineItem__c>();
        Integer i=1;
        for(ServiceLineItem__c sli:serLineItem){
            sli.Service_Status__c = 'Confirmed';
            sli.Reservation_Number__c = 'Confirmed_'+i;
            serLineItemList.add(sli);
            i++;
        }
        BaseTriggerHandler.bypass('TH_Quotations');
        update serLineItemList;
        Test.startTest();
        QuotationPricingController.getQuotationPricingDetails(quotationId);
        QuotationPricingController.updateQuotataionSalesValue(quotationId,2,3,4,1,2,'2018-02-20','2018-02-20');
        Test.stopTest();
        BaseTriggerHandler.clearBypass('TH_Quotations');	
        
    }
    
    static testMethod void testMethodFourTest()  
    {
        setupInsertData();
        //Quotation Four Currency GBP
        String quotationId = Quotations[3].Id;
        List<QuotationLineItem__c> quoLineItem = [ select Id,Quotation__c FROM QuotationLineItem__c where Quotation__c = :quotationId];
        List<Id> qliId = new List<Id>();
        for(QuotationLineItem__c qli:quoLineItem){
            qliId.add(qli.Id);
        }
        List<ServiceLineItem__c> serLineItem = [select Id,Name,Service_Status__c,Reservation_Number__c FROM ServiceLineItem__c where QuotationLine__c In :qliId];
        List<ServiceLineItem__c> serLineItemList = new List<ServiceLineItem__c>();
        Integer i=1;
        for(ServiceLineItem__c sli:serLineItem){
            sli.Service_Status__c = 'Confirmed';
            sli.Reservation_Number__c = 'Confirmed_'+i;
            serLineItemList.add(sli);
            i++;
        }
        BaseTriggerHandler.bypass('TH_Quotations');
        update serLineItemList;
        Test.startTest();
        QuotationPricingController.getQuotationPricingDetails(quotationId);
        QuotationPricingController.updateQuotataionSalesValue(quotationId,2,3,4,1,2,'2018-02-20','2018-02-20');
        Test.stopTest();
        BaseTriggerHandler.clearBypass('TH_Quotations');	
        
    }
}