Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Lead_Nurture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Nurture</label>
        <referenceTo>Lead_Nurture__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Beach_relaxation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Beach relaxation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Nurture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exists as Lead Nurture</label>
        <referenceTo>Lead_Nurture__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Did the Client agree to receive the Safari365 Newsletter or not?</inlineHelpText>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Lead_Nurture__c.object
<CustomObject>
    <fields>
        <fullName>Beach_relaxation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Beach relaxation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Nurture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Nurture</label>
        <referenceTo>Lead_Nurture__c</referenceTo>
        <relationshipLabel>Lead Nurturing</relationshipLabel>
        <relationshipName>Lead_Nurturing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <label>Lead Nurture</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Lead Nurture Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Nurturing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/LeadNurturingHandler_Test.cls
@isTest
public class LeadNurturingHandler_Test {
    static Lead_Nurture__c testLeadNurture;
    static Lead testLeadRec;
    static Account testAccountRec;
    static Contact testContactRec;
    public static void setupTestData(){
        testAccountRec = new Account();
        testAccountRec.Name = 'Test Account';
        testAccountRec.Newsletter__c= true;
        insert testAccountRec;
        
        testContactRec = new Contact();
        testContactRec.LastName = 'test';
        testContactRec.Email = 'test@gmail.com';
        insert testContactRec;
        
        testLeadRec = new Lead();
        testLeadRec.Email = 'test@gmail.com';
        testLeadRec.LastName = 'lead test';
        testLeadRec.Company = 'company1';
        //testLeadRec.ConvertedContactId = testContactRec.id;
        //testLeadRec.ConvertedDate = System.today();
        insert testLeadRec;
        
        testLeadNurture = new Lead_Nurture__c();
        testLeadNurture.Email__c = 'test@gmail.com';
        testLeadNurture.First_Name__c = 'test1';
        //testLeadNurture.Countries_of_Interest__c ='South Africa;Zambia';
        insert testLeadNurture;
        
        
    }
    
    public testmethod static void testLeadNurtureUpdate(){
        setupTestData();
        Test.startTest();
        Lead_Nurture__c testLeadNurture1 = new Lead_Nurture__c();
        testLeadNurture1.Email__c = 'test@gmail.com';
        //testLeadNurture1.First_Name__c= 'test2';
        insert testLeadNurture1;
        testLeadNurture1.Beach_relaxation__c = true;
        //testLeadNurture1.Countries_of_Interest__c ='South Africa;Zambia';
        update testLeadNurture1;
        Test.stopTest();
    }
    
    public testmethod static void testLeadUpdate(){
        setupTestData();
        Test.startTest();
        testLeadRec.Country ='SA';
        update testContactRec;
        Test.stopTest();
    }
    
    public testmethod static void testContactUpdate(){
        setupTestData();
        Test.startTest();
        testContactRec.Birthdate = System.today();
        update testContactRec;
        Test.stopTest();
    }
}