Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ExchangeRates__c.object
<CustomObject>
    <fields>
        <fullName>BaseCurrency__c</fullName>
        <label>BaseCurrency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USD__c</fullName>
        <label>USD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>ExchangeRate</label>
    <nameField>
        <displayFormat>ER-{000000000}</displayFormat>
        <label>ExchangeRates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExchangeRates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/GoogleDriveSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expired_In__c</fullName>
        <label>Expired In</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Updated__c</fullName>
        <label>Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TeamDrive_Folder_Id__c</fullName>
        <label>TeamDrive Folder Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GoogleDriveSetting</label>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Display_Currency__c</fullName>
        <inlineHelpText>Choose the most likely Currency your client will want to pay in (based on their Country of Residence) The client can change this in the MembersClub if they desire, but will be unable to change once the Quotation goes to stage &quot;Raised Booking Confirmation&quot;</inlineHelpText>
        <label>Client Display Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exchange_Currency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <formula>Opportunity__r.Arrival_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Arrival Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entitled_to_Photobook_s__c</fullName>
        <inlineHelpText>How many Photobooks is this passenger entitled to? Enter a number only</inlineHelpText>
        <label>Entitled to Photobook(s)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers (New Account)</relationshipLabel>
        <relationshipName>Passengers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PassengerType__c</fullName>
        <label>Passenger Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adult</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Infant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/PassengerQuotationMapping__c.object
<CustomObject>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PassengerQuotationMapping</label>
    <nameField>
        <displayFormat>PQM-{00000000}</displayFormat>
        <label>PassengerQuotationMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PassengerQuotationMappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/QuotationLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipName>QuotationLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quotation Line Item</label>
    <nameField>
        <label>Quotation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TravelStartDate__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>QuotationLine__c</fullName>
        <label>Quotation Line</label>
        <referenceTo>QuotationLineItem__c</referenceTo>
        <relationshipName>ServiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Line Item</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceLine Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItemPassengersMapping__c.object
<CustomObject>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>ServiceLineItemPassengersMappings</relationshipLabel>
        <relationshipName>ServiceLineItemPassengersMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Line Item</label>
        <referenceTo>ServiceLineItem__c</referenceTo>
        <relationshipLabel>ServiceLineItemPassengersMappings</relationshipLabel>
        <relationshipName>ServiceLineItemPassengersMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ServiceLineItemPassengersMapping</label>
    <nameField>
        <displayFormat>SLIP-{00000000}</displayFormat>
        <label>ServiceLineItemPassengersMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceLineItemPassengersMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_MultiSelectCheckboxPassengerCTRL.cls
@isTest
private class Test_MultiSelectCheckboxPassengerCTRL {
    
    static List<Opportunity> opportunitys = new List<Opportunity>();
    static List<Account> accounts = new List<Account>();
    static List<Passenger__c> passengers = new List<Passenger__c>();
    static List<Quotations__c> Quotations = new List<Quotations__c>();
    static List<QuotationLineItem__c> quotationLineItems = new List<QuotationLineItem__c>();
    static QuotationBuilderDatabaseQueries dbQueries = new QuotationBuilderDatabaseQueries();
    static List<PassengerQuotationMapping__c> passengerQuotations = new List<PassengerQuotationMapping__c>();
    static List<ServiceLineItem__c> slis = new List<ServiceLineItem__c>();
    static List<ServiceLineItemPassengersMapping__c> sliPassengers = new List<ServiceLineItemPassengersMapping__c>();
    static List<ExchangeRates__c> exchangeRates = new List<ExchangeRates__c>();
    static Integer recordCount =3;
    
    static void setupInsertData()
    {
        User us = TestDataFactory.createUser(true, '', true);
        System.runAs(us){
            Account accountRec = new Account();
            accountRec.Name = 'Unit Test Account';
            accountRec.BillingStreet = '123 Unit Test Street';
            accountRec.BillingCity='Dallas';
            accountRec.BillingState = 'TX';
            accountRec.BillingPostalCode = '75006';
            accountRec.BillingCountry='US';
            accountRec.Industry = 'Commerical';
            accountRec.Newsletter__c= true;
            accounts.add(accountRec);
            
            DAL_BaseObject.InsertDBObjects(accounts);
            
            Map<String,Object> exchangeRateMap = new Map<String,Object>();
            exchangeRateMap.put('BaseCurrency__c','USD');
            exchangeRateMap.put('USD__c',10);
            for(Integer i = 0 ; i <recordCount; i++)
            {
                exchangeRates.add((ExchangeRates__c) TestDataFactory.operationOnObjectRecord(null, 'ExchangeRates__c', exchangeRateMap));
            }
            DAL_BaseObject.InsertDBObjects(exchangeRates);
            Date arrivaleDate = Date.newInstance(2008,1,1);
            Map<String,Object>  accountOpportunityMap = new Map<String,Object>();
            for(Account acc:accounts)
            {
                accountOpportunityMap.put('AccountId', acc.ID);
                accountOpportunityMap.put('StageName', 'Prospect');
                accountOpportunityMap.put('Arrival_Date__c',arrivaleDate);
                accountOpportunityMap.put('TravelEndDate__c',system.today().addDays(5));
                accountOpportunityMap.put('Client_Display_Currency__c', 'USD');
                
            }
            
            for(Integer i = 0 ; i <recordCount; i++)
            {
                opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap));
            }
            DAL_BaseObject.InsertDBObjects(opportunitys);
            
            
            Map<String,Object>  opportunityQuotationMap = new Map<String,Object>();
            Map<String,Object>  accountMap = new Map<String,Object>();
            for(Opportunity opp:opportunitys)
            {
                opportunityQuotationMap.put('Opportunity__c', opp.ID);
                opportunityQuotationMap.put('TravelStartDate__c',system.today());
                opportunityQuotationMap.put('TravelEndDate__c',system.today().addDays(3));
                accountMap.put('Account__c' ,accounts[0].id );
                accountMap.put('New_Account__c' ,accounts[0].id );
                accountMap.put('Opportunity__c' ,opp.id );
                
                
            }
            
            for(Integer i = 0 ; i <recordCount; i++)
            {
                passengers.add((Passenger__c) TestDataFactory.operationOnObjectRecord(null, DAL_Passenger.OBJECT_NAME, accountMap));
            }
            if(recordCount>1){
                passengers[1].Entitled_to_Photobook_s__c=1 ;
                passengers[1].Is_Primary__c=true;
                passengers[1].Account__c=accounts[0].id ;
                passengers[1].New_Account__c=accounts[0].id ;
                passengers[1].Opportunity__c=opportunitys[1].id ;
            }
            if(recordCount>2){
                passengers[2].Entitled_to_Photobook_s__c=1 ;
                passengers[2].Is_Primary__c=true;
                passengers[2].Account__c=accounts[0].id ;
                passengers[2].New_Account__c=accounts[0].id ;
                passengers[2].Opportunity__c=opportunitys[2].id ;
                passengers[2].PassengerType__c='Child';
            }
            DAL_BaseObject.InsertDBObjects(passengers);
            
            for(Integer i = 0 ; i <recordCount; i++)
            {
                Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap));
            }
             BaseTriggerHandler.bypass('OpportunityTriggerHandler');
            DAL_BaseObject.InsertDBObjects(Quotations);
             BaseTriggerHandler.clearBypass('OpportunityTriggerHandler');
            
            Map<String,Object>  passengerQuotationMapingMap = new Map<String,Object>();
            passengerQuotationMapingMap.put('Passenger__c',passengers[0].Id);
            passengerQuotationMapingMap.put('Quotation__c',Quotations[0].Id);
            for(Integer i = 0 ; i <recordCount; i++)
            {
                passengerQuotations.add((PassengerQuotationMapping__c) TestDataFactory.operationOnObjectRecord(null, 'PassengerQuotationMapping__c', passengerQuotationMapingMap));
            }
            DAL_BaseObject.InsertDBObjects(passengerQuotations);
            
            Map<String,Object>  quotationLineItemQuotationMapingMap = new Map<String,Object>();
            quotationLineItemQuotationMapingMap.put('Quotation__c',Quotations[0].Id);
           
            for(Integer i = 0 ; i <recordCount; i++)
            {
                quotationLineItems.add((QuotationLineItem__c) TestDataFactory.operationOnObjectRecord(null, 'QuotationLineItem__c', quotationLineItemQuotationMapingMap));
            }
            DAL_BaseObject.InsertDBObjects(quotationLineItems);
            
            List<QuotationLineItem__c> getQuotationLineItemList= dbQueries.GetQuotationLineItemList(Quotations[0].id);
            
            Map<String, Object> quoationServiceLineMap =new Map<String, Object>();
            for(QuotationLineItem__c quoli: getQuotationLineItemList)
            {
                quoationServiceLineMap.put('QuotationLine__c',quoli.Id);
            }
            
            for(Integer i = 0 ; i <recordCount; i++)
            {
                slis.add((ServiceLineItem__c) TestDataFactory.operationOnObjectRecord(null, 'ServiceLineItem__c', quoationServiceLineMap));
            }
            DAL_BaseObject.InsertDBObjects(slis);
            
            
            Map<String,Object>  passengerSLIMapingMap = new Map<String,Object>();
            passengerSLIMapingMap.put('Passenger__c',passengers[0].Id);
            passengerSLIMapingMap.put('Service_Line_Item__c',slis[0].Id);
            for(Integer i = 0 ; i <recordCount; i++)
            {
                sliPassengers.add((ServiceLineItemPassengersMapping__c) TestDataFactory.operationOnObjectRecord(null, 'ServiceLineItemPassengersMapping__c', passengerSLIMapingMap));
            }
            DAL_BaseObject.InsertDBObjects(sliPassengers);
            GoogleDriveSetting__c GDSetting= new GoogleDriveSetting__c();
            GDSetting.Access_Token__c='ya29.Gly7Bf_N4RntWboIxqzepsNUK6peHCP128fFoFIngVB0jYcbfcu1pohoYe4Ix35AD5VT2rEUpJbBzoGmhO5usEX_iOEMVIlsW0texKNF7cx4SGkBCBkTeKeAg0YB3w';
            GDSetting.Expired_In__c='3600';
            GDSetting.Client_Id__c = '1064689029437-o8cb1ese4j3vr2cjne1jj7d5nupe40qd.apps.googleusercontent.com';
            GDSetting.Client_Secret__c = '0fOjg-EicipIWsIxRbLwbYGy';
            GDSetting.Refresh_Token__c = '1/PNE2SPiiVlD-c229simV0WbsTxmriVaB-ksm1CZKdEw';
            GDSetting.TeamDrive_Folder_Id__c ='0AGVNCjd9GIIQUk9PVA';
            GDSetting.Last_Updated__c=DateTime.Now().adddays(-1);
            insert GDSetting;
            
        }   
    }
    
    static testMethod void saveTest() {
        setupInsertData();
        
        Test.startTest();
        PageReference pageRef = Page.MultiSelectCheckboxForPassengers;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('retURL', String.valueOf(opportunitys[0].Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(Quotations[0]);
        MultiSelectCheckboxPassengerController ctrl = new MultiSelectCheckboxPassengerController(sc);
        ctrl.parentID= opportunitys[0].Id;
        List<string> SelectedPassengers = new List<String>();
        SelectedPassengers.add(passengers[0].Id);
        ctrl.SelectedPassengers = SelectedPassengers;
        ctrl.Save();
        ctrl.Cancel();
        Test.stopTest();
        
    }
    static testMethod void saveTest1() {
        if(recordCount>1){
            
            setupInsertData();
            
            Test.startTest();
            PageReference pageRef = Page.MultiSelectCheckboxForPassengers;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('retURL', String.valueOf(opportunitys[1].Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(Quotations[1]);
            MultiSelectCheckboxPassengerController ctrl = new MultiSelectCheckboxPassengerController(sc);
            ctrl.parentID= opportunitys[1].Id;
            List<string> SelectedPassengers = new List<String>();
            SelectedPassengers.add(passengers[1].Id);
            ctrl.SelectedPassengers = SelectedPassengers;
            ctrl.Save();
            ctrl.Cancel();
            Test.stopTest();
        }
        
    }
    static testMethod void saveTest2() {
        if(recordCount>2){
            
            setupInsertData();
            
            Test.startTest();
            PageReference pageRef = Page.MultiSelectCheckboxForPassengers;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('retURL', String.valueOf(opportunitys[2].Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(Quotations[2]);
            MultiSelectCheckboxPassengerController ctrl = new MultiSelectCheckboxPassengerController(sc);
            ctrl.parentID= opportunitys[2].Id;
            List<string> SelectedPassengers = new List<String>();
            SelectedPassengers.add(passengers[2].Id);
            ctrl.SelectedPassengers = SelectedPassengers;
            ctrl.Save();
            ctrl.Cancel();
            Test.stopTest();
        }
        
    }
    
}