Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ExchangeRates__c.object
<CustomObject>
    <fields>
        <fullName>BaseCurrency__c</fullName>
        <label>BaseCurrency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>ExchangeRate</label>
    <nameField>
        <displayFormat>ER-{000000000}</displayFormat>
        <label>ExchangeRates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExchangeRates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <formula>Opportunity__r.Arrival_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Arrival Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/PassengerQuotationMapping__c.object
<CustomObject>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PassengerQuotationMapping</label>
    <nameField>
        <displayFormat>PQM-{00000000}</displayFormat>
        <label>PassengerQuotationMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PassengerQuotationMappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/QuotationLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipName>QuotationLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quotation Line Item</label>
    <nameField>
        <label>Quotation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TravelStartDate__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Service_Line_Item_ChargeType__c.object
<CustomObject>
    <description>This object will have the details for Service Line Items. The details this object will have are Charge Type, Currency, Nett Cost, Markup (%) and Total.</description>
    <fields>
        <fullName>Markup__c</fullName>
        <label>%</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Overide_Markup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overide Markup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Line Item</label>
        <referenceTo>ServiceLineItem__c</referenceTo>
        <relationshipLabel>Service Line Item ChargeTypes</relationshipLabel>
        <relationshipName>Service_Line_Item_ChargeTypes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Line Item ChargeType</label>
    <nameField>
        <displayFormat>SLICT-{00000000}</displayFormat>
        <label>Service Line Item Charge Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Item ChargeTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Markup__c</fullName>
        <label>MarkUp</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuotationLine__c</fullName>
        <label>Quotation Line</label>
        <referenceTo>QuotationLineItem__c</referenceTo>
        <relationshipName>ServiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Supplier_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Service Line Item</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceLine Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_TH_ServiceLineItemChargeType.cls
@isTest
private class Test_TH_ServiceLineItemChargeType {

    static List<ServiceLineItem__c> ServiceLineItems = new List<ServiceLineItem__c>();
    static List<Service_Line_Item_ChargeType__c> ServiceLineItemsChargeTypes= new List<Service_Line_Item_ChargeType__c>();
    static List<QuotationLineItem__c> QuotationLineItems = new List<QuotationLineItem__c>();
    static List<Quotations__c> Quotations = new List<Quotations__c>();
   	static List<Opportunity> opportunitys = new List<Opportunity>();
   	static List<Passenger__c> passengers = new List<Passenger__c>();
   	static List<PassengerQuotationMapping__c> selectedPassengers = new List<PassengerQuotationMapping__c>();
   	static List<ExchangeRates__c> exchangeRates = new List<ExchangeRates__c>();
   	static List<Account> accounts = new List<Account>();
   	public static Integer count = 1;
    
    static void setupInsertData(){
        
       User us = TestDataFactory.createUser(true, '', true);
       System.runAs(us)
       {
           Account accountRec = new Account();
           accountRec.Name = 'Unit Test Account';
           accountRec.BillingStreet = '123 Unit Test Street';
           accountRec.BillingCity='Dallas';
           accountRec.BillingState = 'TX';
           accountRec.BillingPostalCode = '75006';
           accountRec.BillingCountry='US';
           accountRec.Industry = 'Commerical';
           accountRec.Newsletter__c= true;
           accounts.add(accountRec);
           
           DAL_BaseObject.InsertDBObjects(accounts);
        
           Map<String,Object>  accountOpportunityMap = new Map<String,Object>();
           Date arrivaleDate = Date.newInstance(2008,1,1);
           Date closeDate = Date.newInstance(2008,1,1); 
           for(Account acc:accounts)
           {
               accountOpportunityMap.put('AccountId', acc.ID);
               accountOpportunityMap.put('StageName', 'Money in the Bank');
               accountOpportunityMap.put('CloseDate',closeDate);
               accountOpportunityMap.put('Arrival_Date__c',arrivaleDate);
               accountOpportunityMap.put('TravelEndDate__c',system.today().addDays(5));
           }
        
            Map<String,Object> exchangeRateMap = new Map<String,Object>();
	        exchangeRateMap.put('BaseCurrency__c','ZAR');
	        for(Integer i = 0 ; i <count; i++)
	        {
	            exchangeRates.add((ExchangeRates__c) TestDataFactory.operationOnObjectRecord(null, 'ExchangeRates__c', exchangeRateMap));
	        }
	        DAL_BaseObject.InsertDBObjects(exchangeRates);
	        
           for(Integer i = 0 ; i <count; i++)
           {
               opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap));
           }
           DAL_BaseObject.InsertDBObjects(opportunitys);
           
           Map<String,Object>  opportunityQuotationMap = new Map<String,Object>();
           Map<String,Object>  opportunityPassengerMap = new Map<String,Object>();
           for(Opportunity opp:opportunitys)
           {
               opportunityPassengerMap.put('Opportunity__c', opp.ID);
               opportunityQuotationMap.put('Opportunity__c', opp.ID);
               opportunityQuotationMap.put('TravelStartDate__c',system.today());
               opportunityQuotationMap.put('TravelEndDate__c',system.today().addDays(2));
           }
           
           for(Integer i = 0 ; i <count; i++)
           {
            passengers.add((Passenger__c) TestDataFactory.operationOnObjectRecord(null, DAL_Passenger.OBJECT_NAME, opportunityPassengerMap));
           }
           
           DAL_BaseObject.InsertDBObjects(passengers);
           
           
           for(Integer i = 0 ; i <count; i++)
           {
               Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, 'Quotations__c', opportunityQuotationMap));
           }
           
           DAL_BaseObject.InsertDBObjects(Quotations);
           
           Map<String,Object>  passengerQuotationMap = new Map<String,Object>();
           passengerQuotationMap.put('Passenger__c',passengers[0].Id);
           passengerQuotationMap.put('Quotation__c',Quotations[0].Id);
           
           
           for(Integer i = 0 ; i <count; i++)
           {
               selectedPassengers.add((PassengerQuotationMapping__c) TestDataFactory.operationOnObjectRecord(null, 'PassengerQuotationMapping__c', passengerQuotationMap));
           }
           DAL_BaseObject.InsertDBObjects(selectedPassengers);
           
           Set<Id> quotationIds = new Set<Id>();
  		   for(Quotations__c quotat:Quotations)
  		   {
  		  	 quotationIds.add(quotat.id);
  		   }
  		   List<QuotationLineItem__c> quotationLineItems = DAL_Quotations.getAllQuotationsLineItems(quotationIds);
           
           Map<String,Object>  serviceLineQuotationMap = new Map<String,Object>();
           for(QuotationLineItem__c qli:quotationLineItems)
           {
          	 serviceLineQuotationMap.put('QuotationLine__c',qli.Id);
          	 serviceLineQuotationMap.put('Service_Status__c','Confirmed');
           }
           for(Integer i = 0 ; i <count; i++)
           {
               ServiceLineItems.add((ServiceLineItem__c) TestDataFactory.operationOnObjectRecord(null, 'ServiceLineItem__c', serviceLineQuotationMap));
           }
  		    DAL_BaseObject.InsertDBObjects(ServiceLineItems);
  		    
  		   Map<String,Object>  serviceLineChargeTypeMap = new Map<String,Object>();
  		   for(ServiceLineItem__c sli:ServiceLineItems)
           {
          	 serviceLineChargeTypeMap.put('Service_Line_Item__c',sli.Id);
           }
  		   for(Integer i = 0 ; i <count; i++)
           {
               ServiceLineItemsChargeTypes.add((Service_Line_Item_ChargeType__c) TestDataFactory.operationOnObjectRecord(null, 'Service_Line_Item_ChargeType__c', serviceLineChargeTypeMap));
           }
  		    DAL_BaseObject.InsertDBObjects(ServiceLineItemsChargeTypes); 
    	}
    }
    
    @isTest  
  	static void testBeforeUpdatServiceLineItem() {
  		
  		setupInsertData();
  		Test.startTest();
  		   List<Service_Line_Item_ChargeType__c> toUpdateRecords = new List<Service_Line_Item_ChargeType__c>();
  		   for(Service_Line_Item_ChargeType__c sliChargeTypes:ServiceLineItemsChargeTypes)
  	        {
  	        	sliChargeTypes.Overide_Markup__c = true;
  	        	sliChargeTypes.Markup__c=2.2;
  	        	toUpdateRecords.add(sliChargeTypes);
  	        }
  	        
  	        if(!toUpdateRecords.isEmpty())
  	        update toUpdateRecords;
  		Test.stopTest();    
        
  	}
    
}