Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Surname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers (New Account)</relationshipLabel>
        <relationshipName>Passengers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PassengerName__c</fullName>
        <label>PAX</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/PassengerQuotationMapping__c.object
<CustomObject>
    <fields>
        <fullName>PassengerName__c</fullName>
        <formula>Passenger__r.PassengerName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PassengerName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PassengerQuotationMapping</label>
    <nameField>
        <displayFormat>PQM-{00000000}</displayFormat>
        <label>PassengerQuotationMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PassengerQuotationMappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/PassengerDetailsController.cls
public class PassengerDetailsController {
    public List<PassengerWrapper> PassengerWs {get;set;}
    public List<Passenger__c> Passengers {get;set;}
    public List<SelectOption> PassengerSelectOptions{get;set;}
    public Passenger__c SelectedPassenger {get;set;}
    public String SelectedOption{get;set;}
    public Boolean SaveDisabled{get; set;}
    public Integer intCounter;
    
    public List<Schema.FieldSetMember> getFields() {
        return SObjectType.Passenger__c.FieldSets.PassengerFrontEnd.getFields();
    }
    
    public List<SelectOption> getPassengerSelectOptions() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('--Select Passenger--','--Select Passenger--'));
        for(Passenger__c  p:this.Passengers)
        {
            options.add(new SelectOption(p.Id,p.PassengerName__c));
        }
        return options;
    }
    
    public void onPassengerListChange()
    {
        if('--Select Passenger--' == SelectedOption)
        {
            SaveDisabled = true;
            SelectedPassenger= new Passenger__c();
            return;
        }
        else
        {
           SaveDisabled = false; 
        }
        for(PassengerWrapper  p:this.PassengerWs)
        {
            if(p.Passenger.Id==SelectedOption)
            {
                SelectedPassenger = p.Passenger;
            }
        }
    }
    public PassengerDetailsController() {
        SaveDisabled = true;
        SelectedPassenger = new Passenger__c();
        //passenger = new Passenger__c();
        Passengers = getPassengers();
        PassengerSelectOptions = getPassengerSelectOptions();
        PassengerWs = new List<PassengerWrapper>();
        
        intCounter=1;
        for(Passenger__c  p:Passengers)
        {
            PassengerWrapper pw = new PassengerWrapper();
            pw.Passenger=p;
            pw.counter =intCounter;
            PassengerWs.add(pw);
            intCounter = intCounter+1;
        }
        //onPassengerListChange();
    }
    
    private List<Passenger__c> getPassengers() {
        String quotationId = System.currentPagereference().getParameters().get('Id').replace('/','');
        //String quotationId ='a0m0E0000006nkV';
        List<PassengerQuotationMapping__c> passengerQuotationMappings=[SELECT Passenger__c FROM PassengerQuotationMapping__c WHERE Quotation__c =:quotationId] ;
        List<String> confirmedPassengerIds = new List<String>();
        for(PassengerQuotationMapping__c pqm:passengerQuotationMappings)
        {
            confirmedPassengerIds.add(pqm.Passenger__c);
        }

        
        String query = 'SELECT ';
        for(Schema.FieldSetMember f : this.getFields()) {
            query += f.getFieldPath() + ', ';
        }
        query += 'Id, Name,New_Account__c,Account__c FROM Passenger__c WHERE Id IN  (SELECT Passenger__c FROM PassengerQuotationMapping__c WHERE Quotation__c =:quotationId)' ;
        
        return Database.query(query);
    }

    public pageReference Save()
    {   
        upsert SelectedPassenger;
        List<Account> newAccounts = new list<Account>();
        Map<String, Account> passengerNameToAccountMap = new Map<String, Account>();
        Id recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
        if(SelectedPassenger.New_Account__c == NULL)
        {
            Account acc = new Account();
            acc.firstName =  SelectedPassenger.FirstName__c;
            acc.LastName = SelectedPassenger.Last_Name__c;
            //acc.Name = p.FirstName__c+''+p.PassengerName__c+''+p.Last_Name__c;
            acc.Primary_Account__c = SelectedPassenger.Account__c;
            acc.RecordTypeId = recordtypeId;
            newAccounts.add(acc);
            passengerNameToAccountMap.put(SelectedPassenger.Name,acc);
        }
        
        if(newAccounts.size()>0)
        {
            DAL_BaseObject.InsertDBObjects(newAccounts);
        }
        
        if( null != passengerNameToAccountMap.get(SelectedPassenger.Name))
            SelectedPassenger.New_Account__c = passengerNameToAccountMap.get(SelectedPassenger.Name).Id;
        
        return null;
    }
    
    
       
   public class PassengerWrapper
    {
       public Passenger__c Passenger {get; set;}
       public Integer counter {get; set;}
    }
}