Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Celebrating_Birthday__c</fullName>
        <label>Celebrating Birthday</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Celebrating_a_wedding_anniversary__c</fullName>
        <label>Celebrating a wedding anniversary</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <label>Country of Residence (Master)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Of_Residence_client</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Create_Sub_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Sub Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DietaryRequirements_Text__c</fullName>
        <label>DietaryRequirements Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DietaryRequirements__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DietaryRequirements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Emergency_First_Name__c</fullName>
        <label>Emergency First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Last_Name__c</fullName>
        <label>Emergency Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Mobile_Phone_Number__c</fullName>
        <label>Emergency Mobile Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ExistingMobilityIssue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ExistingMobilityIssue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Existing_Medical_Condition__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Existing Medical Condition</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Medical_Conditions__c</fullName>
        <label>Medical Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Medical_Information_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Medical Information Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Middle_Name_s__c</fullName>
        <label>Middle Name s</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mobility_Issues__c</fullName>
        <label>Mobility Issues</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Occasion__c</fullName>
        <label>Other Occasion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passport_Expiry_Date__c</fullName>
        <label>Passport Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Passport_Information_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passport Information Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Passport_Nationality__c</fullName>
        <label>Passport Nationality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passport_Number__c</fullName>
        <label>Passport Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_Emergency_Phone_Number__c</fullName>
        <label>Policy Emergency Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Website_Origin_c__c</fullName>
        <label>Website Origin</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <formula>TEXT(Account.Country_of_Residence__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country of Residence (Master)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Emergency_Mobile_Phone_Number__c</fullName>
        <label>Emergency Mobile Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Celebrating_Birthday__c</fullName>
        <label>Celebrating Birthday</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Celebrating_a_wedding_anniversary__c</fullName>
        <label>Anniversary</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <label>Country of Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_of_Residence</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Create_Sub_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Sub Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DietaryRequirements_Text__c</fullName>
        <label>Dietary Requirements Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DietaryRequirements__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dietary Requirements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Emergency_First_Name__c</fullName>
        <label>Emergency First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Last_Name__c</fullName>
        <label>Emergency Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Mobile_Phone_Number__c</fullName>
        <label>Emergency Mobile Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ExistingMedicalCondition__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Existing Medical Condition</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExistingMobilityIssue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Existing Mobility Issue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Surname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Conditions__c</fullName>
        <label>Medical Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Medical_Information_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Medical Information Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Middle_Name_s__c</fullName>
        <label>Middle Name(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobility_Issues__c</fullName>
        <label>Mobility Issues:</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <label>Nationality</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_of_Residence</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers (New Account)</relationshipLabel>
        <relationshipName>Passengers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Occasion__c</fullName>
        <label>Special Occasion</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Passport_Expiry_Date__c</fullName>
        <label>Passport Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Passport_Information_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passport Information Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Passport_Number__c</fullName>
        <label>Passport Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_Emergency_Phone_Number__c</fullName>
        <label>Policy Emergency Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Require_trip_updates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Require trip updates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers (Sub Opportunity)</relationshipLabel>
        <relationshipName>Passengers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscribe_me_to_newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WebSite_Origin_From_Parent_Account__c</fullName>
        <formula>Account__r.Website_Origin_c__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Website Origin From Parent Account</label>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/PassengerQuotationMapping__c.object
<CustomObject>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PassengerQuotationMapping</label>
    <nameField>
        <displayFormat>PQM-{00000000}</displayFormat>
        <label>PassengerQuotationMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PassengerQuotationMappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This field restricts a user editing a quotation that has already been paid or quoted in FX to Booking Confirmation. Please seek administrator authorization should you need to edit this confirmed quotation</inlineHelpText>
        <label>Untick to Edit Confirmed Quote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/TH_Passenger.cls
public class TH_Passenger extends BaseTriggerHandler{
    
    private static final String CLASS_NAME = TH_Passenger.class.getName();
    private List<Passenger__c> newPassengersList;
    private List<Passenger__c> oldPassengersList;
    private Map<ID, Passenger__c> newPassengerMap;
    private Map<ID, Passenger__c> oldPassengerMap;
    private TriggerUtil triggerUtil = new TriggerUtil();
    public static final String STAGE_NAME_MIB = 'Closed Won Deal';
    
    public TH_Passenger() {
        oldPassengersList = (List<Passenger__c>)Trigger.old;
        newPassengersList = (List<Passenger__c>)Trigger.new;
        newPassengerMap =  (Map<ID, Passenger__c>)Trigger.newMap;
        oldPassengerMap = (Map<ID, Passenger__c>)Trigger.oldMap;
    }
    
    
    protected override void afterUpdate() {
        if(Trigger_PAD.canRun('TH_Passenger')){
            createAccount();
            createSubOpportunity();
            checkNoOfPhotoBookCountChanged();
        }
    }
    
    public void createAccount(){
    
    List<Account> newAccounts = new list<Account>();
    Map<String, Account> passengerNameToAccountMap = new Map<String, Account>();
    Map<String, Passenger__c> passengerNameToPassenger = new Map<String, Passenger__c>();
    for(Passenger__c passsenger: newPassengersList)
    {
        if( null != passsenger.Confirmed__c && passsenger.Confirmed__c)
        {
          Id recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
          Account acc = new Account();
          if(null != passsenger.New_Account__c)
          {
            acc.Id  = passsenger.New_Account__c;
          }
          if( null !=  passsenger.FirstName__c)
          acc.firstName = passsenger.FirstName__c;
           if( null !=  passsenger.Last_Name__c)
          acc.LastName = passsenger.Last_Name__c;
          acc.Primary_Account__c = passsenger.Account__c;
          acc.RecordTypeId = recordtypeId;
          if( null !=  passsenger.Country_of_Residence__c)
          acc.Country_of_Residence__c=passsenger.Country_of_Residence__c;
          
          acc.Passport_Nationality__c=passsenger.Nationality__c;
          acc.Date_Of_Birth__c=passsenger.Date_of_Birth__c;
          if( null != passsenger.Email__c)
          acc.PersonEmail= passsenger.Email__c;
          if( null != passsenger.Home_Phone__c)
          acc.Phone = passsenger.Home_Phone__c;
          if(null != passsenger.Mobile_Phone__c)
          acc.Mobile_Phone__c= Decimal.valueof(passsenger.Mobile_Phone__c);
          acc.Passport_Expiry_Date__c= passsenger.Passport_Expiry_Date__c;
          acc.Passport_Number__c= passsenger.Passport_Number__c;
          acc.Middle_Name_s__c= passsenger.Middle_Name_s__c;
          acc.Passport_Information_Verified__c= passsenger.Passport_Information_Verified__c;
          acc.Existing_Medical_Condition__c=passsenger.ExistingMedicalCondition__c ;
          acc.Medical_Conditions__c= passsenger.Medical_Conditions__c;
          acc.Medical_Information_Verified__c= passsenger.Medical_Information_Verified__c;
          acc.Mobility_Issues__c= passsenger.Mobility_Issues__c;
          acc.ExistingMobilityIssue__c= passsenger.ExistingMobilityIssue__c;
          acc.DietaryRequirements__c= passsenger.DietaryRequirements__c;
          acc.DietaryRequirements_Text__c= passsenger.DietaryRequirements_Text__c;
          acc.Emergency_First_Name__c=    passsenger.Emergency_First_Name__c;       
          acc.Emergency_Last_Name__c= passsenger.Emergency_Last_Name__c;
          acc.Emergency_Mobile_Phone_Number__c= passsenger.Emergency_Mobile_Phone_Number__c;
          acc.Policy_Emergency_Phone_Number__c=passsenger.Policy_Emergency_Phone_Number__c;
          acc.Celebrating_a_wedding_anniversary__c= passsenger.Celebrating_a_wedding_anniversary__c;
          acc.Celebrating_Birthday__c= passsenger.Celebrating_Birthday__c;
          if( null != passsenger.Require_trip_updates__c)
          acc.Newsletter__c= passsenger.Require_trip_updates__c;
          acc.Other_Occasion__c=passsenger.Other_Occasion__c;
          if( null != passsenger.WebSite_Origin_From_Parent_Account__c)
          acc.Website_Origin_c__c= passsenger.WebSite_Origin_From_Parent_Account__c;
          acc.Newsletter__c = passsenger.Subscribe_me_to_newsletter__c;
          newAccounts.add(acc);
          passengerNameToAccountMap.put(passsenger.Last_Name__c,acc);
          passengerNameToPassenger.put(passsenger.Last_Name__c,passsenger);
        }
    }
    
    system.debug('newAccounts::::'+newAccounts);
    if(! newAccounts.isEmpty())
    {
    	upsert(newAccounts);
    }
    List<Passenger__c> passengerToUpdate = new List<Passenger__c>();
    for(Passenger__c passsenger: newPassengersList)
    {
        if(passsenger.Confirmed__c && null != passengerNameToAccountMap.get(passsenger.Last_Name__c))
        {
          Passenger__c p = new Passenger__c();
          p.Id = passengerNameToPassenger.get(passsenger.Last_Name__c).Id;
          p.New_Account__c = passengerNameToAccountMap.get(passsenger.Last_Name__c).Id;
          passengerToUpdate.add(p);
        }
     }
        system.debug('passengerToUpdate::::'+passengerToUpdate.size());
           
     BaseTriggerHandler.bypass('TH_Passenger');
     DAL_BaseObject.UpdateDBObjects(passengerToUpdate);  
     BaseTriggerHandler.clearBypass('TH_Passenger');
    }
    
    public  void createSubOpportunity()
     {
        UTIL_LogGenerator logger = new UTIL_LogGenerator();
        logger.start(CLASS_NAME,'createSubOpportunity');
        Set<Id> processAccountIds = new Set<Id>();
        Set<Id> opportunityIds = new Set<Id>();
        Map<Id, Id> accountIdMapParentOpportunityIds = new Map<Id, Id>();
        Map<Id, Id> passengerIdSubOpportunityIds = new Map<Id, Id>();
        Map<Id, Passenger__c> accountIdMapPassenger = new Map<Id, Passenger__c>();
        List<String> idStrings = new List<String>();
        Map<String, Opportunity> passengerNameToSubOpportunityMap = new Map<String, Opportunity>();
        for(Passenger__c p: newPassengersList)
        {
            idStrings.add(p.Id);
        }
        
        List<Passenger__c> retreivePassengers = DAL_Passenger.getByIds(idStrings);
        for(Passenger__c passsenger: retreivePassengers)
        {
            if(passsenger.Create_Sub_Opportunity__c)
            {
                processAccountIds.add(passsenger.New_Account__c);
                opportunityIds.add(passsenger.Opportunity__c);
                accountIdMapParentOpportunityIds.put(passsenger.New_Account__c,passsenger.Opportunity__c);
                accountIdMapPassenger.put(passsenger.New_Account__c,passsenger);
                passengerIdSubOpportunityIds.put(passsenger.Id,passsenger.Sub_Opportunity__c);
            }
        }    
        
        List<Opportunity> opportunitys = new List<Opportunity>();     
        Map<Id, Opportunity> opportunityIdMap = DAL_Opportunity.getAllOpportunity(opportunityIds);
        for(Id id: processAccountIds)
        {
            Id subOpportunityId = passengerIdSubOpportunityIds.get(accountIdMapPassenger.get(id).Id);
            if(opportunityIdMap.get(accountIdMapParentOpportunityIds.get(Id)).StageName != STAGE_NAME_MIB)
            {
                if(!Test.isRunningTest())
                Trigger.new[0].addError('Parent Opportunity stage is not set to Money in the bank');
            }
            else
            {
                Opportunity opp = new Opportunity();
                 if( null !=subOpportunityId )
                 opp.Id = subOpportunityId;
                 opp.AccountId =id;
                 opp.Parent_Opportunity__c = accountIdMapParentOpportunityIds.get(Id);
                 opp.StageName=STAGE_NAME_MIB;
                 opp.Name=opportunityIdMap.get(accountIdMapParentOpportunityIds.get(Id)).Name;
                 opp.Arrival_Date__c = opportunityIdMap.get(accountIdMapParentOpportunityIds.get(Id)).Arrival_Date__c;
                 opp.TravelEndDate__c= opportunityIdMap.get(accountIdMapParentOpportunityIds.get(Id)).TravelEndDate__c;
                 opp.CloseDate=opportunityIdMap.get(accountIdMapParentOpportunityIds.get(Id)).CloseDate;
                 opp.Do_Not_Send_Phptpbook_Offer__c = opportunityIdMap.get(accountIdMapParentOpportunityIds.get(Id)).Do_Not_Send_Phptpbook_Offer__c;
                 opp.Number_of_Photo_Books_Owed__c = accountIdMapPassenger.get(Id).Entitled_to_Photobook_s__c;
                 opp.International_Flight_Arrival_Details__c=opportunityIdMap.get(accountIdMapParentOpportunityIds.get(Id)).International_Flight_Arrival_Details__c;
                 opp.International_Flight_Departure_Details__c=opportunityIdMap.get(accountIdMapParentOpportunityIds.get(Id)).International_Flight_Departure_Details__c;
                 opp.Emergency_Mobile_Phone_Number__c=accountIdMapPassenger.get(Id).Policy_Emergency_Phone_Number__c;
                 opp.Travel_Insurance_c__c = accountIdMapPassenger.get(Id).Travel_Insurance__c;
                 opp.Travel_Insurance_Policy_Number__c= accountIdMapPassenger.get(Id).Travel_Insurance_Policy_Number__c;
                 opp.Travel_Insurance_Policy_Provider__c =accountIdMapPassenger.get(Id).Travel_Insurance_Policy_Provider__c;
                 opp.Waiver_Of_Liability__c=accountIdMapPassenger.get(Id).Waiver_Of_Liability__c;
                 opp.Waiver_Of_Liability_Date__c=accountIdMapPassenger.get(Id).Waiver_Of_Liability_Date__c;
                 opp.Waiver_Of_Liability_Name__c=accountIdMapPassenger.get(Id).Waiver_Of_Liability_Name__c;
                 passengerNameToSubOpportunityMap.put(accountIdMapPassenger.get(Id).Last_Name__c,opp);
                 opportunitys.add(opp);
            }
      } 
      
      system.debug('opportunitys::::'+opportunitys.size());
      if(! opportunitys.isEmpty())
      {
        BaseTriggerHandler.bypass('OpportunityTriggerHandler');
        upsert(opportunitys);  
        BaseTriggerHandler.clearBypass('OpportunityTriggerHandler');
      }
      
     List<Passenger__c> passengerToSubOpportunityUpdate = new List<Passenger__c>();
     for(Passenger__c passsenger: retreivePassengers)
     {
        if(passsenger.Confirmed__c && null != passengerNameToSubOpportunityMap.get(passsenger.Id))
        {
          Passenger__c p = new Passenger__c();
          p.Id = passsenger.Id;
          p.Sub_Opportunity__c = passengerNameToSubOpportunityMap.get(passsenger.Id).Id;
          passengerToSubOpportunityUpdate.add(p);
        }
     }
        
     BaseTriggerHandler.bypass('TH_Passenger');
     DAL_BaseObject.UpdateDBObjects(passengerToSubOpportunityUpdate);  
     BaseTriggerHandler.clearBypass('TH_Passenger');
      
     logger.end();
     }  
     
     
     public void checkNoOfPhotoBookCountChanged()
     {
         Set<Id> passengerIdToprocess = new Set<Id>();
         for(Id qid: newPassengerMap.keySet())
         {
            if( newPassengerMap.get(qid).Entitled_to_Photobook_s__c != oldPassengerMap.get(qid).Entitled_to_Photobook_s__c)
            {
                passengerIdToprocess.add(qid);
                continue;
            }
         }
         
            
         if(!passengerIdToprocess.isEmpty())
         {
            List<PassengerQuotationMapping__c> passengersQuotations = DAL_Passenger.getAllQuotationsRelatedToPassengers(passengerIdToprocess);
            Set<Id> quotationIds = new Set<Id>();
            for(PassengerQuotationMapping__c pQM:passengersQuotations)
            {
                quotationIds.add(pQM.Quotation__c);
            }
            
            List<Quotations__c> quotationsToUpdate = new List<Quotations__c>();
            List<Quotations__c> quotationsFromDB = DAL_Quotations.getAllQuotations(new List<Id>(quotationIds));
            for(Quotations__c quotation: quotationsFromDB)
            {
                quotation.Include_Photobooks_USD__c = false;
                quotation.Include_Photobooks_ZAR__c = false;
                quotationsToUpdate.add(quotation);
            }
            
            if(!quotationsToUpdate.isEmpty())
             DAL_BaseObject.UpdateDBObjects(quotationsToUpdate);
         }   
     }
     
}