Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Exposure_ROE__c.object
<CustomObject>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipName>Quotation_ROE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Exposure ROE</label>
    <nameField>
        <displayFormat>ROE-{00000000}</displayFormat>
        <label>Exposure ROE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exposure ROE</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Include_Passenger_Insurance_USD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Passenger Emergency Evac in USD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_Passenger_Insurance_ZAR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Passenger Emergency Evac in ZAR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_Photobooks_USD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Photobooks in USD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_Photobooks_ZAR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Photobooks in ZAR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_by_Consultant__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this box will add this Quotation value ( Sale and Cost) to the main Opportunity value for &quot;Closed Won Deal&quot; Do this if the client is confirming multiple quotations</inlineHelpText>
        <label>Always Include this Quote in Opp Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quotation_Stage__c</fullName>
        <label>Quotation Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quoting</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Raised Invoice</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TravelStartDate__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_DAL_ExposureRoe.cls
@isTest
private class Test_DAL_ExposureRoe {
	
   static List<Quotations__c> Quotations = new List<Quotations__c>();
   static List<Opportunity> opportunitys = new List<Opportunity>();
   static List<Exposure_ROE__c> ExposureROEs = new List<Exposure_ROE__c>();
   static List<Account> accounts = new List<Account>();
   public static Integer OpportunityCount = 4;

    @testSetup static void setupInsertData(){
       
       User us = TestDataFactory.createUser(true, '', true);
       System.runAs(us)
       {
	       Account accountRec = new Account();
	       accountRec.Name = 'Unit Test Account';
	       accountRec.BillingStreet = '123 Unit Test Street';
	       accountRec.BillingCity='Dallas';
	       accountRec.BillingState = 'TX';
	       accountRec.BillingPostalCode = '75006';
	       accountRec.BillingCountry='US';
	       accountRec.Industry = 'Commerical';
	       accountRec.Newsletter__c= true;
	       accounts.add(accountRec);
	       
	       DAL_BaseObject.InsertDBObjects(accounts);
	        
	        Map<String,Object>  accountOpportunityMap = new Map<String,Object>();
	        for(Account acc:accounts)
	        {
	            accountOpportunityMap.put('AccountId', acc.ID);
	            accountOpportunityMap.put('StageName', 'Prospect');
	        }
	        
	        for(Integer i = 0 ; i <OpportunityCount; i++)
	        {
	            opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap));
	        }
	        DAL_BaseObject.InsertDBObjects(opportunitys);
	        
	        Map<String,Object>  opportunityQuotationMap = new Map<String,Object>();
	        for(Opportunity opp:opportunitys)
	        {
	            opportunityQuotationMap.put('Opportunity__c', opportunitys[0].ID);
	            opportunityQuotationMap.put('TravelStartDate__c',system.today());
	            opportunityQuotationMap.put('TravelEndDate__c',system.today().addDays(500));
	            opportunityQuotationMap.put('Include_Passenger_Insurance_USD__c',true);
	            opportunityQuotationMap.put('Include_Passenger_Insurance_ZAR__c',false);
	            opportunityQuotationMap.put('Include_Photobooks_USD__c',true);
	            opportunityQuotationMap.put('Include_Photobooks_ZAR__c',false);
	            opportunityQuotationMap.put('Quotation_Stage__c','Confirmed');
	            opportunityQuotationMap.put('Primary_by_Consultant__c',false);
	        }
	        
	        for(Integer i = 0 ; i <OpportunityCount; i++)
	        {
	            Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap));
	        }
	        DAL_BaseObject.InsertDBObjects(Quotations);
	        
	        Map<String,Object>  ExposureROEOpportunityMap = new Map<String,Object>();
	        for(Opportunity opp:opportunitys)
	        {
	            ExposureROEOpportunityMap.put('Quotation__c', Quotations[0].ID);
	        }
	        
	        for(Integer i = 0 ; i <OpportunityCount; i++)
	        {
	            ExposureROEs.add((Exposure_ROE__c) TestDataFactory.operationOnObjectRecord(null, 'Exposure_ROE__c', ExposureROEOpportunityMap));
	        }
	        DAL_BaseObject.InsertDBObjects(ExposureROEs);
      }
    }
   
    static testMethod void getByQuotationIdTest() {
    	
    	Set<Id> quotationIds = new Set<Id>();
    	Test.startTest();
    	for(Opportunity opp:opportunitys)
        {
            quotationIds.add(opp.ID);
        }
    	DAL_ExposureRoe.getByQuotationId(quotationIds);
    	Test.stopTest();
        
    }
}