Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Consultant_Target_Monthly__c.object
<CustomObject>
    <label>Individual Cons. GP Setup (Monthly)</label>
    <nameField>
        <displayFormat>CTM-{00000000}</displayFormat>
        <label>ID - Individ Cons. GP</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. GP Setup (Monthly)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Consultant_Target_Monthly__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Target Monthly</label>
        <referenceTo>Consultant_Target_Monthly__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <label>Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Surname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers (New Account)</relationshipLabel>
        <relationshipName>Passengers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PassengerName__c</fullName>
        <label>PAX</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PassengerType__c</fullName>
        <label>Passenger Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adult</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Infant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <formula>CASESAFEID(QuotationLine__r.Quotation__r.Opportunity__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OpportunityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Email__c</fullName>
        <label>Opportunity Owner Email</label>
        <type>Email</type>
    </fields>
    <label>Service Line Item</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceLine Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler extends BaseTriggerHandler {
  
    private List<Opportunity> newOptList;
    private List<Opportunity> oldOptList;
    private Map<ID, Opportunity> newOptMap;
    private Map<ID, Opportunity> oldOptMap;
    private TriggerUtil triggerUtil = new TriggerUtil();

    public OpportunityTriggerHandler()
     {
        oldOptList = (List<Opportunity>)Trigger.old;
        newOptList = (List<Opportunity>)Trigger.new;
        newOptMap =  (Map<ID, Opportunity>)Trigger.newMap;
        oldOptMap = (Map<ID, Opportunity>)Trigger.oldMap;
    }
    
    protected override void beforeInsert()
    { 
        if(Trigger_PAD.canRun('OpportunityTriggerHandler'))
        {
            updateCloseDate();
            updateEmailFromAccount();
        }
    } 

    protected override void beforeUpdate()
    {
        if(Trigger_PAD.canRun('OpportunityTriggerHandler'))
        {
           //updateCloseDate(); 
           updateEmailFromAccount(); 
           updateOwnerEmailOnServiceLineItem();              
        }
    }
    
    protected override void afterInsert()
    {
        if(Trigger_PAD.canRun('OpportunityTriggerHandler'))
        {
           createMainAccountAsPassenger();        
        }
    }
    
    
    protected override void afterUpdate()
    {
        if(Trigger_PAD.canRun('OpportunityTriggerHandler'))
        {
           List<Opportunity> updateoppList = updateCloseDateAfterUpdate(); 
           system.debug('updateoppList:::'+updateoppList);  
           UpdateTargetValueOpportunityService.updateTargetMonthlyValues(updateoppList,oldOptMap);
        }
    }
    
    protected override void afterDelete()
    {
        if(Trigger_PAD.canRun('OpportunityTriggerHandler'))
        {
           UpdateTargetValueOpportunityService.deleteTargetMonthlyValues(oldOptList,oldOptMap);
        }
    }
    
    public void updateOwnerEmailOnServiceLineItem()
    {
      Set<String> opportunityToProcess = new Set<String>();
      Set<Id> ownerIdSet = new Set<ID>();
      Map<String,String> opportunityOwnerMap = new Map<String,String>();
        for(Id oppid: newOptMap.keySet())
        {
            if( newOptMap.get(oppid).OwnerId != null
               &&oldOptMap.get(oppid).OwnerId != newOptMap.get(oppid).OwnerId)
            {
                opportunityToProcess.add(newOptMap.get(oppid).Id);
                ownerIdSet.add(newOptMap.get(oppid).OwnerId);
                opportunityOwnerMap.put(newOptMap.get(oppid).Id,newOptMap.get(oppid).OwnerId);
            }
            
       }
       
       if(!ownerIdSet.isEmpty())
       {
           Map<Id,User> userIdMap = DAL_USER.getUserByIds(ownerIdSet);
           List<ServiceLineItem__c> slis = QuotationBuilderDatabaseQueries.allServiceLineItemRelatedToOpportunityIds(opportunityToProcess);
           List<ServiceLineItem__c> slisToUpdate = new List<ServiceLineItem__c>();
           for(ServiceLineItem__c sli:slis)
           {
                User u = userIdMap.get(opportunityOwnerMap.get(Id.valueof(sli.OpportunityId__c)));
                sli.Opportunity_Owner_Email__c =u.Email;
                slisToUpdate.add(sli);
           }
           
           if(!slisToUpdate.isEmpty())
           update slisToUpdate;
       }
    }  
    
    
    public void createMainAccountAsPassenger()
    {
        List<Passenger__c> passengers  = new List<Passenger__c>();
        Set<Id> accountIds = new Set<Id>();
        for(Opportunity opp: newOptList)
        {
            accountIds.add(opp.AccountId);
        }
     
        Map<Id, Account> accountIdMap = DAL_Account.getById(accountIds);
        for(Opportunity opp: newOptList)
        {
            Passenger__c pass = new Passenger__c();
            pass.FirstName__c= accountIdMap.get(opp.AccountId).FirstName;
            pass.Last_Name__c= accountIdMap.get(opp.AccountId).LastName;
            pass.New_Account__c = opp.AccountId;
            pass.Confirmed__c = true;
            pass.Is_Primary__c = true;
            pass.Opportunity__c = opp.id;
            pass.PassengerType__c = 'Adult';
            pass.PassengerName__c = accountIdMap.get(opp.AccountId).FirstName +' '+accountIdMap.get(opp.AccountId).LastName;
            passengers.add(pass);
        }
       
       if(! passengers.isEmpty())
       {
        BaseTriggerHandler.byPass('TH_Passenger');
        DAL_BaseObject.InsertDBObjects(passengers);
        BaseTriggerHandler.clearBypass('TH_Passenger');
       }  
       
    }
     public  void updateEmailFromAccount()
     {
         Set<Id>  accountIDSet= new Set<Id>();
         for(Opportunity OppRec : newOptList)
         {
            accountIDSet.add(OppRec.AccountId);
         }
        
         Map<Id,Account> accountMap = new Map<ID, Account>([Select Id ,PersonEmail from Account where Id IN:accountIDSet]);
         
         for(Opportunity OppRecs : newOptList)
          {
            Account acc = accountMap.get(OppRecs.AccountId);
            if(null!=acc && null!=acc.PersonEmail)
            {
                OppRecs.Email__c=acc.PersonEmail;
            }
          }    
     }
  
     public  void updateCloseDate(){
              
        for(Opportunity OppRec : newOptList)
        {
           if(!(OppRec.StageName == 'Closed Won Deal') || !(OppRec.StageName == 'Money in the Bank'))
           {
                OppRec.closeDate=system.today().addDays(Integer.valueof(system.Label.Opportunity_Close_Day));
           }
           else if(OppRec.StageName == 'Closed Won Deal' || OppRec.StageName == 'Money in the Bank')
           {
                OppRec.closeDate=system.today();
           }
        }
     }    

      public List<Opportunity> updateCloseDateAfterUpdate(){
              
        List<Opportunity> opportunityToUpdate = new List<Opportunity>();
        Boolean flagToUpdate = false;
        for(Opportunity OppRec : newOptList)
        {
           
           Opportunity newOpp = null;
           Opportunity oldOpp = oldOptMap.get(OppRec.Id);
           if(OppRec.StageName != 'Closed Won Deal' 
                && OppRec.StageName != 'Money in the Bank'
                &&  OppRec.StageName != 'Closed Won - Cancelled' )
           {
                newOpp  = new Opportunity(Id =OppRec.Id);
                newOpp.closeDate=system.today().addDays(Integer.valueof(system.Label.Opportunity_Close_Day));
                newOpp.Gross_Profit__c = OppRec.Gross_Profit__c;
                newOpp.StageName = OppRec.StageName;
                //newOpp =OppRec;
           }
           else if( oldOpp.StageName != OppRec.StageName 
                    &&( OppRec.StageName == 'Closed Won Deal' 
                       || OppRec.StageName == 'Closed Won - Cancelled' 
                        || OppRec.StageName == 'Money in the Bank'))
           {
                newOpp  = new Opportunity(Id =OppRec.Id);
                newOpp.closeDate = system.today();
                newOpp.Gross_Profit__c = OppRec.Gross_Profit__c;
                newOpp.StageName = OppRec.StageName;
                newOpp.OwnerId = OppRec.OwnerId;
                //newOpp =OppRec;
           }
           else if( oldOpp.StageName == OppRec.StageName 
                    &&( OppRec.StageName == 'Closed Won Deal' 
                       || OppRec.StageName == 'Closed Won - Cancelled' 
                        || OppRec.StageName == 'Money in the Bank'))
           {
                newOpp  = new Opportunity(Id =OppRec.Id);
                newOpp.closeDate = OppRec.closeDate;
                newOpp.Gross_Profit__c = OppRec.Gross_Profit__c;
                newOpp.StageName = OppRec.StageName;
                newOpp.OwnerId = OppRec.OwnerId;
                newOpp.Consultant_Target_Monthly__c = OppRec.Consultant_Target_Monthly__c;
                flagToUpdate = true;
           }
           
           
            if(null != newOpp )
            opportunityToUpdate.add(newOpp);
         }
           
           if(!opportunityToUpdate.isEmpty() 
                && !flagToUpdate)
           {
                BaseTriggerHandler.byPass('OpportunityTriggerHandler');
                update opportunityToUpdate;
                BaseTriggerHandler.clearBypass('OpportunityTriggerHandler');
           }
           return opportunityToUpdate;
        }

}