Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CoS__c</fullName>
        <label>CoS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <formula>If(Arrival_Date__c -60 &lt;  CloseDate ,  CloseDate ,

Arrival_Date__c -60
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_TL_Quotation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary TL Quotation</label>
        <referenceTo>TL_Quotation__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ROE__c</fullName>
        <inlineHelpText>Legacy field, not part of the Ferret system</inlineHelpText>
        <label>ROE</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/TL_Quotation__c.object
<CustomObject>
    <fields>
        <fullName>CoS__c</fullName>
        <label>CoS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TL Quotations</relationshipLabel>
        <relationshipName>TL_Quotations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Quotation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newest and/or Primary Quotation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROE__c</fullName>
        <label>ROE</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <label>Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Travel_Date__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <label>TL Quotation</label>
    <nameField>
        <displayFormat>TLQ-{00000}</displayFormat>
        <label>TL Quotation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TL Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/TLQTest.cls
@isTest
private class TLQTest{
    public static testMethod void testTLQ() {

        Test.startTest();
        
        
        
        Account a = new Account();
        a.Name='test2';
        a.Newsletter__c=true;
   //     a.RecordTypeId = '012D0000000Jjz7';
        insert a;     
        
        Opportunity o = new Opportunity();
        o.name = 'test opp';
        o.AccountId = a.Id;
        o.stagename = 'Teststage';
        o.CloseDate = System.Today();
        BaseTriggerHandler.bypass('OpportunityTriggerHandler');
        insert o;
       
        
        TL_Quotation__c tlq = new TL_Quotation__c();
        tlq.Opportunity__c = o.Id;
        tlq.Sales__c=200.00;
        
        tlq.Primary_Quotation__c = true;
        tlq.Travel_Date__c= system.today();
        
        insert tlq;
        
        tlq.ROE__c= 7.00;
        tlq.COS__c=300.00;
        update tlq;
        
        TL_Quotation__c tlq2 = new TL_Quotation__c();
        tlq2.Opportunity__c = o.Id;
        tlq2.Sales__c=200.00;
        
        tlq2.Primary_Quotation__c = true;
        
        insert tlq2;
        
        tlq2.ROE__c= 7.00;
        tlq2.COS__c=300.00;
        update tlq2;
        
   //     delete tlq;
        
        o.Primary_TL_Quotation__c = tlq.id;
        o.Arrival_Date__c=tlq.Travel_Date__c;
       // o.Invoice_Date__c=tlq.Travel_Date__c;
        update o;
        
        o.Primary_TL_Quotation__c = tlq2.id;
          o.Arrival_Date__c=tlq2.Travel_Date__c;
        //o.Invoice_Date__c=tlq2.Travel_Date__c;
        update o;
        BaseTriggerHandler.bypass('OpportunityTriggerHandler');
      //  system.assertEquals(inv.Id,[select AccountId from Contact where Id=:case1.ContactId].AccountId);
        Test.stopTest();
    }

}