Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/CRM__c.object
<CustomObject>
    <fields>
        <fullName>CODE__c</fullName>
        <externalId>true</externalId>
        <label>CODE</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOD_ID__c</fullName>
        <label>SOD ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CRM</label>
    <nameField>
        <displayFormat>CRM-{00000000}</displayFormat>
        <label>CRM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/DB4__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DB4</label>
    <nameField>
        <displayFormat>DB-{00000000}</displayFormat>
        <label>DB4 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DB4s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/LCL__c.object
<CustomObject>
    <fields>
        <fullName>CODE__c</fullName>
        <externalId>true</externalId>
        <label>CODE</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>LCL</label>
    <nameField>
        <displayFormat>LCL-{0000000}</displayFormat>
        <label>LCL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCLs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <label>Supplier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Southern Destinations</fullName>
                </value>
                <value>
                    <fullName>African Safaris</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opt__c.object
<CustomObject>
    <fields>
        <fullName>ANALYSIS4__c</fullName>
        <label>ANALYSIS4</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOCALITY__c</fullName>
        <label>LOCALITY</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOD_ID__c</fullName>
        <label>SOD_ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <label>Supplier</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>OPT</label>
    <nameField>
        <displayFormat>OPT-{0000000}</displayFormat>
        <label>OPT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/SOD__c.object
<CustomObject>
    <description>Supplier Overall Policy</description>
    <fields>
        <fullName>SOD_ID__c</fullName>
        <externalId>true</externalId>
        <label>SOD_ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SOD</label>
    <nameField>
        <displayFormat>SOD-{00000000}</displayFormat>
        <label>SOD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SODs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/SRV__c.object
<CustomObject>
    <fields>
        <fullName>ANALYSIS4__c</fullName>
        <label>ANALYSIS4</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CODE__c</fullName>
        <externalId>true</externalId>
        <label>CODE</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>SRV</label>
    <nameField>
        <displayFormat>SRV-{00000000}</displayFormat>
        <label>SRV Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SRVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_ServiceLineItem.cls
@isTest
private class Test_ServiceLineItem {

    public static List<OPT__c>  db4opts = new List<OPT__c>();
    public static List<DB4__c>  db4s= new List<DB4__c>();
    public static List<OPT__c>  crmopts = new List<OPT__c>();
    public static List<CRM__c>  crms= new List<CRM__c>();
    public static List<OPT__c>  lclopts = new List<OPT__c>();
    public static List<LCL__c>  lcls= new List<LCL__c>();
    public static List<OPT__c>  srvopts = new List<OPT__c>();
    public static List<SRV__c>  srvs= new List<SRV__c>();
    public static List<SOD__c>  sods= new List<SOD__c>();
    public static List<OPT__c>  sodopts = new List<OPT__c>();
    
    static List<Quotations__c> Quotations = new List<Quotations__c>();
    static List<Opportunity> opportunitys = new List<Opportunity>();
    static List<Account> accounts = new List<Account>();
    
    public static Integer count = 1;
    
    static void setupSODInsertData(){
        
        for(Integer i = 0 ; i <count; i++)
        {
            sods.add((SOD__c) TestDataFactory.operationOnObjectRecord(null, 'SOD__c', null));
        }
        insert sods;
        
        Map<String,Object> sodkeyValueMap = new Map<String,Object>();
        for(SOD__c sod:sods)
        {
            sodkeyValueMap.put('SOD_ID__c', sod.SOD_ID__c);
        }
    
        for(Integer i = 0 ; i <count; i++)
        sodopts.add((Opt__c) TestDataFactory.operationOnObjectRecord(null, 'Opt__c', sodkeyValueMap));
        
    }
    
    static void setupDB4InsertData(){
        
        for(Integer i = 0 ; i <count; i++)
        {
            db4s.add((DB4__c) TestDataFactory.operationOnObjectRecord(null, 'DB4__c', null));
        }
        insert db4s;
        
        Map<String,Object> db4keyValueMap = new Map<String,Object>();
        for(DB4__c db4:db4s)
        {
            db4keyValueMap.put('ANALYSIS4__c', db4.CODE__c);
        }
    
        for(Integer i = 0 ; i <count; i++)
        db4opts.add((Opt__c) TestDataFactory.operationOnObjectRecord(null, 'Opt__c', db4keyValueMap));
        
    }
    
    static void setupCRMInsertData(){
        
        for(Integer i = 0 ; i <count; i++)
        {
            crms.add((CRM__c) TestDataFactory.operationOnObjectRecord(null, 'CRM__c', null));
        }
        insert crms;
        
        Map<String,Object> crmkeyValueMap = new Map<String,Object>();
        for(CRM__c crm:crms)
        {
            crmkeyValueMap.put('Supplier__c', crm.CODE__c);
        }
    
        for(Integer i = 0 ; i <count; i++)
        crmopts.add((Opt__c) TestDataFactory.operationOnObjectRecord(null, 'Opt__c', crmkeyValueMap));
        
    }
    
    static void setupLCLInsertData(){
        
        for(Integer i = 0 ; i <count; i++)
        {
            lcls.add((LCL__c) TestDataFactory.operationOnObjectRecord(null, 'LCL__c', null));
        }
        insert lcls;
        
        Map<String,Object> keyValueMap = new Map<String,Object>();
        for(LCL__c opt:lcls)
        {
            keyValueMap.put('LOCALITY__c', opt.CODE__c);
        }
    
        for(Integer i = 0 ; i <count; i++)
        lclopts.add((Opt__c) TestDataFactory.operationOnObjectRecord(null, 'Opt__c', keyValueMap));
        
    }
    
    static void setupSRVInsertData(){
        
        for(Integer i = 0 ; i <count; i++)
        {
            srvs.add((SRV__c) TestDataFactory.operationOnObjectRecord(null, 'SRV__c', null));
        }
        insert srvs;
        
        Map<String,Object> keyValueMap = new Map<String,Object>();
        for(SRV__c opt:srvs)
        {
            keyValueMap.put('Service__c', opt.CODE__c);
        }
    
        for(Integer i = 0 ; i <count; i++)
        srvopts.add((Opt__c) TestDataFactory.operationOnObjectRecord(null, 'Opt__c', keyValueMap));
        
    }
    
    static void setupQuotationInsertData(){
       
       User us = TestDataFactory.createUser(true, '', true);
       System.runAs(us){
       Account accountRec = new Account();
       accountRec.Name = 'Unit Test Account';
       accountRec.BillingStreet = '123 Unit Test Street';
       accountRec.BillingCity='Dallas';
       accountRec.BillingState = 'TX';
       accountRec.BillingPostalCode = '75006';
       accountRec.BillingCountry='US';
       accountRec.Industry = 'Commerical';
       accountRec.Newsletter__c= true;
       accounts.add(accountRec);
       
       DAL_BaseObject.InsertDBObjects(accounts);
        
        Map<String,Object>  accountOpportunityMap = new Map<String,Object>();
        Date arrivaleDate = Date.newInstance(2008,1,1);
        Date closeDate = Date.newInstance(2008,1,1); 
        for(Account acc:accounts)
        {
            accountOpportunityMap.put('AccountId', acc.ID);
            accountOpportunityMap.put('StageName', 'Money in the Bank');
            accountOpportunityMap.put('CloseDate',closeDate);
            accountOpportunityMap.put('Arrival_Date__c',arrivaleDate);
        }
        
        for(Integer i = 0 ; i <count; i++)
        {
            opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap));
        }
        DAL_BaseObject.InsertDBObjects(opportunitys);
        
        Map<String,Object>  opportunityQuotationMap = new Map<String,Object>();
        for(Opportunity opp:opportunitys)
        {
            opportunityQuotationMap.put('Opportunity__c', opp.ID);
        }
        
        for(Integer i = 0 ; i <count; i++)
        {
            Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, 'Quotations__c', opportunityQuotationMap));
        }
        DAL_BaseObject.InsertDBObjects(Quotations);
    }
        
    }
    
}