Safari365 Prod/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ExchangeRates__c.object
<CustomObject>
    <fields>
        <fullName>BaseCurrency__c</fullName>
        <label>BaseCurrency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>ExchangeRate</label>
    <nameField>
        <displayFormat>ER-{000000000}</displayFormat>
        <label>ExchangeRates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExchangeRates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/PassengerQuotationMapping__c.object
<CustomObject>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PassengerQuotationMapping</label>
    <nameField>
        <displayFormat>PQM-{00000000}</displayFormat>
        <label>PassengerQuotationMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PassengerQuotationMappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/QuotationLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Line_Item_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipName>QuotationLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quotation Line Item</label>
    <nameField>
        <label>Quotation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TravelStartDate__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <inlineHelpText>The date when the quoted exchange rate for this quote will expire. Rate will be valid until midnight of this date South African time.</inlineHelpText>
        <label>Quotation FX Rate Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>QuotationLine__c</fullName>
        <label>Quotation Line</label>
        <referenceTo>QuotationLineItem__c</referenceTo>
        <relationshipName>ServiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Line Item</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceLine Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItemPassengersMapping__c.object
<CustomObject>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>ServiceLineItemPassengersMappings</relationshipLabel>
        <relationshipName>ServiceLineItemPassengersMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Line Item</label>
        <referenceTo>ServiceLineItem__c</referenceTo>
        <relationshipLabel>ServiceLineItemPassengersMappings</relationshipLabel>
        <relationshipName>ServiceLineItemPassengersMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ServiceLineItemPassengersMapping</label>
    <nameField>
        <displayFormat>SLIP-{00000000}</displayFormat>
        <label>ServiceLineItemPassengersMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceLineItemPassengersMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_DAL_Quotations.cls
@isTest
private class Test_DAL_Quotations {

   static List<Opportunity> opportunitys = new List<Opportunity>();
   static List<Account> accounts = new List<Account>();
   static List<Passenger__c> passengers = new List<Passenger__c>();
   static List<Quotations__c> Quotations = new List<Quotations__c>();
   static List<PassengerQuotationMapping__c> passengerQuotations = new List<PassengerQuotationMapping__c>();
   static List<ServiceLineItem__c> slis = new List<ServiceLineItem__c>();
   static List<ServiceLineItemPassengersMapping__c> sliPassengers = new List<ServiceLineItemPassengersMapping__c>();
   static Integer recordCount = 1;
   static List<QuotationLineItem__c> getQuotationLineItemList;
   static QuotationBuilderDatabaseQueries dbQueries = new QuotationBuilderDatabaseQueries();
   static List<ExchangeRates__c> exchangeRates = new List<ExchangeRates__c>();
   
   static void setupInsertData()
    {
       User us = TestDataFactory.createUser(true, '', true);
       System.runAs(us){
       Account accountRec = new Account();
       accountRec.Name = 'Unit Test Account';
       accountRec.BillingStreet = '123 Unit Test Street';
       accountRec.BillingCity='Dallas';
       accountRec.BillingState = 'TX';
       accountRec.BillingPostalCode = '75006';
       accountRec.BillingCountry='US';
       accountRec.Industry = 'Commerical';
       accountRec.Newsletter__c= true;
       accounts.add(accountRec);
       
       DAL_BaseObject.InsertDBObjects(accounts);
        
        Map<String,Object>  accountOpportunityMap = new Map<String,Object>();
        for(Account acc:accounts)
        {
            accountOpportunityMap.put('AccountId', acc.ID);
            accountOpportunityMap.put('StageName', 'Prospect');
        }
        
        Map<String,Object> exchangeRateMap = new Map<String,Object>();
        exchangeRateMap.put('BaseCurrency__c','ZAR');
        for(Integer i = 0 ; i <recordCount; i++)
        {
            exchangeRates.add((ExchangeRates__c) TestDataFactory.operationOnObjectRecord(null, 'ExchangeRates__c', exchangeRateMap));
        }
        DAL_BaseObject.InsertDBObjects(exchangeRates);
        
        for(Integer i = 0 ; i <recordCount; i++)
        {
            opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap));
        }
        DAL_BaseObject.InsertDBObjects(opportunitys);
        
        
        
        Map<String,Object>  opportunityQuotationMap = new Map<String,Object>();
        Map<String,Object>  accountMap = new Map<String,Object>();
        for(Opportunity opp:opportunitys)
        {
            opportunityQuotationMap.put('Opportunity__c', opp.ID);
            opportunityQuotationMap.put('TravelStartDate__c',system.today());
            opportunityQuotationMap.put('TravelEndDate__c',system.today().addDays(3));
            accountMap.put('Opportunity__c' ,opp.id );
        }
      
        for(Integer i = 0 ; i <recordCount; i++)
        {
            passengers.add((Passenger__c) TestDataFactory.operationOnObjectRecord(null, DAL_Passenger.OBJECT_NAME, accountMap));
        }
        DAL_BaseObject.InsertDBObjects(passengers);
        
        for(Integer i = 0 ; i <recordCount; i++)
        {
            Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap));
        }
        DAL_BaseObject.InsertDBObjects(Quotations);
        
        Map<String,Object>  passengerQuotationMapingMap = new Map<String,Object>();
        passengerQuotationMapingMap.put('Passenger__c',passengers[0].Id);
        passengerQuotationMapingMap.put('Quotation__c',Quotations[0].Id);
        for(Integer i = 0 ; i <recordCount; i++)
        {
            passengerQuotations.add((PassengerQuotationMapping__c) TestDataFactory.operationOnObjectRecord(null, 'PassengerQuotationMapping__c', passengerQuotationMapingMap));
        }
        DAL_BaseObject.InsertDBObjects(passengerQuotations);
        
       getQuotationLineItemList= dbQueries.GetQuotationLineItemList(Quotations[0].id);
       
       Map<String, Object> quoationServiceLineMap =new Map<String, Object>();
       for(QuotationLineItem__c quoli: getQuotationLineItemList)
       {
       	quoationServiceLineMap.put('QuotationLine__c',quoli.Id);
       }
       
       for(Integer i = 0 ; i <recordCount; i++)
        {
            slis.add((ServiceLineItem__c) TestDataFactory.operationOnObjectRecord(null, 'ServiceLineItem__c', quoationServiceLineMap));
        }
        DAL_BaseObject.InsertDBObjects(slis);
       
       
        Map<String,Object>  passengerSLIMapingMap = new Map<String,Object>();
        passengerSLIMapingMap.put('Passenger__c',passengers[0].Id);
        passengerSLIMapingMap.put('Service_Line_Item__c',slis[0].Id);
        for(Integer i = 0 ; i <recordCount; i++)
        {
            sliPassengers.add((ServiceLineItemPassengersMapping__c) TestDataFactory.operationOnObjectRecord(null, 'ServiceLineItemPassengersMapping__c', passengerSLIMapingMap));
        }
        DAL_BaseObject.InsertDBObjects(sliPassengers);
        
       }   
    }
    
    
    static void setupInsertData2()
    {
       User us = TestDataFactory.createUser(true, '', true);
       System.runAs(us){
       Account accountRec = new Account();
       accountRec.Name = 'Unit Test Account';
       accountRec.BillingStreet = '123 Unit Test Street';
       accountRec.BillingCity='Dallas';
       accountRec.BillingState = 'TX';
       accountRec.BillingPostalCode = '75006';
       accountRec.BillingCountry='US';
       accountRec.Industry = 'Commerical';
       accountRec.Newsletter__c= true;
       accounts.add(accountRec);
       
       DAL_BaseObject.InsertDBObjects(accounts);
        
        Map<String,Object>  accountOpportunityMap = new Map<String,Object>();
        for(Account acc:accounts)
        {
            accountOpportunityMap.put('AccountId', acc.ID);
            accountOpportunityMap.put('StageName', 'Prospect');
        }
        
        Map<String,Object> exchangeRateMap = new Map<String,Object>();
        exchangeRateMap.put('BaseCurrency__c','ZAR');
        for(Integer i = 0 ; i <recordCount; i++)
        {
            exchangeRates.add((ExchangeRates__c) TestDataFactory.operationOnObjectRecord(null, 'ExchangeRates__c', exchangeRateMap));
        }
        DAL_BaseObject.InsertDBObjects(exchangeRates);
        
        for(Integer i = 0 ; i <recordCount; i++)
        {
            opportunitys.add((Opportunity) TestDataFactory.operationOnObjectRecord(null, 'Opportunity', accountOpportunityMap));
        }
        DAL_BaseObject.InsertDBObjects(opportunitys);
        
        
        
        Map<String,Object>  opportunityQuotationMap = new Map<String,Object>();
        Map<String,Object>  accountMap = new Map<String,Object>();
        for(Opportunity opp:opportunitys)
        {
            opportunityQuotationMap.put('Opportunity__c', opp.ID);
            opportunityQuotationMap.put('TravelStartDate__c',system.today());
            opportunityQuotationMap.put('TravelEndDate__c',system.today().addDays(3));
            opportunityQuotationMap.put('Valid_Until__c',null);
            accountMap.put('Opportunity__c' ,opp.id );
        }
      
        for(Integer i = 0 ; i <recordCount; i++)
        {
            passengers.add((Passenger__c) TestDataFactory.operationOnObjectRecord(null, DAL_Passenger.OBJECT_NAME, accountMap));
        }
        DAL_BaseObject.InsertDBObjects(passengers);
        
        for(Integer i = 0 ; i <recordCount; i++)
        {
            Quotations.add((Quotations__c) TestDataFactory.operationOnObjectRecord(null, DAL_Quotations.OBJECT_NAME, opportunityQuotationMap));
        }
        DAL_BaseObject.InsertDBObjects(Quotations);
        
        Map<String,Object>  passengerQuotationMapingMap = new Map<String,Object>();
        passengerQuotationMapingMap.put('Passenger__c',passengers[0].Id);
        passengerQuotationMapingMap.put('Quotation__c',Quotations[0].Id);
        for(Integer i = 0 ; i <recordCount; i++)
        {
            passengerQuotations.add((PassengerQuotationMapping__c) TestDataFactory.operationOnObjectRecord(null, 'PassengerQuotationMapping__c', passengerQuotationMapingMap));
        }
        DAL_BaseObject.InsertDBObjects(passengerQuotations);
        
       getQuotationLineItemList= dbQueries.GetQuotationLineItemList(Quotations[0].id);
       
       Map<String, Object> quoationServiceLineMap =new Map<String, Object>();
       for(QuotationLineItem__c quoli: getQuotationLineItemList)
       {
       	quoationServiceLineMap.put('QuotationLine__c',quoli.Id);
       }
       
       for(Integer i = 0 ; i <recordCount; i++)
        {
            slis.add((ServiceLineItem__c) TestDataFactory.operationOnObjectRecord(null, 'ServiceLineItem__c', quoationServiceLineMap));
        }
        DAL_BaseObject.InsertDBObjects(slis);
       
       
        Map<String,Object>  passengerSLIMapingMap = new Map<String,Object>();
        passengerSLIMapingMap.put('Passenger__c',passengers[0].Id);
        passengerSLIMapingMap.put('Service_Line_Item__c',slis[0].Id);
        for(Integer i = 0 ; i <recordCount; i++)
        {
            sliPassengers.add((ServiceLineItemPassengersMapping__c) TestDataFactory.operationOnObjectRecord(null, 'ServiceLineItemPassengersMapping__c', passengerSLIMapingMap));
        }
        DAL_BaseObject.InsertDBObjects(sliPassengers);
        
       }   
    }
    
    
    static testMethod void GetQuotationLineItemDateTest() {
    	
    	Test.startTest();
    	setupInsertData();
    	List<Id> quotationIds = new List<Id>();
    	Set<Id> setquotationIds = new Set<Id>();
    	Set<Date> quotationDates = new Set<Date>();
        
        Date maxDate = getQuotationLineItemList[0].Line_Item_Date__c;
    	List<String> strquotationIds = new List<Id>();
    	Set<Id> opportunityIds = new Set<Id>();
        List<String> opportunityId = new List<String>();
        opportunityId.add(opportunitys[0].id);
    	opportunityIds.add(opportunitys[0].id);
    	quotationIds.add(Quotations[0].Id);
    	strquotationIds.add(Quotations[0].Id);
    	setquotationIds.add(Quotations[0].Id);
    	List<Id> quotationLineItemids = new List<Id>();
    	List<Id> serviceLineItemIds  = new List<Id>();
        Set<Id> serviceLineItemId = new Set<Id>();
        Set<String> chargeTypes = new Set<String>();
        chargeTypes.add('abc');
        chargeTypes.add('xyz');
    	for(ServiceLineItem__c serv:slis)
    	{
    		serviceLineItemIds.add(serv.Id);
            serviceLineItemId.add(serv.Id);
    	}
    	for(QuotationLineItem__c qli:getQuotationLineItemList)
    	{
    		quotationLineItemids.add(qli.Id);
    		quotationDates.add(qli.Line_Item_Date__c);
    	}
    	DAL_Quotations.getAllQuotations(quotationIds);
        DAL_Quotations.getQuotationForWetuById(Quotations[0].Id);
    	DAL_Quotations.getAllQuotationsById(Quotations[0].Id);
    	DAL_Quotations.getAllQuotationsLineItems(strquotationIds);
    	DAL_Quotations.getAllQuotationsLineItems(setquotationIds);
    	DAL_Quotations.getAllQuotationsLineItemsByDate(quotationDates, setquotationIds);
    	DAL_Quotations.getAllbyOpportunityIds(opportunityIds);
    	DAL_Quotations.getAllServiceLineItems(quotationLineItemids);
        DAL_Quotations.getAllServiceLineItemsForPassengerInsurance(quotationLineItemids);
    	DAL_Quotations.getExistingServiceLineItemCount(new list<Date>(quotationDates)[0], quotationLineItemids[0]);
    	DAL_Quotations.getAllQuotationsLineItemsMaxEndDate(Quotations[0].Id);
        DAL_Quotations.getQuotationLineItemByMaxEndDates(setquotationIds,quotationDates);
        DAL_Quotations.getAllQuotationsLineItemsMaxEndDates(setquotationIds);
        DAL_Quotations.getQuotationLineItemByMaxEndDate(Quotations[0].Id,maxDate);
    	DAL_Quotations.getAllServiceLineItemsByIds(serviceLineItemIds);
        DAL_Quotations.getServiceChargeTypeForPassengerInsurance(serviceLineItemId,chargeTypes);
        DAL_Quotations.getQuotationExtraCostingServiceLineItem(quotationIds);
        DAL_Quotations.getPassengerForServiceLineItems(serviceLineItemId);
        DAL_Quotations.getOldConfirmedQuotationForSameOpportunity(opportunityIds,quotationIds);
        DAL_Quotations.getQuotationsFromOppId_DynamiCSOQL(opportunityId);
        DAL_Quotations.getQuotations_DynamiCSOQL(opportunityId);
    	Test.stopTest();
    }
    
    
    static testMethod void GetQuotationLineItemDateTest2() {
    	
    	Test.startTest();
    	setupInsertData2();
    	List<String> opportunityId = new List<String>();
        opportunityId.add(opportunitys[0].id);
        List<Quotations__c> quotations = DAL_Quotations.getQuotationsFromOppId_DynamiCSOQL(opportunityId);
        List<Quotations__c> quotationsList = DAL_Quotations.getQuotations_DynamiCSOQL(opportunityId);
    	Test.stopTest();
       
        
    }
}