Safari365 Prod/src/objects/Consultant_Target_Monthly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant_Gross_Profit_Target_Achieved__c</fullName>
        <label>Consultant Gross Profit Achieved</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant_Target_Yearly__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant GP Target (Annual)</label>
        <referenceTo>Consultant_Target_Yearly__c</referenceTo>
        <relationshipName>Consultant_Target_Monthly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gross_Profit_Target__c</fullName>
        <label>Consultant Gross Profit Target</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Individual Cons. GP Setup (Monthly)</label>
    <nameField>
        <displayFormat>CTM-{00000000}</displayFormat>
        <label>ID - Individ Cons. GP</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. GP Setup (Monthly)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Consultant_Target_Yearly__c.object
<CustomObject>
    <fields>
        <fullName>Total_Target_Achieved__c</fullName>
        <label>Total Annual Gross Profit Achieved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Target__c</fullName>
        <label>Total Annual Gross Profit Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Individual Cons. GP Rollup (Annual)</label>
    <nameField>
        <displayFormat>CTY-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. GP Rollup (Annual)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/HLPR_RollupTargetYearly.cls
public class HLPR_RollupTargetYearly {
    
    public static void rollUpFromMonthlyRecords(Map<Id, Consultant_Target_Monthly__c> mapMonthlyRecords) {
        List<Consultant_Target_Yearly__c> lstYearlyRecordsToBeUpdated = new List<Consultant_Target_Yearly__c>();
        Map<String,List<Consultant_Target_Monthly__c>> yearlyMonthlyMap = new Map<String,List<Consultant_Target_Monthly__c>>();
        for( Consultant_Target_Monthly__c monthlyRecord : mapMonthlyRecords.values()) {
            if(monthlyRecord.Consultant_Target_Yearly__c!=null) {
                if(yearlyMonthlyMap.containsKey(monthlyRecord.Consultant_Target_Yearly__c)) {
                    yearlyMonthlyMap.get(monthlyRecord.Consultant_Target_Yearly__c).add(monthlyRecord);
                } else {
                    yearlyMonthlyMap.put(monthlyRecord.Consultant_Target_Yearly__c, new List<Consultant_Target_Monthly__c>{monthlyRecord});
                }
            }
            
        }
        
        if(yearlyMonthlyMap!=null && !yearlyMonthlyMap.isEmpty()) {
            //query all monthlyMap records to setup fields at yearly level
            List<Consultant_Target_Yearly__c> lstYearlyRecordWithMonthlyChild = [Select Id, Total_Target__c, Total_Target_Achieved__c,
                                                                    (Select Id,Consultant_Target_Yearly__c, Gross_Profit_Target__c,Consultant_Gross_Profit_Target_Achieved__c 
                                                                    from Consultant_Target_Monthly__r) from Consultant_Target_Yearly__c where ID IN:yearlyMonthlyMap.keyset() ];
            if(lstYearlyRecordWithMonthlyChild!=null && !lstYearlyRecordWithMonthlyChild.isEmpty()) {
                for(Consultant_Target_Yearly__c yearlyRecord : lstYearlyRecordWithMonthlyChild) {
                    Consultant_Target_Yearly__c updateYearly = new Consultant_Target_Yearly__c(Id = yearlyRecord.Id);
                    //reset the target and target achieved
                    updateYearly.Total_Target__c = 0;
                    updateYearly.Total_Target_Achieved__c = 0;
                    //process through child records and rollup the values
                    for(Consultant_Target_Monthly__c monthlyRecord : yearlyRecord.Consultant_Target_Monthly__r) {
                        updateYearly.Total_Target__c += (monthlyRecord.Gross_Profit_Target__c==null?0: monthlyRecord.Gross_Profit_Target__c);
                        updateYearly.Total_Target_Achieved__c += (monthlyRecord.Consultant_Gross_Profit_Target_Achieved__c==null?0:monthlyRecord.Consultant_Gross_Profit_Target_Achieved__c);
                    }
                    //add to the updated list
                    lstYearlyRecordsToBeUpdated.add(updateYearly);
                }
                //check and update the parent records
                if(lstYearlyRecordsToBeUpdated!=null && !lstYearlyRecordsToBeUpdated.isEmpty()) {
                    update lstYearlyRecordsToBeUpdated;
                }
            }
        }
    }

}