Safari365 Prod/src/objects/Consultant_Target_Lead_Monthly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant_Leads_Target__c</fullName>
        <label>Number of Leads Required (Monthly)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Level</label>
        <referenceTo>Consultant_Target_Schema__c</referenceTo>
        <relationshipName>Consultant_Target_Lead_Monthly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consultant_Target_Lead_Achieved__c</fullName>
        <inlineHelpText>This will automatically populate based on leads assigned, no need to enter details here</inlineHelpText>
        <label>Number of Leads Received (Monthly)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Lead_Montly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Month</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. Lead Setup (Monthly)</label>
    <nameField>
        <displayFormat>CTLM-{00000000}</displayFormat>
        <label>ID - Indiv. Cons. Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. Lead Setup (Monthly)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Consultant_Target_Monthly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant_Gross_Profit_Target_Achieved__c</fullName>
        <label>Consultant Gross Profit Achieved</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant_Gross_Profit_Target__c</fullName>
        <label>Consultant Convsersion Ratio Target</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Consultant_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Level</label>
        <referenceTo>Consultant_Target_Schema__c</referenceTo>
        <relationshipName>Consultant_Target_Monthly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Monthly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Month</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. GP Setup (Monthly)</label>
    <nameField>
        <displayFormat>CTM-{00000000}</displayFormat>
        <label>ID - Individ Cons. GP</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. GP Setup (Monthly)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_ConsultantTargetMonthly.cls
public class DAL_ConsultantTargetMonthly{
    
    
    public static List<Consultant_Target_Monthly__c> getByConsultantIdAndYear(Set<Id> consultantId,
                                                                              Set<String> months,
                                                                              Set<String> years)
    {
    
      return [SELECT 
                    Id,
                    Consultant_Gross_Profit_Target_Achieved__c,
                    Consultant_Gross_Profit_Target__c,
                    Consultant_Role__c,
                    Consultant__c,
                    Month__c,
                    Year__c
               FROM 
                    Consultant_Target_Monthly__c
               WHERE
                    Consultant__c IN:consultantId
                AND 
                    Month__c IN: months
               AND 
                   Year__c IN:years];
    }
    
    
    public static List<Consultant_Target_Lead_Monthly__c> getLeadTargetByConsultantIdAndYear(Set<Id> consultantId,
                                                                              Set<String> months,
                                                                              Set<String> years)
    {
    
      return [SELECT 
                    Id,
                    Consultant_Leads_Target__c,
                    Consultant_Target_Lead_Achieved__c,
                    Consultant_Role__c,
                    Consultant__c,
                    Month__c,
                    Year__c
               FROM 
                    Consultant_Target_Lead_Monthly__c
               WHERE
                    Consultant__c IN:consultantId
                AND 
                    Month__c IN: months
               AND 
                   Year__c IN:years];
    }
    
    
    
    public static Map<String,Object> getCountConsultantTargetMonthly(Set<String> years, 
                                                               Set<Id> consultantIds)
    {
     
      AggregateResult[] groupedResults = [SELECT 
                                                Consultant__c,
                                                Count(Id)aver,
                                                Year__c
                                               FROM 
                                                     Consultant_Target_Monthly__c
                                              WHERE
                                                     Year__c IN: years
                                               AND 
                                                    Consultant__c IN: consultantIds
                                              group by Consultant__c,Year__c];
                              
         Map<String,Integer>  countOfActiveMonthTargetMap = new Map<String,Integer>();
         for(AggregateResult result:groupedResults )
        {
          String key = (String)result.get('Consultant__c')+(String)result.get('Year__c');
          countOfActiveMonthTargetMap.put(key,(result.get('aver')==null?0:(Integer)result.get('aver')));
        }  
    
    return countOfActiveMonthTargetMap;             
    }
    
    
    public static Map<String,Object> getSumOfAverageConsultantTargetMonthly(Set<String> years, 
                                                               Set<Id> consultantIds)
    {
     
      AggregateResult[] groupedResults = [SELECT 
                                                Consultant__c,
                                                Sum(Consultant_Gross_Profit_Target__c)aver,
                                                Year__c
                                               FROM 
                                                     Consultant_Target_Monthly__c
                                              WHERE
                                                     Year__c IN: years
                                               AND 
                                                    Consultant__c IN: consultantIds
                                              group by Consultant__c,Year__c];
                              
         Map<String,Decimal>  sumOfGPTargetMap = new Map<String,Decimal>();
         for(AggregateResult result:groupedResults )
        {
          String key = (String)result.get('Consultant__c')+(String)result.get('Year__c');
          sumOfGPTargetMap.put(key,(result.get('aver')==null?0:(Decimal)result.get('aver')));
        }  
    
    return sumOfGPTargetMap;             
    }
    
    
    public static Map<String,Object> getSumOfLeadMonthyTarget(Set<String> years, 
                                                               Set<Id> consultantIds)
    {
     
      AggregateResult[] groupedResults = [SELECT 
                                                Consultant__c,
                                                SUM(Consultant_Leads_Target__c)aver,
                                                Year__c
                                               FROM 
                                                     Consultant_Target_Lead_Monthly__c
                                              WHERE
                                                     Year__c IN: years
                                               AND 
                                                    Consultant__c IN: consultantIds
                                              group by Consultant__c,Year__c];
                              
         Map<String,Decimal>  monthlyTargetMap = new Map<String,Decimal>();
         for(AggregateResult opp:groupedResults )
        {
          String key = (String)opp.get('Consultant__c')+(String)opp.get('Year__c');
          monthlyTargetMap.put(key,(opp.get('aver')==null?0:(Decimal)opp.get('aver')));
        }  
    
    return monthlyTargetMap;             
    }
    
    
    public static Map<String,Object> getSumOfLeadMonthyTargetAchieved(Set<String> years, 
                                                               Set<Id> consultantIds)
    {
     
      AggregateResult[] groupedResults = [SELECT 
                                                Consultant__c,
                                                SUM(Consultant_Target_Lead_Achieved__c)aver,
                                                Year__c
                                               FROM 
                                                     Consultant_Target_Lead_Monthly__c
                                              WHERE
                                                     Year__c IN: years
                                               AND 
                                                    Consultant__c IN: consultantIds
                                              group by Consultant__c,Year__c];
                              
         Map<String,Decimal>  monthlyTargetMap = new Map<String,Decimal>();
         for(AggregateResult opp:groupedResults )
        {
          String key = (String)opp.get('Consultant__c')+(String)opp.get('Year__c');
          monthlyTargetMap.put(key,(opp.get('aver')==null?0:(Decimal)opp.get('aver')));
        }  
    
    return monthlyTargetMap;             
    }

}