Safari365 Prod/src/objects/Consultant_Target_Lead_Yearly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant_Target_Lead_Achieved__c</fullName>
        <label>Total Leads Received (Annual)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant_Total_Lead_Target__c</fullName>
        <label>Total Leads Required (Annual)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Lead_Yearly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CounsltantIdAndYearKey__c</fullName>
        <externalId>true</externalId>
        <label>CounsltantIdAndYearKey</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. Lead Rollup (Annual)</label>
    <nameField>
        <displayFormat>CTLY-{00000000}</displayFormat>
        <label>ID - Indiv Cons. Lead Rollup</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. Lead Rollup (Annual)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Consultant_Target_Monthly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant_Gross_Profit_Target_Achieved__c</fullName>
        <label>Consultant Gross Profit Achieved</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant_Target_Yearly__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant GP Target (Annual)</label>
        <referenceTo>Consultant_Target_Yearly__c</referenceTo>
        <relationshipName>Consultant_Target_Monthly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Monthly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gross_Profit_Target__c</fullName>
        <label>Consultant Gross Profit Target</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. GP Setup (Monthly)</label>
    <nameField>
        <displayFormat>CTM-{00000000}</displayFormat>
        <label>ID - Individ Cons. GP</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. GP Setup (Monthly)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Consultant_Target_Yearly__c.object
<CustomObject>
    <fields>
        <fullName>Average_of_Conversion_Ratio__c</fullName>
        <label>Target Conversion Ratio (Annual)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ConsultantIdKeyYear__c</fullName>
        <formula>CASESAFEID(Consultant__r.Id)+Text(Year__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ConsultantIdKeyYear</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Yearly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CounsltantIdAndYearKey__c</fullName>
        <externalId>true</externalId>
        <label>CounsltantIdAndYearKey</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Target_Achieved__c</fullName>
        <label>Total Annual Gross Profit Achieved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Target__c</fullName>
        <label>Total Annual Gross Profit Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. GP Rollup (Annual)</label>
    <nameField>
        <displayFormat>CTY-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. GP Rollup (Annual)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_ConsultantTargetYearly.cls
public class DAL_ConsultantTargetYearly
{
    
    public static List<Consultant_Target_Yearly__c> getByConsultantIdandYear(Set<Id> consultantId,
                                                                              Set<String> years)
    {
      return [SELECT
                     Id,
                     Consultant__c,
                     Name,
                     Year__c,
                     Total_Target__c,
                     Total_Target_Achieved__c,
                     Average_of_Conversion_Ratio__c ,
                     ConsultantIdKeyYear__c
               FROM
                     Consultant_Target_Yearly__c
               WHERE
                     Consultant__c IN: consultantId
               AND 
                      Year__c IN:years];   
    }

  
    public static List<Consultant_Target_Lead_Yearly__c> getLeadTargetByConsultantIdsAndYear(Set<Id> consultantId,
                                                                              Set<String> years)
    {
      return [SELECT
                     Id,
                     Consultant__c,
                     Name,
                     Year__c,
                     Consultant_Total_Lead_Target__c,
                     Consultant_Target_Lead_Achieved__c,
                    
                     CounsltantIdAndYearKey__c
               FROM
                     Consultant_Target_Lead_Yearly__c
               WHERE
                     Consultant__c IN: consultantId
               AND 
                     Year__c IN:years];   
    }


   public static List<Consultant_Target_Yearly__c> getByIds(Set<Id> ids)
   {
      return [SELECT
                     Id,
                     Consultant__c,
                     Name,
                     Year__c,
                     Total_Target__c,
                     Total_Target_Achieved__c,
                     Average_of_Conversion_Ratio__c,
                     ConsultantIdKeyYear__c
               FROM
                     Consultant_Target_Yearly__c
               WHERE
                     Id IN: ids];   
    }
    
    
   public static List<Consultant_Target_Yearly__c> getByYearSet(Set<Id> ids)
   {
      return [Select Id, 
                     Total_Target__c,
                     Total_Target_Achieved__c,
                     (SELECT 
                             Id,
                             Consultant_Target_Yearly__c,
                             Gross_Profit_Target__c,
                             Consultant_Gross_Profit_Target_Achieved__c 
                     FROM
                             Consultant_Target_Monthly__r) 
               FROM
                     Consultant_Target_Yearly__c
              WHERE 
                    ID IN:ids];   
    }
    
    
    public static List<Consultant_Target_Lead_Yearly__c> getLeadTargetByIds(Set<Id> ids)
   {
      return [SELECT
                     Id,
                     Consultant__c,
                     Name,
                     Year__c,
                     Consultant_Total_Lead_Target__c,
                     Consultant_Target_Lead_Achieved__c,
                     CounsltantIdAndYearKey__c
               FROM
                     Consultant_Target_Lead_Yearly__c
               WHERE
                     Id IN: ids];   
    }
    
    
    
}