Safari365 Prod/src/objects/Consultant_Target_Lead_Monthly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Lead_Montly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Month</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check Override if you want to Override the &quot;Number of Leads Required&quot; in any one particular month</inlineHelpText>
        <label>Override the Number of Leads Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. Lead Setup (Monthly)</label>
    <nameField>
        <displayFormat>CTLM-{00000000}</displayFormat>
        <label>ID - Indiv. Cons. Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. Lead Setup (Monthly)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Consultant_Target_Monthly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Monthly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Month</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If a consultant has just started with Safari365 (or is a trainee in forst 3 months) this allows for a staggered ( 25%, 50%, 75% etc) lead-in of the normal monthly target for the initial 3 months.</inlineHelpText>
        <label>Override Monthly GP Required (Lead-In)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. GP Setup (Monthly)</label>
    <nameField>
        <displayFormat>CTM-{00000000}</displayFormat>
        <label>ID - Individ Cons. GP</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. GP Setup (Monthly)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_DAL_ConsultantTargetMonthly.cls
@isTest
private class Test_DAL_ConsultantTargetMonthly{

   public static List<Consultant_Target_Monthly__c>  consultantTargetMonthlys = new List<Consultant_Target_Monthly__c>();
   public static List<Consultant_Target_Lead_Monthly__c>  consultantTargetLeadMonthlys = new List<Consultant_Target_Lead_Monthly__c>();
   static Integer recordCount = 1; 
   
   @testSetup 
   static void setupInsertData()
   {
       User us = TestDataFactory.createUser(true, '', true);
       System.runAs(us)
       {
            Map<String,Object> consultantTargetMonthlyMap = new Map<String,Object>();
            consultantTargetMonthlyMap.put('Month__c',String.valueof(system.today().month()));
            consultantTargetMonthlyMap.put('Year__c',String.valueof(system.today().year()));
            consultantTargetMonthlyMap.put('Consultant__c',us.id);
            consultantTargetMonthlyMap.put('Override__c',true);
            for(Integer i = 0 ; i <recordCount; i++)
            {
                consultantTargetMonthlys.add((Consultant_Target_Monthly__c) TestDataFactory.operationOnObjectRecord(null, 'Consultant_Target_Monthly__c', consultantTargetMonthlyMap));
            }
            DAL_BaseObject.InsertDBObjects(consultantTargetMonthlys);
            
            Map<String,Object> consultantTargetLeadMonthlyMap = new Map<String,Object>();
            consultantTargetLeadMonthlyMap.put('Month__c',String.valueof(system.today().month()));
            consultantTargetLeadMonthlyMap.put('Year__c',String.valueof(system.today().year()));
            consultantTargetLeadMonthlyMap.put('Consultant__c',us.id);
            consultantTargetLeadMonthlyMap.put('Override__c',true);
            for(Integer i = 0 ; i <recordCount; i++)
            {
                consultantTargetLeadMonthlys.add((Consultant_Target_Lead_Monthly__c) TestDataFactory.operationOnObjectRecord(null, 'Consultant_Target_Lead_Monthly__c', consultantTargetLeadMonthlyMap));
            }
            DAL_BaseObject.InsertDBObjects(consultantTargetLeadMonthlys);
            
       }
    }
    
    static testMethod void getByConsultantIdAndYearTest() 
    {
      Test.startTest();
      Set<Id> consultantId = new Set<Id>();
      Set<String> months = new Set<String>();
      Set<String> years = new Set<String>();
      for(Consultant_Target_Monthly__c ac: consultantTargetMonthlys)
      {
        consultantId.add(ac.Consultant__c);
        months.add(ac.Month__c);
        years.add(ac.Year__c);
        
      }
      DAL_ConsultantTargetMonthly.getByConsultantIdAndYear(consultantId,months,years);
      DAL_ConsultantTargetMonthly.getSumOfLeadMonthyTarget(years,consultantId);
      DAL_ConsultantTargetMonthly.getSumOfLeadMonthyTargetAchieved(years,consultantId);
      DAL_ConsultantTargetMonthly.getCountConsultantTargetMonthly(years,consultantId);
      DAL_ConsultantTargetMonthly.getSumOfAverageConsultantTargetMonthly(years,consultantId);
      Test.stopTest();
    }

}