Safari365 Prod/src/objects/Consultant_Target_Monthly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant_Gross_Profit_Target_Achieved__c</fullName>
        <label>Consultant Gross Profit Achieved</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant_Gross_Profit_Target__c</fullName>
        <label>Consultant Convsersion Ratio Target</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Consultant_Target_Yearly__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant GP Target (Annual)</label>
        <referenceTo>Consultant_Target_Yearly__c</referenceTo>
        <relationshipName>Consultant_Target_Monthly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Monthly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gross_Profit_Target__c</fullName>
        <label>Consultant Gross Profit Target</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Month</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If a consultant has just started with Safari365 (or is a trainee in forst 3 months) this allows for a staggered ( 25%, 50%, 75% etc) lead-in of the normal monthly target for the initial 3 months.</inlineHelpText>
        <label>Override Monthly GP Required (Lead-In)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. GP Setup (Monthly)</label>
    <nameField>
        <displayFormat>CTM-{00000000}</displayFormat>
        <label>ID - Individ Cons. GP</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. GP Setup (Monthly)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Consultant_Target_Yearly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Yearly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. GP Rollup (Annual)</label>
    <nameField>
        <displayFormat>CTY-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. GP Rollup (Annual)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_TH_ConsultantTargetMonthly.cls
@isTest
private class Test_TH_ConsultantTargetMonthly{
  
  public static Consultant_Target_Yearly__c consultantTargetYearlys = new Consultant_Target_Yearly__c();    
  public static List<Consultant_Target_Monthly__c>  consultantTargetMonthlys = new List<Consultant_Target_Monthly__c>();
   static Integer recordCount = 1; 
   public static Integer count =5;
   
   @testSetup 
   static void setupInsertData()
   {
       User us = TestDataFactory.createUser(true, '', true);
       System.runAs(us)
       {
            consultantTargetYearlys = (Consultant_Target_Yearly__c) TestDataFactory.operationOnObjectRecord(null,'Consultant_Target_Yearly__c', null);
            insert consultantTargetYearlys;
            Map<String,Object> consultantTargetMonthlyMap = new Map<String,Object>();
            consultantTargetMonthlyMap.put('Month__c',String.valueof(system.today().month()));
            consultantTargetMonthlyMap.put('Year__c',String.valueof(system.today().year()));
            consultantTargetMonthlyMap.put('Consultant__c',us.id);
            consultantTargetMonthlyMap.put('Override__c',true);
            consultantTargetMonthlyMap.put('Gross_Profit_Target__c',1000);
            consultantTargetMonthlyMap.put('Consultant_Gross_Profit_Target__c',10);
            consultantTargetMonthlyMap.put('Consultant_Gross_Profit_Target__c',10);
            consultantTargetMonthlyMap.put('Consultant_Target_Yearly__c', consultantTargetYearlys.Id);
            for(Integer i = 0 ; i <recordCount; i++)
            {
                consultantTargetMonthlys.add((Consultant_Target_Monthly__c) TestDataFactory.operationOnObjectRecord(null, 'Consultant_Target_Monthly__c', consultantTargetMonthlyMap));
            }
            system.debug('consultantTargetMonthlys:::'+consultantTargetMonthlys);
            DAL_BaseObject.InsertDBObjects(consultantTargetMonthlys);
            
       }
    }
    
    static testMethod void updateCTMTest() 
    {
      setupInsertData();
      Test.startTest();
      List<Consultant_Target_Monthly__c> ctms = new List<Consultant_Target_Monthly__c>();
      for(Consultant_Target_Monthly__c ac: consultantTargetMonthlys)
      {
        ac.Consultant_Gross_Profit_Target_Achieved__c= 100;
        ctms.add(ac);
        
      }
     update ctms;
      
     Test.stopTest();
    }
  
   static testMethod void deleteCTMTest() 
    {
      setupInsertData();
      Test.startTest();
      List<Consultant_Target_Monthly__c> ctms = new List<Consultant_Target_Monthly__c>();
      for(Consultant_Target_Monthly__c ac: consultantTargetMonthlys)
      {
        ac.Consultant_Gross_Profit_Target_Achieved__c= 100;
        ctms.add(ac);
        
      }
      update ctms;
      delete ctms;
      Test.stopTest();
      
    }
}