Safari365 Prod/src/objects/Consultant_Target_Lead_Monthly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant_Leads_Target__c</fullName>
        <label>Number of Leads Required (Monthly)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Level</label>
        <referenceTo>Consultant_Target_Schema__c</referenceTo>
        <relationshipName>Consultant_Target_Lead_Monthly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consultant_Target_Lead_Achieved__c</fullName>
        <inlineHelpText>This will automatically populate based on leads assigned, no need to enter details here</inlineHelpText>
        <label>Number of Leads Received (Monthly)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Lead_Montly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Month</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. Lead Setup (Monthly)</label>
    <nameField>
        <displayFormat>CTLM-{00000000}</displayFormat>
        <label>ID - Indiv. Cons. Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. Lead Setup (Monthly)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/BATCH_CalculateTotalLeadTarget.cls
global class BATCH_CalculateTotalLeadTarget implements Database.Batchable<sObject>,Schedulable{
    
    
    global Database.QueryLocator start(Database.BatchableContext BC){        
        return Database.getQueryLocator([ 
                                            SELECT 
                                            Id,
                                            Consultant_Leads_Target__c,
                                            Consultant_Target_Lead_Achieved__c,
                                            Consultant_Role__c,
                                            Consultant__c,
                                            Month__c,
                                            Year__c
                                       FROM 
                                            Consultant_Target_Lead_Monthly__c]);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        UpdateYearlyLeadTargetService.updateYearlyTarget((List<Consultant_Target_Lead_Monthly__c>)scope);               
    }

    global void finish(Database.BatchableContext BC){
       
    }
    
    global void execute(SchedulableContext sc)
    {
        BATCH_CalculateTotalLeadTarget calTarget = new BATCH_CalculateTotalLeadTarget();
        database.executebatch(calTarget, 100 );
    }
    
}