Safari365 Prod/src/objects/Consultant_Target_Lead_Monthly__c.object
<CustomObject>
    <fields>
        <fullName>Consultant_Leads_Target__c</fullName>
        <label>Number of Leads Required (Monthly)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Consultant_Target_Lead_Montly</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Month</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check Override if you want to Override the &quot;Number of Leads Required&quot; in any one particular month</inlineHelpText>
        <label>Override the Number of Leads Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <label>Individual Cons. Lead Setup (Monthly)</label>
    <nameField>
        <displayFormat>CTLM-{00000000}</displayFormat>
        <label>ID - Indiv. Cons. Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Cons. Lead Setup (Monthly)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_UpdateYearlyLeadTargetService.cls
@isTest
private class Test_UpdateYearlyLeadTargetService
{

   public static List<Consultant_Target_Lead_Monthly__c>  consultantTargetLeadMonthlys = new List<Consultant_Target_Lead_Monthly__c>();
   static Integer recordCount = 1; 
   
   @testSetup 
   static void setupInsertData()
   {
       User us = TestDataFactory.createUser(true, '', true);
       System.runAs(us)
       {
            Map<String,Object> consultantTargetLeadMonthlyMap = new Map<String,Object>();
            consultantTargetLeadMonthlyMap.put('Month__c',String.valueof(system.today().month()));
            consultantTargetLeadMonthlyMap.put('Year__c',String.valueof(system.today().year()));
            consultantTargetLeadMonthlyMap.put('Consultant__c',us.id);
            consultantTargetLeadMonthlyMap.put('Consultant_Leads_Target__c',100);
            consultantTargetLeadMonthlyMap.put('Override__c',true);
            for(Integer i = 0 ; i <recordCount; i++)
            {
                consultantTargetLeadMonthlys.add((Consultant_Target_Lead_Monthly__c) TestDataFactory.operationOnObjectRecord(null, 'Consultant_Target_Lead_Monthly__c', consultantTargetLeadMonthlyMap));
            }
            DAL_BaseObject.InsertDBObjects(consultantTargetLeadMonthlys);
            
       }
    }

    static testMethod void updateYearlyTargetTest() {
      Test.startTest();
      setupInsertData();
      UpdateYearlyLeadTargetService.updateYearlyTarget(consultantTargetLeadMonthlys);
      Test.stopTest();
        
    }
}