Safari365 Prod/src/objects/CRM__c.object
<CustomObject>
    <fields>
        <fullName>SOD_ID__c</fullName>
        <label>SOD ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CRM</label>
    <nameField>
        <displayFormat>CRM-{00000000}</displayFormat>
        <label>CRM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/SOD__c.object
<CustomObject>
    <description>Supplier Overall Policy</description>
    <fields>
        <fullName>CRM_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRM_Lookup</label>
        <referenceTo>CRM__c</referenceTo>
        <relationshipLabel>SODs</relationshipLabel>
        <relationshipName>SODs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOD_ID__c</fullName>
        <externalId>true</externalId>
        <label>SOD_ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SOD</label>
    <nameField>
        <displayFormat>SOD-{00000000}</displayFormat>
        <label>SOD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SODs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_SODTriggerHandler.cls
@isTest
private class Test_SODTriggerHandler {
    
    public static List<CRM__c>  crms = new List<CRM__c>();
    public static List<SOD__c>  sods= new List<SOD__c>();
    public static Integer count =1;
    
    static void setupInsertData(){
        
        for(Integer i = 0 ; i <count; i++)
        {
            crms.add((CRM__c) TestDataFactory.operationOnObjectRecord(null, 'CRM__c', null));
        }
        insert crms;
        
        Map<String,Object> keyValueMap = new Map<String,Object>();
        for(CRM__c crm:crms)
        {
            keyValueMap.put('SOD_ID__c', crm.SOD_ID__c);
        }
    
        for(Integer i = 0 ; i <count; i++)
        sods.add((SOD__c) TestDataFactory.operationOnObjectRecord(null, DAL_SOD.OBJECT_NAME, keyValueMap));
        
    }
    
    static void setupUpdateData(){
        setupInsertData();
        insert sods;
    }

   @isTest  
  static void testBeforeInsert() {
      
      setupInsertData();
      
      Test.startTest();
      insert sods;
      List<SOD__c> sodsList=[select Id,CRM_Lookup__c,SOD_ID__c from SOD__c where SOD_ID__c=: crms[0].SOD_ID__c];
      system.assert(sodsList[0].CRM_Lookup__c <> null);
      Test.stopTest();
      
  }
  
   @isTest  
  static void testBeforeUpdate() {
      
      Trigger_PAD.deactivateTrigger('SODTriggerHandler');
      setupUpdateData();
      Trigger_PAD.activateTrigger('SODTriggerHandler');
      
      Test.startTest();
      
      update sods;
      List<SOD__c> sodsList=[select Id,CRM_Lookup__c,SOD_ID__c from SOD__c where SOD_ID__c=: crms[0].SOD_ID__c];
      system.assert(sodsList[0].CRM_Lookup__c <> null);
      
      Test.stopTest();
      
  }
}