Safari365 Prod/src/objects/CRM__c.object
<CustomObject>
    <fields>
        <fullName>CODE__c</fullName>
        <externalId>true</externalId>
        <label>CODE</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DEFAULT_CURRENCY__c</fullName>
        <label>DEFAULT CURRENCY</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>CRM</label>
    <nameField>
        <displayFormat>CRM-{00000000}</displayFormat>
        <label>CRM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Crm_Code__c</fullName>
        <label>T&amp;C&apos;s</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Service Line Item</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceLine Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_CRM.cls
public class DAL_CRM {
   public static final String OBJECT_NAME = CRM__c.SObjectType.getDescribe().getLocalName();
    
    public static Map<String,CRM__c> getCrmFromServiceLineItems(List<ServiceLineItem__c> serviceLineItems)
    {
         Set<String> codes = new Set<String>();
         for(ServiceLineItem__c sli: serviceLineItems)    
         {
            codes.add(sli.Crm_Code__c);
         }  
        List<CRM__c> crms=
                  [SELECT
                         Id,
                         Code__c
                    FROM 
                         CRM__c 
                    WHERE 
                         Code__c IN:codes];
       Map<String, CRM__c> codeCrmMap = new Map<String, CRM__c>();
       for(CRM__c op:crms)
       {
        codeCrmMap.put(op.Code__c,op);
       }  
       return  codeCrmMap;  
    }
    
    
    public static List<CRM__c> getById(String id)
    {
        return [SELECT
                         Id,
                         Code__c,
                         DEFAULT_CURRENCY__c
                    FROM 
                         CRM__c 
                    WHERE 
                         Id =:id];
    }
    
     
}