Safari365 Prod/src/objects/CRM__c.object
<CustomObject>
    <label>CRM</label>
    <nameField>
        <displayFormat>CRM-{00000000}</displayFormat>
        <label>CRM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/NTS__c.object
<CustomObject>
    <fields>
        <fullName>CATEGORY__c</fullName>
        <label>CATEGORY</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRM Lookup</label>
        <referenceTo>CRM__c</referenceTo>
        <relationshipLabel>NTSs</relationshipLabel>
        <relationshipName>NTSs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MESSAGE_TEXT__c</fullName>
        <label>MESSAGE_TEXT</label>
        <length>100000</length>
        <type>Html</type>
    </fields>
    <label>NTS</label>
    <nameField>
        <displayFormat>NTS-{0000000}</displayFormat>
        <label>NTS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NTSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_NTS.cls
public class DAL_NTS {
    
    public static final String OBJECT_NAME = NTS__c.SObjectType.getDescribe().getLocalName();
    
    public static Map<String,NTS__c> GetNtsForServiceLineItems(List<CRM__c> crms)
    {
        Set<Id> crmLookupCodes = new Set<Id>();
        for(CRM__c crm:crms)
        {
            crmLookupCodes.add(crm.Id);
        }
        List<NTS__c> nts = [SELECT
                                    Id,
                                    CATEGORY__c,
                                    MESSAGE_TEXT__c,
                                    CRM_Lookup__c
                              FROM 
                                    NTS__c
                              WHERE
                                   CRM_Lookup__c IN:crmLookupCodes
                                AND 
                                  CATEGORY__c =:'WET'];
       Map<String, NTS__c> codeNtsMap = new Map<String, NTS__c>();
       for(NTS__c nt:nts)
       {
        codeNtsMap.put(nt.CRM_Lookup__c,nt );
       }  
       return  codeNtsMap;         
    }
}