Safari365 Prod/src/objects/CTT__c.object
<CustomObject>
    <fields>
        <fullName>CODE__c</fullName>
        <externalId>true</externalId>
        <label>CODE</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>CTT</label>
    <nameField>
        <displayFormat>CTT-{00000000}</displayFormat>
        <label>CTT Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTTs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Opt__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>OPT</label>
    <nameField>
        <displayFormat>OPT-{0000000}</displayFormat>
        <label>OPT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/PBK__c.object
<CustomObject>
    <fields>
        <fullName>CONTACTTYPE__c</fullName>
        <label>CONTACTTYPE</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTT_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CTT</label>
        <referenceTo>CTT__c</referenceTo>
        <relationshipName>PBKs_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Contact Detail (PBK)</label>
    <nameField>
        <displayFormat>PBK-{00000000}</displayFormat>
        <label>PBK Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Contact Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_PBKTriggerHandler.cls
@isTest
private class  Test_PBKTriggerHandler {
	
	public static List<PBK__c>  pbksCTT = new List<PBK__c>();
    public static List<CTT__c>  ctts= new List<CTT__c>();
    public static List<Opt__c>  crmopts = new List<Opt__c>();
    
    public static Integer count = 1;
    
    static void setupPBKCTTInsertData(){
        
        for(Integer i = 0 ; i <count; i++)
        {
            ctts.add((CTT__c) TestDataFactory.operationOnObjectRecord(null, 'CTT__c', null));
        }
        insert ctts;
        
        Map<String,Object> db4keyValueMap = new Map<String,Object>();
        for(CTT__c db4:ctts)
        {
            db4keyValueMap.put('CONTACTTYPE__c', db4.CODE__c);
        }
    
        for(Integer i = 0 ; i <count; i++)
        pbksCTT.add((PBK__c) TestDataFactory.operationOnObjectRecord(null, 'PBK__c', db4keyValueMap));
        
    }
    static void setupPBKCTTUpdateData(){
        setupPBKCTTInsertData();
        insert pbksCTT;
    }
    
    @isTest  
  static void testBeforeInsertPBKLookUp() {
      
      setupPBKCTTInsertData();
      insert pbksCTT;
      List<PBK__c> optList=[select Id,CTT_Lookup__c from PBK__c where CONTACTTYPE__c=: ctts[0].CODE__c];
      Test.startTest();
      System.assert(optList[0].CTT_Lookup__c <> null);
      
      Test.stopTest();
      
  }
  
   @isTest  
  static void testBeforeUpdate() {
      
      Trigger_PAD.deactivateTrigger('PBKTriggerHandler');
      setupPBKCTTUpdateData();
      Trigger_PAD.activateTrigger('PBKTriggerHandler');
      
      Test.startTest();
      
      update pbksCTT;
      
      
      Test.stopTest();
      
  }
    
}