Safari365 Prod/src/objects/ExchangeRateColumnMapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Base_Currency__c</fullName>
        <label>Base Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>ZAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Markup_Value__c</fullName>
        <label>Markup Value</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>ExchangeRateColumnMapping</label>
    <pluralLabel>ExchangeRateColumnMappings</pluralLabel>
</CustomObject>

Safari365 Prod/src/objects/ExchangeRates__c.object
<CustomObject>
    <fields>
        <fullName>AED__c</fullName>
        <label>AED</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ANG__c</fullName>
        <label>ANG</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ARS__c</fullName>
        <label>ARS</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRL_Credit_Card_Markup__c</fullName>
        <formula>$CustomMetadata.Credit_Card_Markup__mdt.Credit_Card_Markup_BRL.Markup_value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRL Credit Card Markup</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRL__c</fullName>
        <label>BRL</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseCurrency__c</fullName>
        <label>BaseCurrency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <label>CAD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CHF__c</fullName>
        <label>CHF</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLP__c</fullName>
        <label>CLP</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CNY__c</fullName>
        <label>CNY</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DKK__c</fullName>
        <label>DKK</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExchangeRateDate__c</fullName>
        <label>ExchangeRateDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HKD__c</fullName>
        <label>HKD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ILS__c</fullName>
        <label>ILS</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MYR__c</fullName>
        <label>MYR</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NZD__c</fullName>
        <label>NZD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PEN__c</fullName>
        <label>PEN</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUB__c</fullName>
        <label>RUB</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SEK__c</fullName>
        <label>SEK</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGD__c</fullName>
        <label>SGD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>USD__c</fullName>
        <label>USD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZAR__c</fullName>
        <label>ZAR</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>ExchangeRate</label>
    <nameField>
        <displayFormat>ER-{000000000}</displayFormat>
        <label>ExchangeRates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExchangeRates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_ExchangeRate.cls
public class DAL_ExchangeRate {
   
    public static final String OBJECT_NAME = ExchangeRates__c.SObjectType.getDescribe().getLocalName();
    
    public static List<ExchangeRates__c> getCurrencyByBaseCurrency(String baseCurrency)
    {
      return [SELECT        
                     AED__c,
                     ANG__c,
                     ARS__c,
                     AUD__c,
                     BaseCurrency__c,
                     BRL__c,
                     CAD__c,
                     CHF__c,
                     CLP__c,
                     CNY__c,
                     DKK__c,
                     EUR__c,
                     ExchangeRateDate__c,
                     GBP__c,
                     HKD__c,
                     Id,
                     ILS__c,
                     MYR__c,
                     Name,
                     NZD__c,
                     PEN__c,
                     RUB__c,
                     SEK__c,
                     SGD__c,
                     USD__c,
                     ZAR__c,
                     BRL_Credit_Card_Markup__c
                FROM
                     ExchangeRates__c
                WHERE 
                     BaseCurrency__c =:baseCurrency
             ORDER by CreatedDate DESC limit 1];

    }
    
    public static List<ExchangeRates__c> getCurrencyAllByBaseCurrency()
    {
      return [SELECT        
                     AED__c,
                     ANG__c,
                     ARS__c,
                     AUD__c,
                     BaseCurrency__c,
                     BRL__c,
                     CAD__c,
                     CHF__c,
                     CLP__c,
                     CNY__c,
                     DKK__c,
                     EUR__c,
                     ExchangeRateDate__c,
                     GBP__c,
                     HKD__c,
                     Id,
                     ILS__c,
                     MYR__c,
                     Name,
                     NZD__c,
                     PEN__c,
                     RUB__c,
                     SEK__c,
                     SGD__c,
                     USD__c,
                     ZAR__c 
                FROM
                     ExchangeRates__c
                  WHERE 
                    BaseCurrency__c IN ('USD','EUR','ZAR') 
             ORDER by CreatedDate DESC limit 3];

    }
 
    public static  List<ExchangeRateColumnMapping__mdt> getExchangeRateMapping()
    {
         return [SELECT 
                        Id,
                        Label,
                        Markup_Value__c,
                        Base_Currency__c 
                    FROM
                         ExchangeRateColumnMapping__mdt ];
    }
}