Safari365 Prod/src/objects/ExchangeRateColumnMapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Markup_Value__c</fullName>
        <label>Markup Value</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>ExchangeRateColumnMapping</label>
    <pluralLabel>ExchangeRateColumnMappings</pluralLabel>
</CustomObject>

Safari365 Prod/src/objects/ExchangeRates__c.object
<CustomObject>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BaseCurrency__c</fullName>
        <label>BaseCurrency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>USD__c</fullName>
        <label>USD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>ExchangeRate</label>
    <nameField>
        <displayFormat>ER-{000000000}</displayFormat>
        <label>ExchangeRates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExchangeRates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>CC_ROE_for_EUR_in_AUD__c</fullName>
        <label>CC ROE for EUR to AUD</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_ROE_for_EUR_in_EUR__c</fullName>
        <label>CC ROE for EUR to EUR</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_ROE_for_EUR_in_GPB__c</fullName>
        <label>CC ROE for EUR to GPB</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_ROE_for_EUR_in_USD__c</fullName>
        <label>CC ROE for EUR to USD</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_ROE_for_USD_in_AUD__c</fullName>
        <label>CC ROE for USD to AUD</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_ROE_for_USD_in_EUR__c</fullName>
        <label>CC ROE for USD to EUR</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_ROE_for_USD_in_GPB__c</fullName>
        <label>CC ROE for USD to GPB</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_ROE_for_USD_in_USD__c</fullName>
        <label>CC ROE for USD to USD</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_ROE_for_ZAR_in_AUD__c</fullName>
        <label>CC ROE for ZAR to AUD</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_ROE_for_ZAR_in_EUR__c</fullName>
        <label>CC ROE for ZAR to EUR</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_ROE_for_ZAR_in_GPB__c</fullName>
        <label>CC ROE for ZAR to GPB</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_ROE_for_ZAR_in_USD__c</fullName>
        <label>CC ROE for ZAR to USD</label>
        <precision>15</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client_Fund_Recieved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This box is checked when any payment has been received from the client. If a payment has already been received this boxed must been unchecked and checked again. This checkbox being true enables consultants to move to &apos;Confirmed&apos;</inlineHelpText>
        <label>Deposit Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exchange_Values_Override_By_Finance__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This checkbox disables the FX rate lookup. Only to be used by FX Manager when FX rates must be manually overridden.</inlineHelpText>
        <label>Disable FX Rate Refresh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_Exposure__c</fullName>
        <label>Quote Exposure</label>
        <summarizedField>Exposure_ROE__c.Quote_Exposure__c</summarizedField>
        <summaryForeignKey>Exposure_ROE__c.Quotation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Update_CC_ROE_Fields_Date__c</fullName>
        <description>The date at which the exchange rate updated</description>
        <label>Update CC ROE Fields Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <inlineHelpText>The date when the quoted exchange rate for this quote will expire. Rate will be valid until midnight of this date South African time.</inlineHelpText>
        <label>Quotation FX Rate Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/QuotationCCROEFieldsUpdateController.cls
global with sharing class QuotationCCROEFieldsUpdateController{
    
    webservice static String updateAllCCROIFieldsClassic(String quotationId)
    {
      String response = updateAllCCROIFields(quotationId);
      return response;
    }
    
     @AuraEnabled
    public static String updateManuallyCCROIFields(String quotationId)
    {
        String response='success';
        List<Quotations__c> quotations= DAL_Quotations.getAllQuotationsById(quotationId);
        Quotations__c quotation = quotations[0];
        updateROE(quotation);
        BaseTriggerHandler.bypass('TH_Quotations');
        quotation.Update_CC_ROE_Fields_Date__c = system.today();
        update quotation;
        BaseTriggerHandler.clearBypass('TH_Quotations');
        
        return response;
    }

    @AuraEnabled
    public static String updateAllCCROIFields(String quotationId)
    {
        String response='success';
        List<Quotations__c> quotations= DAL_Quotations.getAllQuotationsById(quotationId);
        
        Quotations__c quotation = quotations[0];
        
        Boolean flag = false;
        if(quotation.Client_Fund_Recieved__c == true 
            || quotation.Valid_Until__c >= system.today())
        {
            flag  = true;
            response ='success';
            return response;
        }
        else if(!flag 
                && quotation.Exchange_Values_Override_By_Finance__c == true)
        {
            flag  = true;
            system.debug('condition3>'+quotation.Exchange_Values_Override_By_Finance__c);
            response ='Itinerary Document not created as FX Rate Refresh has been disabled. If needed, please contact FX manager to create';
            return response;
        }
        else if(!flag
                 && quotation.Quote_Exposure__c > 0
                 && quotation.Valid_Until__c < system.today() 
                 && Integer.valueof(Label.Maximum_Quote_Exposure_Days) > ((system.today()).daysBetween(quotation.LastModifiedDate.date()))
                 )
        {
            flag  = true;
            quotation.Valid_Until__c = system.today().addDays(Integer.valueof(Label.Valid_Until_Days));
            BaseTriggerHandler.bypass('TH_Quotations');
            update quotation;
            BaseTriggerHandler.clearBypass('TH_Quotations');
            response ='success';
            return response;
            
        }
        
        else if(!flag)
        {
            
            try{
                updateROE(quotation);
                BaseTriggerHandler.bypass('TH_Quotations');
                quotation.Valid_Until__c = system.today().addDays(Integer.valueof(Label.Valid_Until_Days));
                update quotation;
                BaseTriggerHandler.clearBypass('TH_Quotations');
                response ='success';
            }catch(Exception e){
                
                response = e.getMessage();
            }
        }
        else
        {
            response ='FailureFXRateLocked';
        }
        return response;
    }
    
    
    private  static void updateROE(Quotations__c quotation)
    {
        List<ExchangeRateColumnMapping__mdt> exchangeRateColumnMapping = DAL_ExchangeRate.getExchangeRateMapping();                                 
        List<ExchangeRates__c> exchangeRates= DAL_ExchangeRate.getCurrencyAllByBaseCurrency();
            
            if(exchangeRateColumnMapping != null
                 && exchangeRates.size()>0)
            {
                Decimal clientExchangeRateUSD;
                Decimal clientExchangeRateAUD;
                Decimal clientExchangeRateGBP;
                Decimal clientExchangeRateEUR;
                 for(ExchangeRates__c exchangeRate:exchangeRates)
                 {
                     if(exchangeRate.BaseCurrency__c =='USD')
                     {
                        for(ExchangeRateColumnMapping__mdt exRatColMap:exchangeRateColumnMapping)
                        {
                          if(exRatColMap.Label=='USD:USD')
                          {
                             clientExchangeRateUSD = exchangeRate.USD__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                          else if(exRatColMap.Label=='USD:AUD')
                          {
                             clientExchangeRateAUD = exchangeRate.AUD__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                          else if(exRatColMap.Label=='USD:GBP')
                          {
                             clientExchangeRateGBP = exchangeRate.GBP__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                          else if(exRatColMap.Label=='USD:EUR')
                          {
                             clientExchangeRateEUR = exchangeRate.EUR__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                        }
                        
                        quotation.CC_ROE_for_USD_in_USD__c = clientExchangeRateUSD;
                        quotation.CC_ROE_for_USD_in_AUD__c = clientExchangeRateAUD;
                        quotation.CC_ROE_for_USD_in_GPB__c = clientExchangeRateGBP;
                        quotation.CC_ROE_for_USD_in_EUR__c = clientExchangeRateEUR;
                        
                     }
                     
                     if(exchangeRate.BaseCurrency__c =='EUR')
                     {
                        for(ExchangeRateColumnMapping__mdt exRatColMap:exchangeRateColumnMapping)
                        {
                          if(exRatColMap.Label=='EUR:USD')
                          {
                                clientExchangeRateUSD = exchangeRate.USD__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                          else if(exRatColMap.Label=='EUR:AUD')
                          {
                            clientExchangeRateAUD = exchangeRate.AUD__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                          else if(exRatColMap.Label=='EUR:GBP')
                          {
                            clientExchangeRateGBP = exchangeRate.GBP__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                          else if(exRatColMap.Label=='EUR:EUR')
                          {
                            clientExchangeRateEUR = exchangeRate.EUR__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                        }
                        quotation.CC_ROE_for_EUR_in_USD__c = clientExchangeRateUSD;
                        quotation.CC_ROE_for_EUR_in_AUD__c = clientExchangeRateAUD;
                        quotation.CC_ROE_for_EUR_in_GPB__c = clientExchangeRateGBP;
                        quotation.CC_ROE_for_EUR_in_EUR__c = clientExchangeRateEUR;
                        
                     }
                     
                     if(exchangeRate.BaseCurrency__c =='ZAR')
                     {
                         for(ExchangeRateColumnMapping__mdt exRatColMap:exchangeRateColumnMapping)
                        {
                          if(exRatColMap.Label=='ZAR:USD')
                          {
                             clientExchangeRateUSD = exchangeRate.USD__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                          else if(exRatColMap.Label=='ZAR:AUD')
                          {
                            clientExchangeRateAUD = exchangeRate.AUD__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                          else if(exRatColMap.Label=='ZAR:GBP')
                          {
                            clientExchangeRateGBP = exchangeRate.GBP__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                          else if(exRatColMap.Label=='ZAR:EUR')
                          {
                            clientExchangeRateEUR = exchangeRate.EUR__c*((100+exRatColMap.Markup_Value__c)/100);
                          }
                        }
    
                        quotation.CC_ROE_for_ZAR_in_USD__c = clientExchangeRateUSD;
                        quotation.CC_ROE_for_ZAR_in_AUD__c = clientExchangeRateAUD;
                        quotation.CC_ROE_for_ZAR_in_GPB__c = clientExchangeRateGBP;
                        quotation.CC_ROE_for_ZAR_in_EUR__c = clientExchangeRateEUR;
                     }
                 }  
            }
    }
    
    @AuraEnabled
    public static String createOrNotQuotationItineraryDocOnGDLtng(String quotationId)
    {
        return QuotationItineraryDocOnGD.createOrNotQuotationItineraryDocOnGDLtng(quotationId);
    }
}