Safari365 Prod/src/objects/Exposure_ROE__c.object
<CustomObject>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipName>Quotation_ROE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Exposure ROE</label>
    <nameField>
        <displayFormat>ROE-{00000000}</displayFormat>
        <label>Exposure ROE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exposure ROE</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_ExposureRoe.cls
public with sharing class DAL_ExposureRoe {
    
    public static Map<Id, Exposure_ROE__c> getByQuotationId(Set<Id> quotationIds)
    {
        Map<Id, Exposure_ROE__c> quotationIdKeyExposureROEValue = new Map<Id, Exposure_ROE__c>();
        List<Exposure_ROE__c> Exposure_ROEs = [SELECT 
                                                      Id,
                                                      Quotation__c
                                                  FROM 
                                                      Exposure_ROE__c
                                                  WHERE
                                                        Quotation__c IN:quotationIds ];
        for(Exposure_ROE__c eR: Exposure_ROEs)
        {
            quotationIdKeyExposureROEValue.put(er.Quotation__c,eR);
        }
        
        return  quotationIdKeyExposureROEValue;                                             
    }
    
}