Safari365 Prod/src/objects/Exposure_ROE__c.object
<CustomObject>
    <fields>
        <fullName>EXP_Quotation_Sale_Total_in_Selected_CC__c</fullName>
        <formula>EXP_Subtotal_for_EUR_in_CC__c +  EXP_Subtotal_for_USD_in_CC__c + EXP_Subtotal_for_ZAR_in_CC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EXP Quotation Sale Total in Selected CC</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quotation_Sale_Total_in_Selected_CC__c</fullName>
        <formula>Quotation__r.Quotation_Sale_Total_in_Selected_CC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quotation Sale Total in Selected CC</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipName>Quotation_ROE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quote_Exposure__c</fullName>
        <label>Exposure %</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Exposure ROE</label>
    <nameField>
        <displayFormat>ROE-{00000000}</displayFormat>
        <label>Exposure ROE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exposure ROE</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Approval_from_FX_Treasury_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval from FX Treasury Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quotation_Sale_Total_in_Selected_CC__c</fullName>
        <description>This displays the quote total in the selected client currency</description>
        <formula>IF( Currency__c == &apos;AUD&apos; , Quotation_Sale_Total_in_CC_AUD__c, IF(Currency__c == &apos;USD&apos;, Quotation_Sale_Total_in_CC_USD__c, IF(Currency__c == &apos;EUR&apos;, Quotation_Sale_Total_in_CC_EUR__c, IF(Currency__c == &apos;GBP&apos;, Quotation_Sale_Total_in_CC_GBP__c, 0.0) ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This displays the quote sale total in the selected client currency</inlineHelpText>
        <label>Quotation Sale Total in Selected CC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Exposure__c</fullName>
        <label>Quote Exposure</label>
        <summarizedField>Exposure_ROE__c.Quote_Exposure__c</summarizedField>
        <summaryForeignKey>Exposure_ROE__c.Quotation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/TH_ExposureRoe.cls
public class TH_ExposureRoe extends BaseTriggerHandler{
    
    private static final String CLASS_NAME = TH_Passenger.class.getName();
    private List<Exposure_ROE__c> newExposureROEList;
    private List<Exposure_ROE__c> oldExposureROEList;
    private Map<ID, Exposure_ROE__c> newExposureROEMap;
    private Map<ID, Exposure_ROE__c> oldExposureROEMap;
    
    public TH_ExposureRoe() {
        oldExposureROEList = (List<Exposure_ROE__c>)Trigger.old;
        newExposureROEList = (List<Exposure_ROE__c>)Trigger.new;
        newExposureROEMap =  (Map<ID, Exposure_ROE__c>)Trigger.newMap;
        oldExposureROEMap = (Map<ID, Exposure_ROE__c>)Trigger.oldMap;
    }
    
    
    protected override void afterInsert() {
        if(Trigger_PAD.canRun('TH_ExposureRoe'))
        {
            populateQuoteExposure();
        }
    }
    
    
     protected override void afterUpdate() {
        if(Trigger_PAD.canRun('TH_ExposureRoe'))
        {
            populateQuoteExposure();
        }
    }
    
    
    public void populateQuoteExposure()
    {
        List<Id> exposureIds = new List<Id>();
        for(Exposure_ROE__c eRoe: newExposureROEList)
        {
            exposureIds.add(eRoe.Id);
        }
        List<Exposure_ROE__c> toProcessRecords =[SELECT 
                                                        Id,
                                                        Quote_Exposure__c,
                                                        EXP_Quotation_Sale_Total_in_Selected_CC__c,
                                                        Quotation_Sale_Total_in_Selected_CC__c ,
                                                        Quotation__c
                                                FROM 
                                                        Exposure_ROE__c
                                                   WHERE
                                                         ID IN:exposureIds  ];
        
        List<Exposure_ROE__c> toUpdateExposureROE = new List<Exposure_ROE__c>();
        Set<Id> quotationIds = new Set<Id>();
       
        for(Exposure_ROE__c e: toProcessRecords)
        {
            if(e.Quotation_Sale_Total_in_Selected_CC__c > 0)
            {
                e.Quote_Exposure__c = ((e.Quotation_Sale_Total_in_Selected_CC__c/e.EXP_Quotation_Sale_Total_in_Selected_CC__c) - 1)*100;
                if(Integer.valueof(e.Quote_Exposure__c) < Integer.valueof(Label.Exposure_Threshold))
                {
                    quotationIds.add(e.Quotation__c);
                }
                toUpdateExposureROE.add(e);
            }
        }
      
      Set<Quotations__c> toUpdateQuotation = new Set<Quotations__c>();
      if(!quotationIds.isEmpty())
      {
        List<Quotations__c> allQuotations = DAL_Quotations.getAllQuotations(new List<Id>(quotationIds));
        for(Quotations__c q: allQuotations)
        {
            q.Approval_from_FX_Treasury_Required__c = true;
            toUpdateQuotation.add(q);
        }
      }
      
      if(!toUpdateQuotation.isEmpty())
      {
        BaseTriggerHandler.bypass('TH_Quotations');
        update new List<Quotations__c>(toUpdateQuotation);
       BaseTriggerHandler.clearBypass('TH_Quotations');
      }
      
      if(!toUpdateExposureROE.isEmpty())
     {
       BaseTriggerHandler.clearAllBypasses();
       BaseTriggerHandler.bypass('TH_ExposureRoe');
       BaseTriggerHandler.bypass('TH_Quotations');
        update toUpdateExposureROE;
       BaseTriggerHandler.clearBypass('TH_ExposureRoe');
       BaseTriggerHandler.clearBypass('TH_Quotations');
     }
    
    }   
     
}