Safari365 Prod/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Consultant_Profile__c</fullName>
        <defaultValue>$User.ProfileUrl__c</defaultValue>
        <label>Consultant Profile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerImageId__c</fullName>
        <label>OwnerImageId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ProfileImageUrl__c</fullName>
        <label>ProfileImageUrl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileUrl__c</fullName>
        <label>ProfileUrl</label>
        <type>Url</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/UpdateOwnerImageId.cls
public class UpdateOwnerImageId{

    public static void updateImageId(List<Lead> lst_Lead){

        Set<String> set_OwnerIds = new Set<String>();
        for(Lead l : lst_Lead){
            if(l.ownerid != null){
                set_OwnerIds.add(l.OwnerId);
            }
        }
        Map<Id, User> map_Users = new Map<Id, User>([ Select Id, ProfileImageUrl__c, ProfileUrl__c from User Where ID IN:set_OwnerIds] );

        for(Lead l : lst_Lead){
            if( l.OwnerId != null && map_Users.containsKey(l.OwnerId)){
                l.OwnerImageId__c = map_Users.get(l.ownerId).ProfileImageUrl__c;
                l.Consultant_Profile__c = map_Users.get(l.ownerId).ProfileUrl__c;
            }
        }
        
    }
    
}