Safari365 Prod/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Basket_Information__c</fullName>
        <inlineHelpText>These are items the Client chose/wanted when checking out of the Safari365 website</inlineHelpText>
        <label>Basket Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>New_Country_of_Residence__c</fullName>
        <inlineHelpText>NB to record this accurately (do not guess as we will market according to this in the future)</inlineHelpText>
        <label>Country of Residence (Master)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_of_Residence</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Website_origin__c</fullName>
        <inlineHelpText>Which Safari365 website did the client use to find us? (This will drive the Language used to communicate with the client) If unsure, choose &apos;Web: Safari365.com&apos;</inlineHelpText>
        <label>Website Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Web: safari365.com</fullName>
                </value>
                <value>
                    <fullName>Web: safari365.com.au</fullName>
                </value>
                <value>
                    <fullName>Web: southafrica365.com</fullName>
                </value>
                <value>
                    <fullName>Web:safari365.com.tur.br</fullName>
                </value>
                <value>
                    <fullName>Web: top5africa.com</fullName>
                </value>
                <value>
                    <fullName>Web: goodsafariguide.com</fullName>
                </value>
                <value>
                    <fullName>Web: safari365.com.cn</fullName>
                </value>
                <value>
                    <fullName>Web: safari365.es</fullName>
                </value>
                <value>
                    <fullName>Web: safari365.de</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/lead_onConvertTest.cls
@isTest
private class lead_onConvertTest
{
    public static List<Lead> testLeads = new List<Lead>();
    @testSetup static void setupInsertData()
    {
        User us = TestDataFactory.createUser(true, '', true);
        System.runAs(us){
            // Create the Lead object
            Lead testLead = new Lead(
                FirstName='Demo First',
                LastName = 'Demo Last UnitTest',
                Email = 'Test@test.com',
                New_Country_of_residence__c = 'South Africa',
                HasOptedOutOfEmail= true,
                Basket_Information__c='Hi this is just for testing purpose',
                Website_origin__c='Web: safari365.com',
                Status='Qualified'   
            );
            testLeads.add(testLead);
            insert testLeads;
        }
        
    }
    @isTest static void mLeadConvert()
    {
        User us = TestDataFactory.createUser(true, '', true);
        System.runAs(us)
        {
	        Lead testLead = [SELECT Id,Status FROM Lead limit 1];
	        Test.startTest();
	        System.debug('Created and inserted lead');
	        Database.LeadConvert lc = new database.LeadConvert();
	        lc.setLeadId(testLead.Id);
	        
	        //LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
	        //lc.setConvertedStatus(convertStatus.MasterLabel);
	        lc.setConvertedStatus(testLead.Status);
	        Database.LeadConvertResult lcr = Database.convertLead(lc);
	        
	        // Make sure conversion was successful
	        System.assert(lcr.isSuccess());
	        Test.stopTest();
        }
    }
}