Safari365 Prod/src/objects/Lead_Nurture__c.object
<CustomObject>
    <fields>
        <fullName>Converted_to_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted to Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Nurture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Nurture</label>
        <referenceTo>Lead_Nurture__c</referenceTo>
        <relationshipLabel>Lead Nurturing</relationshipLabel>
        <relationshipName>Lead_Nurturing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewsLetterSent__c</fullName>
        <label>NewsLetterSent</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_NewsLetter_Date__c</fullName>
        <label>Next NewsLetter Date</label>
        <type>Date</type>
    </fields>
    <label>Lead Nurture</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Lead Nurture Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Nurturing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/LeadNurtureMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in Batch_LeadNurtureNewsLetter</description>
    <label>LeadNurtureMapping</label>
</CustomObject>

Safari365 Prod/src/classes/Batch_LeadNurtureNewsLetter.cls
global class Batch_LeadNurtureNewsLetter implements Database.Batchable<sObject>,Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext BC){

        String queryStr =  'Select Id, Email__c, Last_Name__c, First_Name__c, NewsLetterSent__c, Next_NewsLetter_Date__c,';
        String TodayDate = String.valueOf(System.Today());
        String condition = 'WHERE Newsletter__c=true AND Converted_to_Lead__c=false AND Email__c!=null AND (Next_NewsLetter_Date__c=null OR Next_NewsLetter_Date__c='+TodayDate+') AND(';
        List<LeadNurtureMapping__c> leadNurture = LeadNurtureMapping__c.getall().values();

        for(LeadNurtureMapping__c var : leadNurture){
            queryStr = queryStr + var.Name +', ';
            condition = condition + var.name + '=true OR ';
        }
        queryStr = queryStr.substring(0, queryStr.length()-2) + ' FROM Lead_Nurture__c ';
        condition = condition.substring(0, condition.length()-3) + ')';
        queryStr = queryStr +condition;
        System.debug('---- '+ queryStr );
        if(test.isrunningtest()){
            queryStr = queryStr + ' limit 20';
        }
        return Database.getQueryLocator(queryStr);
    
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        LeadNurtureNewsLetter.sendNewsLetter((List<Lead_Nurture__c>)scope);               
    }

    global void finish(Database.BatchableContext BC){
       
    }
    
    global void execute(SchedulableContext sc)
    {
        Batch_LeadNurtureNewsLetter NewsLetter= new Batch_LeadNurtureNewsLetter();
        database.executebatch(NewsLetter, 20);
    }
    
}