Safari365 Prod/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Beach_relaxation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Beach relaxation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Botswana__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Botswana</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Family_safaris__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Family safaris</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Food_and_Wine__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Food and Wine</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>History_and_culture__c</fullName>
        <defaultValue>false</defaultValue>
        <label>History and culture</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Honeymoons_and_Romance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Honeymoons and Romance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kenya__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kenya</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Nurture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exists as Lead Nurture</label>
        <referenceTo>Lead_Nurture__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Namibia__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Namibia</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Did the Client agree to receive the Safari365 Newsletter or not?</inlineHelpText>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rwanda__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rwanda</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>South_Africa__c</fullName>
        <defaultValue>false</defaultValue>
        <label>South Africa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tanzania__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tanzania</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Uganda__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uganda</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Victoria_Falls__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Victoria Falls</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Walking_Safaris__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Walking Safaris</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zambia__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Zambia</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zanzibar_and_Pemba__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Zanzibar and Pemba</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Lead_Nurture__c.object
<CustomObject>
    <fields>
        <fullName>Active_and_outdoor_adventure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active and outdoor adventure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Beach_relaxation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Beach relaxation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Botswana__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Botswana</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Family_safaris__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Family safaris</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Food_and_Wine__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Food and Wine</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>History_and_culture__c</fullName>
        <defaultValue>false</defaultValue>
        <label>History and culture</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Honeymoons_and_romance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Honeymoons and romance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kenya__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kenya</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Nurture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Nurture</label>
        <referenceTo>Lead_Nurture__c</referenceTo>
        <relationshipLabel>Lead Nurturing</relationshipLabel>
        <relationshipName>Lead_Nurturing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Namibia__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Namibia</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rwanda__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rwanda</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>South_Africa__c</fullName>
        <defaultValue>false</defaultValue>
        <label>South Africa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tanzania__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tanzania</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Uganda__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uganda</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Victoria_Falls__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Victoria Falls</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Walking_safaris__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Walking safaris</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wildlife_and_safari_experiences__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wildlife and safari experiences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zambia__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Zambia</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zanzibar_and_Pemba__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Zanzibar and Pemba</label>
        <type>Checkbox</type>
    </fields>
    <label>Lead Nurture</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Lead Nurture Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Nurturing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Batch_LeadNurtureNewsLetter_Test.cls
@isTest(SeeAllData=true)
private class Batch_LeadNurtureNewsLetter_Test  {
    public static List<Lead_Nurture__c> lst_LeadNurture;
    static void setupData(){      
        lst_LeadNurture = new List<Lead_Nurture__c>();
        
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Active_and_outdoor_adventure__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Beach_relaxation__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Botswana__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Family_safaris__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Food_and_Wine__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',History_and_culture__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Honeymoons_and_romance__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Kenya__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Namibia__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Rwanda__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',South_Africa__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Tanzania__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Uganda__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Victoria_Falls__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Walking_safaris__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Wildlife_and_safari_experiences__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Zanzibar_and_Pemba__c=true)));
        lst_LeadNurture.add(getLeadNurture(new Lead_Nurture__c(Email__c='Test@NewTest.com',Zambia__c=true)));
        insert lst_LeadNurture;
    }
    static Lead_Nurture__c getLeadNurture(Lead_Nurture__c leadNearture_Obj){
        leadNearture_Obj.Newsletter__c=true;
        leadNearture_Obj.First_Name__c='testOne';
        leadNearture_Obj.Last_Name__c='testLast';
        return leadNearture_Obj;
    } 
    static testMethod void callmethod_Scheduler_Test() {                      
        Test.startTest();            
        setupData();            
        Batch_LeadNurtureNewsLetter m = new Batch_LeadNurtureNewsLetter();            
        String sch = '20 40 8 10 2 ?';            
        system.schedule('Batch Lead Nurt Test', sch, m);        
        Test.stopTest();         
    } 
}