Safari365 Prod/src/objects/NTS__c.object
<CustomObject>
    <label>NTS</label>
    <nameField>
        <displayFormat>NTS-{0000000}</displayFormat>
        <label>NTS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NTSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/SettingsToDeleteRecord__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <label>FieldName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldValue__c</fullName>
        <label>FieldValue</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>ObjectName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>SettingsToDeleteRecord</label>
    <pluralLabel>SettingsToDeleteRecords</pluralLabel>
</CustomObject>

Safari365 Prod/src/classes/Test_DeleteRecordsFromSalesforce.cls
@isTest
private class Test_DeleteRecordsFromSalesforce {

    public static Integer recordsCount =100;
    static List<NTS__c> nts= new List<NTS__c>();
    static void setupTestData()
    {
    	for(Integer i = 0 ; i <recordsCount; i++)
        {
            nts.add((NTS__c) TestDataFactory.operationOnObjectRecord(null, 'NTS__c', null));
        }
        
        insert nts;
    }
   
    public static SettingsToDeleteRecord__mdt createRecordsDelete(String objectName, String fieldValue
        , String fieldName, String operator, boolean active) 
    {
        Map<String, Object> jsonFields = new Map<String, Object>();
        SettingsToDeleteRecord__mdt recordsToDelete = new SettingsToDeleteRecord__mdt();
        jsonFields.put('ObjectName__c', objectName);
        jsonFields.put('FieldValue__c', fieldValue);
        jsonFields.put('FieldName__c', fieldName);
        jsonFields.put('Operator__c', operator);
        jsonFields.put('Active__c', active);
        
        recordsToDelete = (SettingsToDeleteRecord__mdt)JSON.deserialize(JSON.serialize(jsonFields), SettingsToDeleteRecord__mdt.class);
        return recordsToDelete;
    }
    
    
   
    static testMethod void deleteScheduleTest() {
    	setupTestData();
    	Test.startTest();
    	
    	DeleteRecordsFromSalesforce.DeleteRecords();
    	
    	Test.stopTest();
        
    }
}