Safari365 Prod/src/objects/OPD__c.object
<CustomObject>
    <fields>
        <fullName>ADD_ADULT1__c</fullName>
        <label>ADD ADULT1</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AGE_CATEGORY__c</fullName>
        <label>AGE CATEGORY</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EX1__c</fullName>
        <label>EX1</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EX2__c</fullName>
        <label>EX2</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EX3__c</fullName>
        <label>EX3</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EX4__c</fullName>
        <label>EX4</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EX5__c</fullName>
        <label>EX5</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OPD_ID__c</fullName>
        <externalId>true</externalId>
        <label>OPD ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OSR_ID__c</fullName>
        <label>OSR ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OSR_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OSR</label>
        <referenceTo>OSR__c</referenceTo>
        <relationshipLabel>OPDs</relationshipLabel>
        <relationshipName>OPDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAX_AGE_MAX__c</fullName>
        <label>PAX_AGE_MAX</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PAX_AGE_MIN__c</fullName>
        <label>PAX_AGE_MIN</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRICE_PXB1__c</fullName>
        <label>PRICE PXB1</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRICE_PXB2__c</fullName>
        <label>PRICE PXB2</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRICE_PXB3__c</fullName>
        <label>PRICE PXB3</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRICE_PXB4__c</fullName>
        <label>PRICE PXB4</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRICE_PXB5__c</fullName>
        <label>PRICE PXB5</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRICE_PXB6__c</fullName>
        <label>PRICE PXB6</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRICE_PXB7__c</fullName>
        <label>PRICE PXB7</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QR__c</fullName>
        <label>QR</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RATE_CATEGORY__c</fullName>
        <label>RATE CATEGORY</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RATE_TYPE__c</fullName>
        <label>RATE TYPE</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SS__c</fullName>
        <label>SS</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STD_EXT__c</fullName>
        <label>STD EXT</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR__c</fullName>
        <label>TR</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW__c</fullName>
        <label>TW</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>OPD</label>
    <nameField>
        <displayFormat>OPD-{00000000}</displayFormat>
        <label>OPD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OPDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/OSR__c.object
<CustomObject>
    <fields>
        <fullName>OSR_ID__c</fullName>
        <externalId>true</externalId>
        <label>OSR ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OSR</label>
    <nameField>
        <displayFormat>OSR-{00000000}</displayFormat>
        <label>OSR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_OPD.cls
public class DAL_OPD {
    
 public static final String OBJECT_NAME = OPD__c.SObjectType.getDescribe().getLocalName();
 
  public static Map<Id,OPD__c> getById(Set<Id> ids)
  {
    return new Map<Id,OPD__c >([SELECT 
                                    ADD_ADULT1__c,
                                    AGE_CATEGORY__c,
                                    EX1__c,EX2__c,EX3__c,EX4__c,EX5__c,
                                    Id,
                                    Name,
                                    OPD_ID__c,
                                    OSR_ID__c,
                                    OSR_Lookup__c,
                                    OwnerId,
                                    PAX_AGE_MAX__c,PAX_AGE_MIN__c,PRICE_PXB1__c,PRICE_PXB2__c,
                                    PRICE_PXB3__c,PRICE_PXB4__c,PRICE_PXB5__c,PRICE_PXB6__c,
                                    PRICE_PXB7__c,QR__c,RATE_CATEGORY__c,
                                    RATE_TYPE__c,SS__c,STD_EXT__c,
                                    TR__c,
                                    TW__c 
                                FROM 
                                    OPD__c
                            WHERE 
                                Id IN :ids]);
  }   
    
    public static List<OPD__c> GetOpdbyOsrId(OSR__c osr)
    {
        return [SELECT  Id,
                        RATE_TYPE__c,
                        RATE_CATEGORY__c,
                        SS__c,
                        QR__c,
                        TR__c,
                        TW__c,
                        AGE_CATEGORY__c,
                        EX1__c,EX2__c,EX3__c,EX4__c,EX5__c,
                        PAX_AGE_MAX__c,PAX_AGE_MIN__c,PRICE_PXB1__c,PRICE_PXB2__c,
                        PRICE_PXB3__c,PRICE_PXB4__c,PRICE_PXB5__c,PRICE_PXB6__c,
                        PRICE_PXB7__c
                FROM OPD__c 
                    WHERE OSR_Lookup__c=:osr.Id];
    }
}