Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_Display_Currency__c</fullName>
        <inlineHelpText>Choose the most likely Currency your client will want to pay in (based on their Country of Residence) The client can change this in the MembersClub if they desire, but will be unable to change once the Quotation goes to stage &quot;Raised Booking Confirmation&quot;</inlineHelpText>
        <label>Client Display Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exchange_Currency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_Not_Send_Phptpbook_Offer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick this if the client must not receive an email offering the free photobook</inlineHelpText>
        <label>Do Not Send Photobook Offer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entitled_to_Photobook_s__c</fullName>
        <inlineHelpText>How many Photobooks is this passenger entitled to? Enter a number only</inlineHelpText>
        <label>Entitled to Photobook(s)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Given_Age__c</fullName>
        <inlineHelpText>What age did the client give for this passenger? ( this will be used to calculate the applicable room rate)</inlineHelpText>
        <label>Given Age</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PassengerName__c</fullName>
        <label>PAX</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PassengerType__c</fullName>
        <label>Passenger Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adult</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Infant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/PassengerQuotationMapping__c.object
<CustomObject>
    <fields>
        <fullName>PassengerName__c</fullName>
        <formula>Passenger__r.PassengerName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PassengerName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PassengerQuotationMapping</label>
    <nameField>
        <displayFormat>PQM-{00000000}</displayFormat>
        <label>PassengerQuotationMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PassengerQuotationMappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quotation_Name__c</fullName>
        <inlineHelpText>Make this descriptive as it displays to the Client in the Members Club</inlineHelpText>
        <label>Quotation Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TravelStartDate__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/MultiSelectCheckboxPassengerController.cls
public class MultiSelectCheckboxPassengerController {
    
    @TestVisible
    public String parentID;
    public String recId{get;set;}
    @TestVisible
    public Date TravelStartDate{get;set;}
    @TestVisible
    public Date TravelEndDate{get;set;}
    public List<string> SelectedPassengers {get;set;}
    public List<SelectOption> PassengerSelectOptions {get;set;}
    public Quotations__c newQuotation{get;set;}
    private static final String CLASS_NAME = MultiSelectCheckboxPassengerController.class.getName();
    Map<Id, Passenger__c> failedCheckPassengers = new Map<Id, Passenger__c>();
    
    public MultiSelectCheckboxPassengerController(ApexPages.StandardController stdController) {
        failedCheckPassengers.clear();
        string str = UserInfo.getUiThemeDisplayed();
        Map<String,String> params = ApexPages.currentPage().getParameters();
        String keyName='';
        for (String key: params.keySet()){
            if(key.Contains('_lkid')){
                keyName = key;
            }
        }
        if(str == 'Theme4d'){
            parentID = ApexPages.currentPage().getParameters().get(keyName);
        }else{
            parentID = System.currentPagereference().getParameters().get('retURL').replace('/','');
        }        
        
        PassengerSelectOptions = new List<SelectOption>();
        List<Passenger__c> passengers  = [select Id,PassengerName__c from Passenger__c where Opportunity__c=:parentID];
        this.SelectedPassengers = new List<String>();
        for(Passenger__c p : passengers)
        {
            String name = p.PassengerName__c;
            if(name==NULL)
            {
                name='';
            }
            PassengerSelectOptions.add(new SelectOption(String.valueOf(p.Id), name));
            SelectedPassengers.add(String.valueOf(p.Id));
        }
        
        SetupnewQuotation();
    }
    
    public pageReference Save()
    {
        List<PassengerQuotationMapping__c> PassengerQuotationMappingList = new List<PassengerQuotationMapping__c>();
        UTIL_LogGenerator logger = new UTIL_LogGenerator();
        logger.start(CLASS_NAME,'Save');
        
        List<Passenger__c> passengers  = DAL_Passenger.getByIds(SelectedPassengers);
        boolean flagToProceed = validateInfantAndChildAgeExist(passengers);
        logger.log(flagToProceed);
        
        List<Opportunity> opportunity = DAL_Opportunity.getById(parentID);
        
        boolean validateEntitledToPhotobookValue = validateEntitledToPhotobook(opportunity[0],passengers);
        
        if(!validateEntitledToPhotobookValue)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'Amount of "Entitled to Photobook" must be greater than zero for at least one selected passenger or check the box "Do Not Send Phptpbook Offer" in opportunity');
            ApexPages.addMessage(myMsg);
        }
        
        else if(opportunity[0].Client_Display_Currency__c == null ||opportunity[0].Client_Display_Currency__c =='')
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'Client Display currency must be selected at Opportunity Level');
            ApexPages.addMessage(myMsg);
        }
        else if(!flagToProceed)
        {
            
            newQuotation.TravelStartDate__c=TravelStartDate;
            newQuotation.TravelEndDate__c = TravelEndDate;
            newQuotation.Email__c = opportunity[0].Email__c;
            insert newQuotation;
            
            for(String sp:SelectedPassengers)
            {
                PassengerQuotationMapping__c passengerQuotationMapping = new PassengerQuotationMapping__c();
                passengerQuotationMapping.Passenger__c = sp;
                passengerQuotationMapping.Quotation__c = newQuotation.Id;
                PassengerQuotationMappingList.add(passengerQuotationMapping);
                //insert passengerQuotationMapping; 
            }
            insert PassengerQuotationMappingList;
            
            //============================================================
            List<Id> ids = new List<Id>();
            ids.add(newQuotation.Id);
            if(!Test.isRunningTest()){
            	CreateFolderStructureGoogleDrive.createFolderGoogleDrive(ids);
            }
            //=============================================================
            PageReference pr = new PageReference('/'+newQuotation.Id);
            pr.setRedirect(true); 
            return pr;
        }
        else
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'Infant need an age');
            ApexPages.addMessage(myMsg);
        }
        //ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'Infant need an age');
        //ApexPages.addMessage(myMsg);
        logger.end();
        return null;
    }
    
    /* public pageReference SaveAndNew()
    {
    newQuotation.TravelStartDate__c=TravelStartDate;
    newQuotation.TravelEndDate__c = TravelEndDate;
    
    insert newQuotation;
    
    for(String sp:SelectedPassengers)
    {
    PassengerQuotationMapping__c passengerQuotationMapping = new PassengerQuotationMapping__c();
    passengerQuotationMapping.Passenger__c = sp;
    passengerQuotationMapping.Quotation__c = newQuotation.Id;
    insert passengerQuotationMapping; 
    }
    
    SetupnewQuotation();
    
    return null;
    }*/
    
    public pageReference Cancel()
    {
        PageReference pr = new PageReference('/'+parentID);
        pr.setRedirect(false); 
        return pr;
    }
    
    private void SetupnewQuotation()
    {
        newQuotation = new Quotations__c();
        if(!Test.isRunningTest())
        {
        newQuotation.Quotation_Name__c='';
        }
        else{
        	newQuotation.Quotation_Name__c='Test Quotation';
        }
        newQuotation.Opportunity__c = parentID;
        TravelStartDate = Date.today();
        TravelEndDate = Date.today().addDays(1);
        
        //SelectedPassengers = new List<String>();
    }
    
    private boolean validateEntitledToPhotobook(Opportunity opportunity, List<Passenger__c> passengers)
    {
        boolean flag = false;
        //List<Opportunity> Opportunity = DAL_Opportunity.getById(parentID);
        
        if(opportunity.Do_Not_Send_Phptpbook_Offer__c == true)
        {
            return true;
        }
        
        for(Passenger__c p: passengers)
        {
            if(p.Entitled_to_Photobook_s__c > 0)
            {
                flag = true;
                failedCheckPassengers.put(p.Id, p);
                break;
            }       
        }
        return flag;
    }
    private boolean validateInfantAndChildAgeExist(List<Passenger__c> passengers)
    {
        UTIL_LogGenerator logger = new UTIL_LogGenerator();
        logger.start(CLASS_NAME,'Save');
        
        logger.log(passengers);
        boolean flag = false;
        for(Passenger__c p: passengers)
        {
            if((p.PassengerType__c=='Infant'|| p.PassengerType__c=='Child') 
               && (p.Given_Age__c == ' ' || p.Given_Age__c == null)
               && (p.Entitled_to_Photobook_s__c > 0))
            {
                flag = true;
                failedCheckPassengers.put(p.Id, p);
                break;
            }       
        }
        return flag;
    }
    
}