Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Currency_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Currency Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Display_Currency__c</fullName>
        <inlineHelpText>Choose the most likely Currency your client will want to pay in (based on their Country of Residence) The client can change this in the MembersClub if they desire, but will be unable to change once the Quotation goes to stage &quot;Raised Booking Confirmation&quot;</inlineHelpText>
        <label>Client Display Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exchange_Currency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoS__c</fullName>
        <label>CoS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Do_Not_Send_Phptpbook_Offer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick this if the client must not receive an email offering the free photobook</inlineHelpText>
        <label>Do Not Send Photobook Offer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>GoogleOppFolderId__c</fullName>
        <inlineHelpText>Stores the Google Fiolder ID so system can reference file location</inlineHelpText>
        <label>GoogleOppFolderId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <label>Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Has_Confirmed_Quotation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If there is a confirmed quotation linked to this Opportunity, it looks at this for the rollup</inlineHelpText>
        <label>Opportunity Has a Confirmed Quotation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>International_Flight_Arrival_Details__c</fullName>
        <label>International Flight Arrival Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>International_Flight_Departure_Details__c</fullName>
        <label>International Flight Departure Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TravelEndDate__c</fullName>
        <label>Travel End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_Opportunity.cls
public class DAL_Opportunity {
  
  public static final String OBJECT_NAME = Opportunity.SObjectType.getDescribe().getLocalName();
  
  public static Map<Id,Opportunity> getAllOpportunity(Set<Id> ids)
  {
    return new Map<Id,Opportunity>([SELECT
                  Id,
                  Name,
                  Arrival_Date__c,
                  TravelEndDate__c,
                  CloseDate,
                  CoS__c,
                  Gross_Profit__c,
                  StageName,
                  Amount,
                  Owner.Email,
                  Do_Not_Send_Phptpbook_Offer__c,
                  International_Flight_Arrival_Details__c,
                  International_Flight_Departure_Details__c,
                  Has_Confirmed_Quotation__c
             FROM 
                  Opportunity
            WHERE 
                  Id IN :ids
                  //AND 
                  //CloseDate >=:system.today()
                  ]);
  }
  
 public static List<Opportunity> getByIds(Set<Id> ids)
  {
    return [SELECT
                  Id,
                  Name,
                  AccountId,
                  Arrival_Date__c,
                  CloseDate,
                  CoS__c,
                  Gross_Profit__c,
                  Amount,
                  Email__c,
                  Client_Name__c,
                  Do_Not_Send_Phptpbook_Offer__c,
                  International_Flight_Arrival_Details__c,
                  International_Flight_Departure_Details__c,
                  Client_Display_Currency__c 
             FROM 
                  Opportunity
            WHERE 
                Id IN :ids];
  }
  
  public static Map<Id,Opportunity> getConfirmedOpportunity(Set<Id> ids)
  {
    return new Map<Id,Opportunity>([SELECT
                  Id,
                  Name,
                  Has_Confirmed_Quotation__c,
                  CoS__c,
                  Gross_Profit__c,
                  Amount,
                  Arrival_Date__c,
                  TravelEndDate__c
             FROM 
                  Opportunity
            WHERE 
                 Id IN :ids
             AND 
                Has_Confirmed_Quotation__c = true]);
  }
  
  public static List<Opportunity> getActiveOpportunity(Id OpportunityId)
  {
    return [SELECT
                  Id,
                  Name,
                  Owner.Name,
                  Owner.Phone,
                  Owner.Email,
                  Client_Display_Currency__c,
                  Client_Currency_Locked__c
             FROM 
                  Opportunity
            WHERE 
                Id =: OpportunityId 
            AND 
                StageName != 'Closed Lost'
            ORDER BY
                CreatedDate DESC];
  }
    
  public static List<Opportunity> getById(String opportunityId)
  {
    Set<Id> ids  = new Set<Id>();
    ids.add(Id.valueof(opportunityId));
    return getByIds(ids);
  }
  
  public static Opportunity getOpportunityById(String oppId)
    {
      return [SELECT 
                     Id,
                    Name,
                    GoogleOppFolderId__c,
                    OwnerId,
                    AccountId
             FROM 
                  Opportunity
            WHERE 
                Id = :oppId];
    }
}