Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>How_can_Safari365_improve__c</fullName>
        <label>How can Safari365 improve</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Improvements__c</fullName>
        <label>Improvements</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Overall_Impressions__c</fullName>
        <label>Overall Impressions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Overall_client_safari_experience__c</fullName>
        <label>Overall client safari experience</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Rating_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rating 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rating_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rating 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rating_3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rating 3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rating_4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rating 4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rating_5__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rating 5</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Review_Stage__c</fullName>
        <label>Review Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Loaded</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>De -Active</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Star_Rating__c</fullName>
        <label>Star Rating</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/WS_GetUpdateReviewOpportunity.cls
@RestResource(urlMapping='/Safari365/MembersClub/GetUpdateReviewOpportunity/*')
global  with sharing class WS_GetUpdateReviewOpportunity
{
    private static final String SUCCESS = 'Success';
    private static final String ERROR = 'Error';
    private static final String BLANK_STRING = '';
    
    @Httppost
    global static ResponseWrapper doPost(RequestWrapper requestWrapper)
    {
        ResponseWrapper returnResponse = new ResponseWrapper();
        returnResponse.requestWrapper = requestWrapper;
        
        try{
            if(requestWrapper.OpportunityInfo != null
            	 && requestWrapper.OpportunityInfo.OpportunityId != null 
            	 && requestWrapper.OpportunityInfo.OpportunityId != '')
             {
                Opportunity opportunity = new Opportunity(Id = requestWrapper.OpportunityInfo.OpportunityId);
                //opportunity.Star_Rating__c = requestWrapper.OpportunityInfo.StarRating;
                //opportunity.Overall_Impressions__c = requestWrapper.OpportunityInfo.OverallImpressions;
                //opportunity.Improvements__c = requestWrapper.OpportunityInfo.Improvements;
                
                opportunity.Review_Stage__c = requestWrapper.OpportunityInfo.ReviewStage;
				opportunity.Overall_client_safari_experience__c= requestWrapper.OpportunityInfo.Overallclientsafariexperience;
				opportunity.How_can_Safari365_improve__c= requestWrapper.OpportunityInfo.HowcanSafari365improve;
				opportunity.Rating_1__c= requestWrapper.OpportunityInfo.Rating1;
				opportunity.Rating_2__c= requestWrapper.OpportunityInfo.Rating2;
				opportunity.Rating_3__c= requestWrapper.OpportunityInfo.Rating3;
				opportunity.Rating_4__c= requestWrapper.OpportunityInfo.Rating4;
				opportunity.Rating_5__c= requestWrapper.OpportunityInfo.Rating5;

                update opportunity;
                returnResponse.status  = SUCCESS;
            }
            else {
                returnResponse.status  = Error;
                returnResponse.errorMessage ='Opportunity Not found';
            }
        }catch(Exception ex){
            returnResponse.status  = Error;
            returnResponse.errorMessage = ex.getMessage();
        }
     
       return returnResponse;
    }
    
    global class ResponseWrapper {
        webservice String status;
        webservice String errorMessage;        
        webservice RequestWrapper requestWrapper;
    }
        
    global class RequestWrapper {
        
        webservice OpportunityInfoWrapper OpportunityInfo;
        
        public RequestWrapper(OpportunityInfoWrapper oppWrap) {
            this.OpportunityInfo = oppWrap;
        }
    }   
    
    global class OpportunityInfoWrapper
     {
        webservice String OpportunityId;
        webservice String ReviewStage;
        webservice String Overallclientsafariexperience;
        webservice String HowcanSafari365improve;
	    webservice Boolean Rating1;
	    webservice Boolean Rating2;
	    webservice Boolean Rating3;
	    webservice Boolean Rating4;
	    webservice Boolean Rating5;
    }       
        
}
/********************************************************

{
    "requestWrapper": {
        "OpportunityInfo":{
            "OpportunityId":"0060E000007jk8A",
            "StarRating":"4",
            "OverallImpressions":"Test OverallImpressions",
            "Improvements": "Test Improvements"
        }   
    }

}


***********************************************************/