Safari365 Prod/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <label>Travel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PhotoBook_Tracking_Number__c</fullName>
        <inlineHelpText>Enter this from DHL (courrier) service as it will be automatically emailed to the client</inlineHelpText>
        <label>PhotoBook Tracking Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkflowRun__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WorkflowRun</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/OpportunityEmailUpdateHandler_Test.cls
@isTest
private class OpportunityEmailUpdateHandler_Test {

     static Account accountObj;
     static Date arrivaleDate = Date.newInstance(2008,1,1);
     static Date closeDate = Date.newInstance(2008,1,1); 
     
     static void setupData(){
        Recordtype rt = [ select id from recordtype where name='person Account'];
        accountObj = new Account(recordtypeid=rt.id, 
        						FirstName='testFirst', lastName='test Last', 
        						Phone='4343343434', PersonEmail='tes1t@fakememail.com',
        						Salutation='Mr.');
        insert accountObj;
    } 
    
    public testmethod static void testUpdateEmailFromAccount(){
        setupData();
        Test.startTest();
        Opportunity opp  = new Opportunity();
	       opp.Name = 'testScheduledApexFromTest';
	       opp.StageName='Money in the Bank';
	       opp.CloseDate=closeDate;
	       opp.Arrival_Date__c=arrivaleDate;
	       opp.WorkflowRun__c=false;
	       opp.PhotoBook_Tracking_Number__c='1111';
	       opp.AccountId= accountObj.Id;
	       insert opp;
        Test.stopTest();
    }
    
}