Safari365 Prod/src/objects/OSR__c.object
<CustomObject>
    <fields>
        <fullName>APPLY_FRI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPLY FRI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPLY_MON__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPLY MON</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPLY_SAT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPLY SAT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPLY_SUN__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPLY SUN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPLY_THU__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPLY THU</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPLY_TUE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPLY TUE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPLY_WED__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPLY WED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BUY_CURRENCY__c</fullName>
        <label>BUY CURRENCY</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CANCEL_HOURS__c</fullName>
        <label>CANCEL HOURS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CHARGEEXTRA1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHARGEEXTRA1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHARGEEXTRA2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHARGEEXTRA2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHARGEEXTRA3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHARGEEXTRA3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHARGEEXTRA4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHARGEEXTRA4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHARGEEXTRA5__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHARGEEXTRA5</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>COMMISSIONABLE__c</fullName>
        <label>COMMISSIONABLE</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>COMM_ORIDE__c</fullName>
        <label>COMM ORIDE</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DATE_FROM__c</fullName>
        <label>DATE FROM</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DATE_TO__c</fullName>
        <label>DATE TO</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EDITVTEXT10__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDITVTEXT10</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EDITVTEXT1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDITVTEXT1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EDITVTEXT2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDITVTEXT2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EDITVTEXT3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDITVTEXT3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EDITVTEXT4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDITVTEXT4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EDITVTEXT5__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDITVTEXT5</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EDITVTEXT6__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDITVTEXT6</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EDITVTEXT7__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDITVTEXT7</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EDITVTEXT8__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDITVTEXT8</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EDITVTEXT9__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EDITVTEXT9</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EXCHANGE_DIV_RATE__c</fullName>
        <label>EXCHANGE DIV RATE</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EXCHANGE_MUT_RATE__c</fullName>
        <label>EXCHANGE MUT RATE</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FIXED_COUNT__c</fullName>
        <label>FIXED COUNT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FREE10__c</fullName>
        <label>FREE10</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FREE1__c</fullName>
        <label>FREE1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FREE2__c</fullName>
        <label>FREE2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FREE3__c</fullName>
        <label>FREE3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FREE4__c</fullName>
        <label>FREE4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FREE5__c</fullName>
        <label>FREE5</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FREE6__c</fullName>
        <label>FREE6</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FREE7__c</fullName>
        <label>FREE7</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FREE8__c</fullName>
        <label>FREE8</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FREE9__c</fullName>
        <label>FREE9</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GROSS_NETT__c</fullName>
        <label>GROSS NETT</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAX_SCU__c</fullName>
        <label>MAX SCU</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MIN_SCU__c</fullName>
        <label>MIN SCU</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OPC_Description__c</fullName>
        <formula>OPC_Lookup__r.Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OPC Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OPC_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OPC</label>
        <referenceTo>OPC__c</referenceTo>
        <relationshipLabel>OSRs</relationshipLabel>
        <relationshipName>OSRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OPT_ID__c</fullName>
        <label>OPT ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OPT_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OPT</label>
        <referenceTo>Opt__c</referenceTo>
        <relationshipLabel>OSRs</relationshipLabel>
        <relationshipName>OSRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OSR_ID__c</fullName>
        <externalId>true</externalId>
        <label>OSR ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PREFER__c</fullName>
        <label>PREFER</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRICE_CODE__c</fullName>
        <label>PRICE CODE</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PROV__c</fullName>
        <label>PROV</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RATE_TEXT__c</fullName>
        <label>RATE TEXT</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REPEAT_IND__c</fullName>
        <label>REPEAT IND</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REPEAT_TIMES__c</fullName>
        <label>REPEAT TIMES</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SALE_FROM__c</fullName>
        <label>SALE FROM</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SALE_TO__c</fullName>
        <label>SALE TO</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SELLBEFORETRAVEL__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SELLBEFORETRAVEL</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SELLBEFORETYPE__c</fullName>
        <label>SELLBEFORETYPE</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SELL_CODE__c</fullName>
        <label>SELL CODE</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SELL_CURRENCY__c</fullName>
        <label>SELL CURRENCY</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPLITRATE__c</fullName>
        <label>SPLITRATE</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STAY10__c</fullName>
        <label>STAY10</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STAY1__c</fullName>
        <label>STAY1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STAY2__c</fullName>
        <label>STAY2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STAY3__c</fullName>
        <label>STAY3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STAY4__c</fullName>
        <label>STAY4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STAY5__c</fullName>
        <label>STAY5</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STAY6__c</fullName>
        <label>STAY6</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STAY7__c</fullName>
        <label>STAY7</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STAY8__c</fullName>
        <label>STAY8</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STAY9__c</fullName>
        <label>STAY9</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STAYPAY_FROM__c</fullName>
        <label>STAYPAY FROM</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>STAYPAY_TO__c</fullName>
        <label>STAYPAY TO</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>STAY_TYPE__c</fullName>
        <label>STAY TYPE</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VALIDATE_MIN_MAX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VALIDATE MIN MAX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VTEXT10__c</fullName>
        <label>VTEXT10</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTEXT1__c</fullName>
        <label>VTEXT1</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTEXT2__c</fullName>
        <label>VTEXT2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTEXT3__c</fullName>
        <label>VTEXT3</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTEXT4__c</fullName>
        <label>VTEXT4</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTEXT5__c</fullName>
        <label>VTEXT5</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTEXT6__c</fullName>
        <label>VTEXT6</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTEXT7__c</fullName>
        <label>VTEXT7</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTEXT8__c</fullName>
        <label>VTEXT8</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTEXT9__c</fullName>
        <label>VTEXT9</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>OSR</label>
    <nameField>
        <displayFormat>OSR-{00000000}</displayFormat>
        <label>OSR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_OSR.cls
public class DAL_OSR {
   
  public static final String OBJECT_NAME = OSR__c.SObjectType.getDescribe().getLocalName();
 
  public static List<OSR__c> getByIds(Set<Id> ids)
  {
    return [SELECT APPLY_FRI__c,APPLY_MON__c,APPLY_SAT__c,
                   APPLY_SUN__c,APPLY_THU__c,APPLY_TUE__c,APPLY_WED__c,
                   BUY_CURRENCY__c,CANCEL_HOURS__c,CHARGEEXTRA1__c,
                   CHARGEEXTRA2__c,CHARGEEXTRA3__c,CHARGEEXTRA4__c,
                   CHARGEEXTRA5__c,COMMISSIONABLE__c,COMM_ORIDE__c,
                   DATE_FROM__c,DATE_TO__c,EDITVTEXT1__c,
                   EDITVTEXT2__c,EDITVTEXT3__c,EDITVTEXT4__c,
                   EDITVTEXT5__c,EDITVTEXT6__c,EDITVTEXT7__c,
                   EDITVTEXT8__c,EDITVTEXT9__c,EDITVTEXT10__c,
                   EXCHANGE_DIV_RATE__c,EXCHANGE_MUT_RATE__c,
                   FIXED_COUNT__c,FREE1__c,FREE2__c,
                   FREE3__c,FREE4__c,FREE5__c,FREE6__c,
                   FREE7__c,FREE8__c,FREE9__c,FREE10__c,
                   GROSS_NETT__c,
                   Id,
                   MAX_SCU__c,MIN_SCU__c,
                   Name,
                   OPC_Description__c,OPC_Lookup__c,
                   OPT_ID__c,OPT_Lookup__c,OSR_ID__c,
                   PREFER__c,PRICE_CODE__c,
                   PROV__c,RATE_TEXT__c,REPEAT_IND__c,REPEAT_TIMES__c,
                   SALE_FROM__c,SALE_TO__c,SELLBEFORETRAVEL__c,SELLBEFORETYPE__c,
                   SELL_CODE__c,SELL_CURRENCY__c,SPLITRATE__c,
                   STAY1__c,STAY2__c,STAY3__c,STAY4__c,
                   STAY5__c,STAY6__c,STAY7__c,STAY8__c,STAY9__c,
                   STAY10__c,STAYPAY_FROM__c,STAYPAY_TO__c,STAY_TYPE__c,
                   VALIDATE_MIN_MAX__c,VTEXT1__c,VTEXT2__c,VTEXT3__c,
                   VTEXT4__c,VTEXT5__c,VTEXT6__c,VTEXT7__c,
                   VTEXT8__c,VTEXT9__c,VTEXT10__c
             FROM 
                   OSR__c
             WHERE 
                  Id IN :ids];
  }
 
  
  public static Map<Id,OSR__c> getById(Set<Id> ids)
  {
    return new Map<Id,OSR__c >(getByIds(ids));
  } 
  
  public static Map<String,Object> getStayFreeValueMap(Set<Id> ids)
  {
    
    Map<String,String> keyValueMap  = new Map<String, String>();
    List<Field_Mapping_For_Rate_Calculation__mdt> fieldMappings = [
                          SELECT 
                                Source_Object__c, 
                                Target_Object__c, 
                                Source_Field__c,
                                Target_Field__c
                         FROM 
                                Field_Mapping_For_Rate_Calculation__mdt];
     for(Field_Mapping_For_Rate_Calculation__mdt mapping: fieldMappings)
     {
        keyValueMap.put(mapping.Source_Field__c, mapping.Target_Field__c);
     }  
     
     Map<String, Object> fieldsAndValues     = null;
     List<OSR__c> osrs  = DAL_OSR.getByIds(ids); 
     for(OSR__c osr: osrs) 
     { 
      fieldsAndValues = osr.getPopulatedFieldsAsMap(); 
     }
     Map<String , Object> keyValueReturnMap  = new Map<String, Object>();
     for(Field_Mapping_For_Rate_Calculation__mdt mapping: fieldMappings)
     {
        keyValueReturnMap.put(mapping.Source_Field__c, fieldsAndValues.get(keyValueMap.get(mapping.Source_Field__c)));
     }      
     
     return keyValueReturnMap;
  }
  
  
  public static List<OSR__c> getOsrbyOPTId(Set<Id> optIds)
  {
    return [SELECT APPLY_FRI__c,APPLY_MON__c,APPLY_SAT__c,
                   APPLY_SUN__c,APPLY_THU__c,APPLY_TUE__c,APPLY_WED__c,
                   BUY_CURRENCY__c,CANCEL_HOURS__c,CHARGEEXTRA1__c,
                   CHARGEEXTRA2__c,CHARGEEXTRA3__c,CHARGEEXTRA4__c,
                   CHARGEEXTRA5__c,COMMISSIONABLE__c,COMM_ORIDE__c,
                   DATE_FROM__c,DATE_TO__c,EDITVTEXT1__c,
                   EDITVTEXT2__c,EDITVTEXT3__c,EDITVTEXT4__c,
                   EDITVTEXT5__c,EDITVTEXT6__c,EDITVTEXT7__c,
                   EDITVTEXT8__c,EDITVTEXT9__c,EDITVTEXT10__c,
                   EXCHANGE_DIV_RATE__c,EXCHANGE_MUT_RATE__c,
                   FIXED_COUNT__c,FREE1__c,FREE2__c,
                   FREE3__c,FREE4__c,FREE5__c,FREE6__c,
                   FREE7__c,FREE8__c,FREE9__c,FREE10__c,
                   GROSS_NETT__c,
                   Id,
                   MAX_SCU__c,MIN_SCU__c,
                   Name,
                   OPC_Description__c,OPC_Lookup__c,
                   OPT_ID__c,OPT_Lookup__c,OSR_ID__c,
                   PREFER__c,PRICE_CODE__c,
                   PROV__c,RATE_TEXT__c,REPEAT_IND__c,REPEAT_TIMES__c,
                   SALE_FROM__c,SALE_TO__c,SELLBEFORETRAVEL__c,SELLBEFORETYPE__c,
                   SELL_CODE__c,SELL_CURRENCY__c,SPLITRATE__c,
                   STAY1__c,STAY2__c,STAY3__c,STAY4__c,
                   STAY5__c,STAY6__c,STAY7__c,STAY8__c,STAY9__c,
                   STAY10__c,STAYPAY_FROM__c,STAYPAY_TO__c,STAY_TYPE__c,
                   VALIDATE_MIN_MAX__c,VTEXT1__c,VTEXT2__c,VTEXT3__c,
                   VTEXT4__c,VTEXT5__c,VTEXT6__c,VTEXT7__c,
                   VTEXT8__c,VTEXT9__c,VTEXT10__c
             FROM 
                   OSR__c
             WHERE 
                  OPT_Lookup__c IN :optIds];
  }
}