Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Sub_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Sub Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entitled_to_Photobook_s__c</fullName>
        <inlineHelpText>How many Photobooks is this passenger entitled to? Enter a number only</inlineHelpText>
        <label>Entitled to Photobook(s)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Given_Age__c</fullName>
        <inlineHelpText>What age did the client give for this passenger? ( this will be used to calculate the applicable room rate)</inlineHelpText>
        <label>Given Age</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>International_Flight_Arrival_Details__c</fullName>
        <label>International Flight Arrival Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>International_Flight_Departure_Details__c</fullName>
        <label>International Flight Departure Details </label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Surname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers (New Account)</relationshipLabel>
        <relationshipName>Passengers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PassengerName__c</fullName>
        <label>PAX</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PassengerType__c</fullName>
        <label>Passenger Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adult</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Infant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Emergency_Phone_Number__c</fullName>
        <label>Policy Emergency Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Privacy_Policy_Agreed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Privacy Policy Agreed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers (Sub Opportunity)</relationshipLabel>
        <relationshipName>Passengers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscribe_me_to_newsletter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Subscribe me to newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Travel_Insurance_Policy_Number__c</fullName>
        <label>Travel Insurance Policy Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Insurance_Policy_Provider__c</fullName>
        <label>Travel Insurance Policy Provider</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Insurance__c</fullName>
        <label>Travel Insurance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>I have arranged my own travel insurance ( inclusive of cancellation,curtailment/lost baggage etc )</fullName>
                </value>
                <value>
                    <fullName>I don&apos;t have travel insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Waiver_Of_Liability_Date__c</fullName>
        <label>Waiver Of Liability Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Waiver_Of_Liability_Name__c</fullName>
        <label>Waiver Of Liability Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Waiver_Of_Liability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waiver Of Liability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WebSite_Origin_From_Parent_Account__c</fullName>
        <formula>Account__r.Website_Origin_c__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Website Origin From Parent Account</label>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/PassengerQuotationMapping__c.object
<CustomObject>
    <fields>
        <fullName>PassengerName__c</fullName>
        <formula>Passenger__r.PassengerName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PassengerName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PassengerQuotationMapping</label>
    <nameField>
        <displayFormat>PQM-{00000000}</displayFormat>
        <label>PassengerQuotationMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PassengerQuotationMappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This field restricts a user editing a quotation that has already been paid or quoted in FX to Booking Confirmation. Please seek administrator authorization should you need to edit this confirmed quotation</inlineHelpText>
        <label>Untick to Edit Confirmed Quote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quotation_Stage__c</fullName>
        <label>Quotation Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quoting</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Raised Invoice</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_Passenger.cls
public class DAL_Passenger {
    
 public static final String OBJECT_NAME = Passenger__c.SObjectType.getDescribe().getLocalName();

 public static Integer getExisitingCouunt(String passengerType , Id oppId)
 {
   String query ='SELECT count() from Passenger__c WHERE PassengerType__c =\''+passengerType + '\' AND Opportunity__c ='+'\''+oppId  +'\'';
   Integer  count= database.countQuery(query);
   return count;

 }
 
 
public static List<Passenger__c> getByIds(List<String> ids)
{
  return [Select 
                Id,
                Name,
                PassengerType__c,
                Given_Age__c,
                PassengerName__c,
                Is_Primary__c,
                Entitled_to_Photobook_s__c,
                New_Account__c,
                Account__c,
                Opportunity__c,
                Create_Sub_Opportunity__c,
                Travel_Insurance_Policy_Provider__c,
                Travel_Insurance_Policy_Number__c,
                Travel_Insurance__c,
                Policy_Emergency_Phone_Number__c,
                International_Flight_Departure_Details__c,
                International_Flight_Arrival_Details__c,
                Waiver_Of_Liability__c,
                Waiver_Of_Liability_Date__c,
                Waiver_Of_Liability_Name__c,
                Sub_Opportunity__c,
                Last_Name__c,
                Confirmed__c,
                WebSite_Origin_From_Parent_Account__c,
                Privacy_Policy_Agreed__c,
                Subscribe_me_to_newsletter__c
            FROM 
                Passenger__c
           WHERE 
                Id IN:ids
        ORDER BY
                PassengerName__c ];
}

public static List<Passenger__c> getPrimaryByIds(List<String> ids)
{
  return [Select 
                Id ,
                PassengerType__c,
                Given_Age__c,
                PassengerName__c
            FROM 
                Passenger__c
           WHERE 
                Id IN:ids AND Is_Primary__c=:true];
}    
public static List<Passenger__c> getById(String id)
{
  List<String> s = new List<String>();
  s.add(id);
  return getByIds(s);
}
 
public static List<String> GetPassengerAgeList()
{
    List<String> options = new List<String>();
    options.add('--Select Age--');    
        Schema.DescribeFieldResult fieldResult = Passenger__c.Given_Age__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }       
        return options;
}    


public static List<PassengerQuotationMapping__c> getAllQuotationsRelatedToPassengers(Set<Id> passengerIds)
{
    return [Select 
                Id ,
                Passenger__c,
                Quotation__c
            FROM 
                PassengerQuotationMapping__c
           WHERE 
                Passenger__c IN:passengerIds];
}

public static List<PassengerQuotationMapping__c> getAllPassengerQuotation(List<Id> quotationIds)
{
    return [Select 
                    Id,
                    Passenger__r.Name,
                    Passenger__c,
                    Quotation__c,
                    Quotation__r.Quotation_Stage__c,
                    Passenger__r.Waiver_Of_Liability__c
                FROM 
                    PassengerQuotationMapping__c
               WHERE 
                    Quotation__c IN:quotationIds];
}

    public static Passenger__c getPasenger_DynamiCSOQL(String PassengerId) {
        try
        {
            String query = 'SELECT ';
            for(Schema.FieldSetMember f : SObjectType.Passenger__c.FieldSets.WS_GetPassenger.getFields()) {
                query += f.getFieldPath() + ',';
            }
            query = query.substring(0, query.length()-1);
            query += ' FROM Passenger__c WHERE Id = \''+PassengerId+'\'';
            return Database.query(query);
        }
        catch(Exception e){
            return null;
        }
       
    }
    
    public static List<Passenger__c> getPasengers_DynamiCSOQL(List<String> PassengerIds) {
        try
        {
            String query = 'SELECT ';
            for(Schema.FieldSetMember f : SObjectType.Passenger__c.FieldSets.WS_GetPassenger.getFields()) {
                query += f.getFieldPath() + ',';
            }
            query = query.substring(0, query.length()-1);
            query += ' FROM Passenger__c WHERE Id IN (';
            for(String str  : PassengerIds){
                query += '\'' + str + '\',';    
            }
            query = query.substring(0, query.length()-1) + ')';
            return Database.query(query);
        }
        catch(Exception e){
            return null;
        }
        
    }

 public static List<WS_GetPassengers.PassengerInfoWrapper> getPassengersDetailsByQuotationId(List<Id> quotationIds)
 {
    List<PassengerQuotationMapping__c> mappingRecords = getAllPassengerQuotation(quotationIds);
    List<String> passengerIds = new List<String>();
    Map<String, String> QuationStatusMap =new Map<String, String>(); 
    for(PassengerQuotationMapping__c pqm: mappingRecords)
    {
        passengerIds.add(pqm.Passenger__c);
        QuationStatusMap.put(pqm.Passenger__c,pqm.Quotation__r.Quotation_Stage__c);
    }
    
    List<Passenger__c> passengers =getByIds(passengerIds);
    List<WS_GetPassengers.PassengerInfoWrapper> passengerInfoWrappers =new List<WS_GetPassengers.PassengerInfoWrapper>();
    for(Passenger__c p:passengers )
    {
        passengerInfoWrappers.add( new WS_GetPassengers.PassengerInfoWrapper(p.PassengerType__c,p.Is_Primary__c,
                          p.PassengerName__c,String.valueof(p.Id),QuationStatusMap.get(p.Id),p.Waiver_Of_Liability__c));
    }
    
    return passengerInfoWrappers;
 }
}