Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>PassengerType__c</fullName>
        <label>Passenger Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adult</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Infant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItemPassengersMapping__c.object
<CustomObject>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>ServiceLineItemPassengersMappings</relationshipLabel>
        <relationshipName>ServiceLineItemPassengersMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Line Item</label>
        <referenceTo>ServiceLineItem__c</referenceTo>
        <relationshipLabel>ServiceLineItemPassengersMappings</relationshipLabel>
        <relationshipName>ServiceLineItemPassengersMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ServiceLineItemPassengersMapping</label>
    <nameField>
        <displayFormat>SLIP-{00000000}</displayFormat>
        <label>ServiceLineItemPassengersMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceLineItemPassengersMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_ServiceLineItemPassengersMapping.cls
public class DAL_ServiceLineItemPassengersMapping{

  public static integer getAdultPassengerCountBySerLineItemId(String serviceLineItemId){
     return [
             SELECT 
                     count() 
             FROM 
                 ServiceLineItemPassengersMapping__c 
             WHERE 
                 Service_Line_Item__c=:serviceLineItemId 
             AND  
                 ServiceLineItemPassengersMapping__c.Passenger__r.PassengerType__c='Adult'
       ];
  }
  
  public static integer getChildPassengerCountBySerLineItemId(String serviceLineItemId){
     return [
             SELECT 
                     count() 
             FROM 
                 ServiceLineItemPassengersMapping__c 
             WHERE 
                 Service_Line_Item__c =:serviceLineItemId 
             AND  
                 ServiceLineItemPassengersMapping__c.Passenger__r.PassengerType__c='Child'
       ];
  }
  
  public static integer getInfantPassengerCountBySerLineItemId(String serviceLineItemId){
     return [
             SELECT 
                     count() 
             FROM 
                 ServiceLineItemPassengersMapping__c 
             WHERE 
                 Service_Line_Item__c =:serviceLineItemId 
             AND  
                 ServiceLineItemPassengersMapping__c.Passenger__r.PassengerType__c='Infant'
       ];
  }
  
  public static List<ServiceLineItemPassengersMapping__c> getPassengerCountBySerLineItemId(Set<Id> serviceLineItemIds){
     return [
             SELECT 
                     Service_Line_Item__c,
                     Passenger__r.PassengerType__c
             FROM 
                 ServiceLineItemPassengersMapping__c 
             WHERE 
                 Service_Line_Item__c=:serviceLineItemIds];
  }

}