Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PassengerName__c</fullName>
        <label>PAX</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/PassengerQuotationMapping__c.object
<CustomObject>
    <fields>
        <fullName>PassengerName__c</fullName>
        <formula>Passenger__r.PassengerName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PassengerName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Quotations__c</referenceTo>
        <relationshipLabel>PassengerQuotationMappings</relationshipLabel>
        <relationshipName>PassengerQuotationMappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PassengerQuotationMapping</label>
    <nameField>
        <displayFormat>PQM-{00000000}</displayFormat>
        <label>PassengerQuotationMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PassengerQuotationMappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/QuotationPassengerListController.cls
public with sharing class QuotationPassengerListController {
   public List<PassengerQuotationMapping__c> PassengerQuotationMappings {get;set;}
    public List<Passenger__c> Passengers {get;set;}
    public List<Passenger__c> AllPassengers {get;set;}
    public List<SelectOption> PassengerSelectOptions {get;set;}
    public List<string> SelectedPassengers {get;set;}
    public boolean firstPanel{get;set;}
    public boolean secondPanel{get;set;}
    public String QuotationId{get;set;}
    
    public QuotationPassengerListController(ApexPages.StandardController stdController) {
        PassengerQuotationMappings = new List<PassengerQuotationMapping__c>();
        Passengers = new List<Passenger__c>();
        
        QuotationId = System.currentPagereference().getParameters().get('Id').replace('/','');
        LoadScreen();
    }
    public void LoadScreen()
    {
        PassengerQuotationMappings = [SELECT Passenger__c FROM PassengerQuotationMapping__c WHERE Quotation__c=:QuotationId] ;
        List<String> PassengerIds = new List<String>();
        
        for(PassengerQuotationMapping__c pqm:PassengerQuotationMappings)
        {
            PassengerIds.add(pqm.Passenger__c);
        }
        
        Passengers = DAL_Passenger.getByIds(PassengerIds);
        
        setAllPassengersAvailableForQuotation(QuotationId);
        
        firstPanel = false;
        secondPanel = true;

    }
    public void setAllPassengersAvailableForQuotation(String quotationId)
    {
        Quotations__c quotation =[SELECT Opportunity__c FROM Quotations__c WHERE Id=:quotationId][0];
        
        AllPassengers  = [select Id,PassengerName__c from Passenger__c where Opportunity__c=:quotation.Opportunity__c];
        PassengerSelectOptions = new List<SelectOption>();
        this.SelectedPassengers = new List<String>();
        for(Passenger__c p : AllPassengers)
        {
            String name = p.PassengerName__c;
            if(name==NULL)
            {
                name='';
            }
            PassengerSelectOptions.add(new SelectOption(String.valueOf(p.Id), name));
            
        }
        
        for(Passenger__c p : Passengers)
        {
            SelectedPassengers.add(String.valueOf(p.Id));
        }
    }
    
    public void Cancel()
    {
        firstPanel = false;
        secondPanel = true;
    }
    
    public void ShowModel()
    {
        firstPanel = true;
        secondPanel = false;
    }
    
    public void Save()
    {
        List<PassengerQuotationMapping__c> mappingsToSave = new List<PassengerQuotationMapping__c>();
        for(String sp:SelectedPassengers)
        {
            PassengerQuotationMapping__c passengerQuotationMapping = new PassengerQuotationMapping__c();
            passengerQuotationMapping.Passenger__c = sp;
            passengerQuotationMapping.Quotation__c = QuotationId;
            mappingsToSave.add(passengerQuotationMapping); 
        }
        if(mappingsToSave.size()>0)
        {
            upsert mappingsToSave;  
            //============================================================
            List<Id> ids = new List<Id>();
            ids.add(QuotationId);
            CreateFolderStructureGoogleDrive.createFolderGoogleDrive(ids);
            //=============================================================  
        }
        LoadScreen();
        
    } 
}