Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PassengerName__c</fullName>
        <label>PAX</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PassengerType__c</fullName>
        <label>Passenger Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adult</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Infant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/CreatePassengerServiceReqButtonHelper.cls
global class CreatePassengerServiceReqButtonHelper{


    webservice static Passenger__c createPassengerAccount(Id AccountId, Id OppId ,String Type, String name){
      
     Passenger__c acc  = new Passenger__c();
     acc.Opportunity__c =OppId;
     acc.Account__c = AccountId;
     acc.PassengerName__c = Name;
     acc.PassengerType__c = Type;
     return acc;
    }

    webservice static void createPassenger(Id AccountId, Id OppId, String Type, Integer counts)
    {
     	Integer lastCount = DAL_Passenger.getExisitingCouunt(Type,OppId);
        if(lastCount==NULL)
        {
            lastCount =0;
        }
     	String name ='';
        List<Passenger__c> Passengers = new List<Passenger__c>();
        
        for(Integer i = 1;i<=counts;i++)
        {
            lastCount = ++lastCount;
            String lastValue = String.valueof(lastCount);
            name = Type+ ' '+lastValue;
            Passengers.add(createPassengerAccount(AccountId,OppId,Type, name));
         }
        DAL_BaseObject.InsertDBObjects(Passengers);
    }


}