Safari365 Prod/src/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Surname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <displayFormat>p-{000000000}</displayFormat>
        <label>Passenger Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/WS_GetPassenger.cls
@RestResource(urlMapping='/Safari365/MembersClub/GetPassenger/*')
global  with sharing class WS_GetPassenger
{
   private static final String SUCCESS = 'Success';
  private static final String ERROR = 'Error';
  private static final String BLANK_STRING = '';
  
    @Httppost
    global static ResponseWrapper doPost(RequestWrapper requestWrapper)
    {
        ResponseWrapper returnResponse = new ResponseWrapper();
        Passenger__c passenger  = DAL_Passenger.getPasenger_DynamiCSOQL(requestWrapper.PassengerId);
        if(null !=passenger)
        {
	        passenger.FirstName__c = '';
	        passenger.Last_Name__c='';
        }
        system.debug('passenger:::'+passenger);
        returnResponse.requestWrapper = requestWrapper;
        if(passenger != null){
            returnResponse.status  = SUCCESS;
            returnResponse.Passenger = passenger;
        }
        else {
            returnResponse.status  = Error;
            returnResponse.errorMessage ='Passenger not Found';
        }
     
       return returnResponse;
    }
    
    global class ResponseWrapper
    {
        webservice String status;
        webservice String errorMessage;
        webservice sObject Passenger;
        webservice RequestWrapper requestWrapper;
    }
        
    global class RequestWrapper
    {
        webservice String PassengerId;
        
        public RequestWrapper(String PassengerId) {
            this.PassengerId = PassengerId;
        }
    }   
            
}

/******************

{
"requestWrapper":{
"PassengerId" : ""
}
}


***************/