Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Currency__c</fullName>
        <formula>TEXT(  Opportunity__r.Client_Display_Currency__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>On the Opportunity level, choose the most likely Client Display Currency (one of the supported Global Currencies)  Your client is able to change their preferred currency in the Members Club, you will need to raise Booking Confirmation in this Currency.</inlineHelpText>
        <label>Client Display Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quotation_Stage__c</fullName>
        <label>Quotation Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quoting</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Raised Invoice</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Sch_ToUpdateExposureROE.cls
global class Sch_ToUpdateExposureROE implements Database.Batchable<SObject>,Schedulable{
    

   global Database.QueryLocator start(Database.BatchableContext BC){

        Set<String> quotationStages = new Set<String>();
        quotationStages.add('Quoting');
        quotationStages.add('Raised Invoice');
        
        return Database.getQueryLocator([SELECT Id,Currency__c,Quotation_Stage__c FROM Quotations__c WHERE Quotation_Stage__c IN:quotationStages]);
    
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
    	
    	Set<Id> quotationIds = new Set<Id>();
        Map<Id, String> quotationIdKeyClientCurrencyValue  = new  Map<Id, String>();
        for(Quotations__c var: (List<Quotations__c>)scope)
        {
        	system.debug('var::'+var.Quotation_Stage__c);
        	quotationIds.add(var.Id);
        	quotationIdKeyClientCurrencyValue.put(var.Id,var.Currency__c);
        }
        UpdateExposureROE.processRecords(quotationIds, quotationIdKeyClientCurrencyValue);               
    }

    global void finish(Database.BatchableContext BC){
       
    }
    
    global void execute(SchedulableContext sc)
    {
        Sch_ToUpdateExposureROE updateExposureROE= new Sch_ToUpdateExposureROE();
        database.executebatch(updateExposureROE, 1);
    }
}