Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/QuotationVFController.cls
public class QuotationVFController {
    public String recId{get;set;}
    public String parentID;
    public Quotations__c quotation ;

    public QuotationVFController(ApexPages.StandardController stdController) {
		parentID = System.currentPagereference().getParameters().get('retURL').replace('/','');
    }

    /*public void CreateNewQuotation()
    {
        if (parentID != null){
            quotation  = new Quotations__c();
            quotation.Opportunity__c=parentid;
            
            insert quotation;
            this.recId =quotation.Id;
        }
    }*/
}