Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Client_Has_Requested_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>In the Members Club, the client has clicked the &quot;Book This&quot; button. Please proceed within 3 days (maximum) to raise a Booking Confirmation ( there is FX exposure if you delay on this stage)</inlineHelpText>
        <label>Client Has Requested Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Has_Requested_Requote__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The quote you had sent the client has expired ( it if no longer valid due to FX exposure) and your client has requested a re-quote on the same itinerary.</inlineHelpText>
        <label>Client Has Requested Requote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Client_Requested_Confirmation__c</fullName>
        <label>Date Client Requested Confirmation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quotation_Stage__c</fullName>
        <label>Quotation Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quoting</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Raised Invoice</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/WS_UpdateQuotation.cls
@RestResource(urlMapping='/Safari365/MembersClub/UpdateQuotation/*')
global with sharing class WS_UpdateQuotation
{
    private static final String SUCCESS = 'Success';
    private static final String ERROR = 'Error';
    private static final String BLANK_STRING = '';
    
    @Httppost
    global static ResponseWrapper doPost(RequestWrapper requestWrapper)
    {
        ResponseWrapper returnResponse = new ResponseWrapper();
        returnResponse.requestWrapper = requestWrapper;
        if(requestWrapper.quotation != null){
            try{
                Quotations__c quoteObj = new Quotations__c(Id=requestWrapper.quotation.QuotationId);
                if(requestWrapper.quotation.Status != null && requestWrapper.quotation.Status != '')
                {
                    quoteObj.Quotation_Stage__c = requestWrapper.quotation.Status;
                }
                if(requestWrapper.quotation.Client_Has_Requested_Confirmation != null)
                {
                    quoteObj.Client_Has_Requested_Confirmation__c = requestWrapper.quotation.Client_Has_Requested_Confirmation;
                    quoteObj.Date_Client_Requested_Confirmation__c = system.today();
                }
                if(requestWrapper.quotation.Client_Has_Requested_Requote != null )
                {
                    quoteObj.Client_Has_Requested_Requote__c = requestWrapper.quotation.Client_Has_Requested_Requote;
                }
                update quoteObj;   
                returnResponse.status  = SUCCESS;         
            }catch(Exception ex){
                System.debug('-----Error--- '+ ex);
                returnResponse.status  = Error;
                returnResponse.errorMessage = ex.getMessage();
            }
        }
        else {
            returnResponse.status  = Error;
            returnResponse.errorMessage ='Quotation not found in request message';
        }
     
       return returnResponse;
    }
    
    global class ResponseWrapper {
    
        webservice String status;
        webservice String errorMessage;
        webservice RequestWrapper requestWrapper;
        
    }
        
    global class RequestWrapper {
        
        webservice Quotation quotation;
        
    }  
    
    global class Quotation {
    
        webservice String QuotationId;
        webservice boolean Client_Has_Requested_Confirmation;
        webservice boolean Client_Has_Requested_Requote;
        webservice String Status;
    
    } 
            
}


/*****************************

{ 
"requestWrapper":{ 
"quotation" : {
"QuotationId":"a0m0E0000015OyO",
"Client_Has_Requested_Confirmation":"true",
"Client_Has_Requested_Requote":"true",
"Status":"Confirmed"
} 
} 
}


******************************/