Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Date_Client_Requested_Confirmation__c</fullName>
        <label>Date Client Requested Confirmation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isClientRequestedConfStatusOverdue__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is a technical field which will be update by a schedular and monitors FX exposure. When True, must send alert to FX manager</description>
        <label>isClientRequestedConfStatusOverdue</label>
        <type>Checkbox</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Sch_ToCheckQuotationInQuotationStage.cls
global class Sch_ToCheckQuotationInQuotationStage  implements Schedulable{
	
    private static final String CLASS_NAME = Sch_ToCheckQuotationInQuotationStage.class.getName();
    
	public static  void checkRecords(){
        
        UTIL_LogGenerator logger = new UTIL_LogGenerator();
        logger.start(CLASS_NAME,'Sch_ToCheckQuotationInQuotationStage' );
       
       List<Quotations__c>  quotaionsToProcessed = DAL_Quotations.getQuotationbyClienRquestedConf('Quoting');
       List<Quotations__c> quotationToSendEmail =  new List<Quotations__c>();
       for(Quotations__c q: quotaionsToProcessed)
       {
       	  if(null != q.Date_Client_Requested_Confirmation__c)
       	  {
	       	  if(Integer.valueof(system.today().daysBetween(q.Date_Client_Requested_Confirmation__c)) 
	       	  		> Integer.valueof(Label.Raised_Client_Confirmation_Tolearance))
	       	  {
	       	  	q.isClientRequestedConfStatusOverdue__c = true;
	       	  	quotationToSendEmail.add(q);
	       	  }
       	  }
       }
       
      if(! quotationToSendEmail.isEmpty())
      {
	       BaseTriggerHandler.bypass('TH_Quotations');
	       update quotationToSendEmail;
	       BaseTriggerHandler.clearBypass('TH_Quotations');
      }
        logger.end();
	}
	
	global void execute(SchedulableContext bc){
       Sch_ToCheckQuotationInQuotationStage.checkRecords();
   }
}