Safari365 Prod/src/objects/QuotationLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_Status__c</fullName>
        <label>Confirmed Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processing</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirmed_serviceLineItems__c</fullName>
        <label>Confirmed ServiceLineItems</label>
        <summaryFilterItems>
            <field>ServiceLineItem__c.Service_Status__c</field>
            <operation>equals</operation>
            <value>Confirmed</value>
        </summaryFilterItems>
        <summaryForeignKey>ServiceLineItem__c.QuotationLine__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>RaisedInvoice_ServiceLineItems_c__c</fullName>
        <label>Raised Invoice ServiceLineItems</label>
        <summaryFilterItems>
            <field>ServiceLineItem__c.Service_Status__c</field>
            <operation>equals</operation>
            <value>Request Provisional Booking, Provisionally Booked, Request Confirmation, Confirmed</value>
        </summaryFilterItems>
        <summaryForeignKey>ServiceLineItem__c.QuotationLine__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Raised_Invoice_Status__c</fullName>
        <label>Raised Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UnConfirmed</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Services_Count__c</fullName>
        <label>Related Services Count</label>
        <summaryFilterItems>
            <field>ServiceLineItem__c.Service_Status__c</field>
            <operation>equals</operation>
            <value>Request Provisional Booking, Not Booked, Provisionally Booked, Request Confirmation, Confirmed</value>
        </summaryFilterItems>
        <summaryForeignKey>ServiceLineItem__c.QuotationLine__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Quotation Line Item</label>
    <nameField>
        <label>Quotation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItem__c.object
<CustomObject>
    <fields>
        <fullName>QuotationLine__c</fullName>
        <label>Quotation Line</label>
        <referenceTo>QuotationLineItem__c</referenceTo>
        <relationshipName>ServiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Line Item</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceLine Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/TH_ServiceLineItems.cls
public class TH_ServiceLineItems extends BaseTriggerHandler{
    
    private static final String CLASS_NAME = TH_ServiceLineItems.class.getName();
    private List< ServiceLineItem__c > newServiceLineItemsList;
    private List< ServiceLineItem__c > oldServiceLineItemsList;
    private Map<ID, ServiceLineItem__c > newServiceLineItemsMap;
    private Map<ID, ServiceLineItem__c > oldServiceLineItemsMap;
    
    public TH_ServiceLineItems() {
        oldServiceLineItemsList = (List<ServiceLineItem__c>)Trigger.old;
        newServiceLineItemsList = (List<ServiceLineItem__c>)Trigger.new;
        newServiceLineItemsMap =  (Map<ID, ServiceLineItem__c>)Trigger.newMap;
        oldServiceLineItemsMap = (Map<ID, ServiceLineItem__c>)Trigger.oldMap;
    }
	
    protected override void afterUpdate()
    {
    	if(Trigger_PAD.canRun('TH_ServiceLineItems'))
        {
            processRecords();     
        }
   }
   protected override void afterInsert()
   {
       if(Trigger_PAD.canRun('TH_ServiceLineItems'))
        {
            processRecords();  
        }
   }
   
   
   private void processRecords()
   {
   	  Set<Id> allQuotationLineIds = new Set<Id>();
      for(ServiceLineItem__c sli: newServiceLineItemsList)
      {
	        allQuotationLineIds.add(sli.QuotationLine__c);
      }
        List<QuotationLineItem__c> allQuotationLines= DAL_Quotations.getAllQuotationsLineItems(allQuotationLineIds);
        updateRelatedQuotationLineItems(allQuotationLines);
            
        ServiceLineItem_EmailService emailService = new ServiceLineItem_EmailService();
        emailService.sendEmailToService(newServiceLineItemsList); 
   }
   
   
   private void updateRelatedQuotationLineItems(List<QuotationLineItem__c> allQuotationLines)
   {
   	 for(QuotationLineItem__c qli:allQuotationLines)
     {
        if(qli.Related_Services_Count__c  == qli.Confirmed_serviceLineItems__c)
        {
            qli.Confirmed_Status__c='Confirmed';
        }
        if(qli.Related_Services_Count__c  == qli.RaisedInvoice_ServiceLineItems_c__c)
        {
            qli.Raised_Invoice_Status__c='Confirmed';
        }
    }

        DAL_BaseObject.UpdateDBObjects(allQuotationLines);
   }
   
   
   
}