Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Wetu_Identifier_Key__c</fullName>
        <label>Wetu Identifier Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wetu_Identifier__c</fullName>
        <inlineHelpText>This is the unique WETU URL string if you want to duplicate this exact Members Club itinerrary display. You can override this field with an updated URL string as required (proceed with caution as the quotes need to be identical)</inlineHelpText>
        <label>WETU Identifier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/WetuResponseHandler.cls
public class WetuResponseHandler
 {
	
	public static void ProcessResponse(String responseXml,String requestXml, Quotations__c quotation)
    {
       
        CreateContentDocumentLink(requestXml,'Wetu Request','Request.xml', quotation);
        CreateContentDocumentLink(responseXml,'Wetu Response','Response.xml', quotation);
        
        if(responseXml != null)
        {
	        XPath xp = new XPath(responseXml);
			
	        Dom.XmlNode[] actualNodes = xp.find(xp.root, '/soap:Envelope/soap:Body/AuthenticateAndSaveItineraryResponse/AuthenticateAndSaveItineraryResult');
	        Dom.XmlNode[] IdentifierNodes = xp.find(actualNodes[0], './Identifier');
	        Dom.XmlNode[] IdentifierKeyNodes = xp.find(actualNodes[0], './IdentifierKey');
	        
	        quotation.Wetu_Identifier__c = IdentifierNodes[0].getText().trim();
	        quotation.Wetu_Identifier_Key__c = IdentifierKeyNodes[0].getText().trim();
	        
	        upsert quotation;
        }
        
    }
    
    private static void CreateContentDocumentLink(String xmlStr,String title, String pathOnClient, Quotations__c quotation)
    {
        String versonData = 'Error Occured!!!!!!';
        system.debug('xmlStr>>>>'+xmlStr);
        if(xmlStr != null &&  xmlStr !='')
        {
       	 system.debug('inside the if block >>>>'+xmlStr);
       	 versonData = xmlStr;
        }
        system.debug('versonData>>>>'+versonData);
        ContentVersion conVer = new ContentVersion();
        conVer.ContentLocation = 'S';    
        conVer.PathOnClient = pathOnClient;  
        conVer.Title = title;  
        conVer.VersionData = Blob.valueOf(versonData);
        insert conVer;
         
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
         
        //System.debug('Content document>>'+[SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id]);
        
        //Create ContentDocumentLink
        ContentDocumentLink cDe = new ContentDocumentLink();
        cDe.ContentDocumentId = conDoc;
        cDe.LinkedEntityId = quotation.Id;  
        cDe.ShareType = 'V';  
        cDe.Visibility = 'AllUsers';
        insert cDe;
    }
}