Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Do_not_include_Photobooks__c</fullName>
        <formula>Opportunity__r.Do_Not_Send_Phptpbook_Offer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Do Not Include Photobooks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_not_include_insurance__c</fullName>
        <formula>Opportunity__r.Include_Travel_Insurance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Do Not Include Passenger Emergency Evac</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_Passenger_Insurance_USD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Passenger Emergency Evac in USD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_Passenger_Insurance_ZAR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Passenger Emergency Evac in ZAR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_Photobooks_USD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Photobooks in USD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_Photobooks_ZAR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Photobooks in ZAR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Itinerary_Summary__c</fullName>
        <inlineHelpText>This is the intro text that will show on this quotation in the Members Club (and also to be used on your covering email) Make sure this is specific to the quotation you are offering and adding value and insight.</inlineHelpText>
        <label>Quotation Intro Note to Customer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wetu_Request_Fail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wetu Request Fail</label>
        <type>Checkbox</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>wetu_password__c</fullName>
        <label>Wetu_Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>wetu_user_id__c</fullName>
        <label>Wetu_UserId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>wetu_username__c</fullName>
        <label>Wetu_UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/CreateManualWetuService.cls
global class CreateManualWetuService{

    static QuotationBuilderDatabaseQueries DbQueries= new QuotationBuilderDatabaseQueries();
    static  UTIL_LogGenerator logger = new UTIL_LogGenerator();
    
    @AuraEnabled
    public static String processRequestLtng(String quotationId){
        List<Id> ids = new List<Id>();
        ids.add(quotationId);
        List<Quotations__c> quotations=DAL_Quotations.getAllQuotations(ids);
        Quotations__c quotationsToProcess = quotations[0];
        String opportunityId=quotationsToProcess.Opportunity__r.Id;
        List<Opportunity> opportunities=DAL_Opportunity.getById(opportunityId);
        Opportunity opportunityToProcess = opportunities[0];
        Boolean errorFlag = false;
        String labelName = '';
        Boolean isTestRunning = false;
        string userId = userInfo.getUserId();
        List<User> users=[SELECT wetu_username__c,wetu_password__c,wetu_user_id__c FROM User WHERE Id=:userId];
        User userToProcess = users[0];
        
        if((quotationsToProcess.Do_not_include_Photobooks__c == false)
        	 && (quotationsToProcess.Include_Photobooks_USD__c == false) 
        	 && (quotationsToProcess.Include_Photobooks_ZAR__c == false))
       {
            labelName = System.Label.Photobooks_not_included_for_wetu;
            errorFlag = true;  
        }
        
        if(quotationsToProcess.Include_Passenger_Insurance_USD__c == false
           && quotationsToProcess.Include_Passenger_Insurance_ZAR__c == false 
           && quotationsToProcess.Do_not_include_insurance__c == false 
           && errorFlag == false)
        {
            labelName = System.Label.Passenger_Insurance_not_included_for_wetu; 
            errorFlag = true;  
        }
        
        if(quotationsToProcess.Itinerary_Summary__c != null
           && quotationsToProcess.Itinerary_Summary__c.length() < 150 
           && errorFlag == false)
        {
            labelName = System.Label.WetuQuotation_Intro_Note_to_Customer_Length; 
            errorFlag = true;  
        }
        
        if(errorFlag == false){
            CreateManualWetuService.processRequest(quotationsToProcess.Id,userToProcess.Id,opportunityToProcess.Id,isTestRunning);
            labelName = 'successMsg';
        }
        Quotations__c quotation = [SELECT Id,Wetu_Request_Fail__c FROM Quotations__c WHERE Id=:quotationId];
        quotation.Wetu_Request_Fail__c = false;
        update quotation;
        return labelName;
    }
    
    
    webservice static void processRequest(String quotationId,String userId,String opportunityId, boolean isTestRunning)    
    {
        List<Quotations__c> quotations=DAL_Quotations.getQuotationForWetuById(quotationId);
        List<Opportunity> opportunities=DAL_Opportunity.getById(opportunityId);
        List<User> users=[SELECT wetu_username__c,wetu_password__c,wetu_user_id__c FROM User WHERE Id=:userId];
        
        Quotations__c quotationsToProcess = quotations[0];
        Opportunity opportunityToProcess = opportunities[0];
        User userToProcess = users[0];
        
        logger.start(CreateManualWetuService.class.getName(),'CreateManualWetuService');
        String request;
        String response;
        try
        {
            request = createRequest(quotationsToProcess,opportunityToProcess,userToProcess);
            logger.log('request',request);
            // Instantiate a new http object
            String  url ='https://wetu.com/Map/ItineraryServiceV7.asmx';
            Http h = new Http();
            // Instantiate a new HTTP request, specify the method (GET) as well as the endpoint
            HttpRequest req = new HttpRequest();
            req.setHeader('Host', 'wetu.com');
            req.setHeader('Content-Type', 'text/xml; charset=utf-8');
            req.setHeader('Content-Length', 'length');
            req.setHeader('SOAPAction', 'http://wetu.com/Map/ItineraryServiceV7/AuthenticateAndSaveItinerary');
            req.setEndpoint(url);
            req.setMethod('POST');
            req.setBody(request);
            // Send the request, and return a response
            HttpResponse res = h.send(req);
            response =  res.getBody();
            logger.log('response',response);
            ProcessResponse(quotationsToProcess, response,request);
            Quotations__c quotation = [SELECT Id,Wetu_Request_Fail__c FROM Quotations__c WHERE Id=:quotationId];
            quotation.Wetu_Request_Fail__c = false;
            update quotation;
        }
        catch(Exception e)
        {
            logger.log('Wetu ProcessRequest',e.getMessage());
            ProcessResponse(quotationsToProcess, response,request);
            Quotations__c quotation = [SELECT
            								 Id,
            								 Wetu_Request_Fail__c 
            						    FROM 
            						    	 Quotations__c 
            						   WHERE 
            						         Id=:quotationId];
            quotation.Wetu_Request_Fail__c = false;
            update quotation;
        }
        logger.end();
    }
        
    public static  String createRequest(Quotations__c quotationsToProcess,Opportunity opportunityToProcess,User userToProcess)
    {
       return  CreateManualWetuServiceHelper.createWetuXmlString(quotationsToProcess,opportunityToProcess,userToProcess);             
        
    }
    
    public static void ProcessResponse(Quotations__c quotation, String Xmlresponse,String request)
    {
       WetuResponseHandler.ProcessResponse(Xmlresponse,request,quotation);
    }

}