Safari365 Prod/src/objects/QuotationLineItem__c.object
<CustomObject>
    <label>Quotation Line Item</label>
    <nameField>
        <label>Quotation Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/Quotations__c.object
<CustomObject>
    <description>This the table for quotation, which will be created based on the data from Opportunity and Location Service.</description>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This field restricts a user editing a quotation that has already been paid or quoted in FX to Booking Confirmation. Please seek administrator authorization should you need to edit this confirmed quotation</inlineHelpText>
        <label>Untick to Edit Confirmed Quote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SAF-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/ServiceLineItem__c.object
<CustomObject>
    <label>Service Line Item</label>
    <nameField>
        <label>Supplier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceLine Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/EmailUtilService.cls
public class EmailUtilService {

    /*public void sendEmailToServiceContactType(List<Quotations__c> quotaions)
	{
	  List<Id> confirmedQuotaionsIds = new List<Id>();
	  for(Quotations__c quotaion: quotaions)
	  {
	    if(quotaion.Confirmed__c)
	    {
	    	confirmedQuotaionsIds.add(quotaion.Id);
	    }
	  }
        SendEmail(confirmedQuotaionsIds);
	   
       /* //Fetch Confirmed all QuotationLineItems
	   List<QuotationLineItem__c> quotationLineItemsIds = DAL_Quotations.getAllQuotationsLineItems(confirmedQuotaionsIds);
	   
	   //Fetch Confirmed all serrviceLineItems
	   List<ServiceLineItem__c> allServiceLineItem = DAL_Quotations.getAllServiceLineItems(new List<Id>(
	   												SystemUtil.extractListIds(quotationLineItemsIds)));
	}*/
    
    public static void sendEmail(Set<Id> confirmedQuotaionsIds, Map<Id,String> quotationIdEmailMap)
    {
        final String template = 'EmailForPessangerDetails';
        Id templateId;

    	try
        {
        	templateId = [select id from EmailTemplate where Name = :template].id;
      	} 
        catch (QueryException e) 
        {
            System.debug('Email Template was not found for Passenger Details Email');
      	}
		
        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
        //for (Quotations__c q: [select Id,Confirmed__c,Opportunity__c  from Quotations__c where Id IN:confirmedQuotaionsIds]) 
        for (Id i: confirmedQuotaionsIds) 
        {
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setTemplateId(templateId);
            message.setTargetObjectId(i);
            //message.setWhatId(q.Confirmed__c);
            message.setToAddresses(new String[] {quotationIdEmailMap.get(i)});
      		messages.add(message);
        }
        
        if(!Test.isRunningTest())
		Messaging.sendEmail(messages);
	}
}