Safari365 Prod/src/objects/Service_Line_Item_ChargeType__c.object
<CustomObject>
    <description>This object will have the details for Service Line Items. The details this object will have are Charge Type, Currency, Nett Cost, Markup (%) and Total.</description>
    <fields>
        <fullName>Markup__c</fullName>
        <label>%</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Nett_Cost__c</fullName>
        <label>Nett</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overide_Markup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overide Markup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Nett_Cost__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Nett Cost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Sale</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service Line Item ChargeType</label>
    <nameField>
        <displayFormat>SLICT-{00000000}</displayFormat>
        <label>Service Line Item Charge Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Item ChargeTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/TH_ServiceLineItemChargeType.cls
public  class TH_ServiceLineItemChargeType extends BaseTriggerHandler{

    private static final String CLASS_NAME = TH_ServiceLineItemChargeType.class.getName();
    private List<Service_Line_Item_ChargeType__c> newServiceLineItemChargeTypeList;
    private List<Service_Line_Item_ChargeType__c> oldServiceLineItemChargeTypeList;
    private Map<ID, Service_Line_Item_ChargeType__c > newServiceLineItemChargeTypeMap;
    private Map<ID, Service_Line_Item_ChargeType__c > oldServiceLineItemChargeTypeMap;

    public TH_ServiceLineItemChargeType() 
    {
        oldServiceLineItemChargeTypeList = (List<Service_Line_Item_ChargeType__c>)Trigger.old;
        newServiceLineItemChargeTypeList = (List<Service_Line_Item_ChargeType__c>)Trigger.new;
        newServiceLineItemChargeTypeMap =  (Map<ID, Service_Line_Item_ChargeType__c>)Trigger.newMap;
        oldServiceLineItemChargeTypeMap = (Map<ID, Service_Line_Item_ChargeType__c>)Trigger.oldMap;
    }
    
    
    protected override void beforeUpdate()
    {
       if(Trigger_PAD.canRun('TH_ServiceLineItemChargeType'))
       {
         updateNetValues(); 
       }
    }
    
    
    public void updateNetValues()
    {
        for(Service_Line_Item_ChargeType__c sli : newServiceLineItemChargeTypeList)
         {
             Decimal d  =0;
            if(sli.Override_Nett_Cost__c && sli.Total__c >0)
            {
                d =((sli.Total__c-sli.Nett_Cost__c)/sli.Total__c)*100;
                sli.Markup__c = d.setscale(2);
            }
            
            if(sli.Overide_Markup__c && !sli.Override_Nett_Cost__c)
            {
                sli.Total__c = Math.round(sli.Nett_Cost__c+(sli.Nett_Cost__c*sli.Markup__c)/100);
            }
            
         }
    }
    
}