Safari365 Prod/src/objects/SyncforceServiceLog__c.object
<CustomObject>
    <description>Created by Syncforce tool for logs</description>
    <fields>
        <fullName>NumberOfRecordsProcessed__c</fullName>
        <description>Created by Syncforce tool for logs</description>
        <label>NumberOfRecordsProcessed</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfRecordsUnProcessed__c</fullName>
        <description>Created by Syncforce tool for logs</description>
        <label>NumberOfRecordsUnProcessed</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProcessDate__c</fullName>
        <description>Created by Syncforce tool for logs</description>
        <label>ProcessDate</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueryId__c</fullName>
        <description>Created by Syncforce tool for logs</description>
        <externalId>true</externalId>
        <label>QueryId</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesforceObjectName__c</fullName>
        <description>Created by Syncforce tool for logs</description>
        <label>SalesforceObjectName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SqlTableName__c</fullName>
        <description>Created by Syncforce tool for logs</description>
        <label>SqlTableName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SyncforceServiceLog</label>
    <nameField>
        <displayFormat>SL-{00000000}</displayFormat>
        <label>SyncforceServiceLog</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SyncforceServiceLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/objects/WetuLocation__c.object
<CustomObject>
    <label>Wetu Location</label>
    <nameField>
        <displayFormat>WL-{000000000}</displayFormat>
        <label>Wetu Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wetu Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/LoadWetuLocationService.cls
global class LoadWetuLocationService implements Schedulable  {
    
    
    @future(callout=true)
    public static void loadWetuLocation()
    {
        
        string url ='https://wetu.com/API/Pins/'+Label.WetuAPI+'/List?All=include&modifiedsince='+getLastMonthDate();
         // Instantiate a new http object
        Http h = new Http();

        // Instantiate a new HTTP request, specify the method (GET) as well as the endpoint
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('GET');
        // Send the request, and return a response
        HttpResponse res = h.send(req);        
        List<WetuLocation__c> wetuLocations = JSON2Apex.parseWetuLocationJson(System.JSON.createParser(res.getBody()));
        DAL_BaseObject.InsertDBObjectsAsync(wetuLocations);
        insertIntegrationLog(wetuLocations.size());
       
    }
    
    public static void insertIntegrationLog(Integer wetuLocations)
    {
        SyncforceServiceLog__c  log =  new SyncforceServiceLog__c();
        log.NumberOfRecordsProcessed__c =wetuLocations;
        log.SalesforceObjectName__c='WetuLocation__c';
        log.QueryId__c='1';
        log.NumberOfRecordsUnProcessed__c =0;
        log.ProcessDate__c = UTIL_Date.formatGivenDateToString(system.today());
        log.SqlTableName__c='WetuLocation__c';
        if(!Test.isRunningTest())
        insert log;
    }
    
    public static  String getLastMonthDate()
    {   
        Integer year = null;
        if(system.today().month() == 1)
        {
            year  = system.today().addYears(-1).year();
        }
        else
        {
            year  = system.today().year();
        }
        Integer month = system.today().toStartOfMonth().addMonths(-1).month();
        Integer day  = system.today().day();
        String returnDate =String.valueOf(year)+'-'+String.valueOf(month)+'-'+String.valueOf(day)+'T00:00:00';
        return returnDate;
    }
    
    
     global void execute(SchedulableContext bc){
       LoadWetuLocationService.loadWetuLocation();

   }     
}