Safari365 Prod/src/objects/TL_Quotation__c.object
<CustomObject>
    <fields>
        <fullName>Newest_TLQ__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Newest TLQ</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TL Quotations</relationshipLabel>
        <relationshipName>TL_Quotations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Quotation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newest and/or Primary Quotation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_by_Consultant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tick to always include in deal value</label>
        <type>Checkbox</type>
    </fields>
    <label>TL Quotation</label>
    <nameField>
        <displayFormat>TLQ-{00000}</displayFormat>
        <label>TL Quotation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TL Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/TLQInsertBefore.cls
public class TLQInsertBefore {
    
    //create your variables and data structures

    //constructor
    public TLQInsertBefore(){
        
    }
    
    //constructor accepting a list of TLQs
    public TLQInsertBefore(TL_Quotation__c[] myTLQs){
                             
        Set<Id> OppSet = new Set<Id>();
       
            for (TL_Quotation__c tlq : myTLQs) {                         // if an item is marked as primary, add the purchased country to the map where the sales order id is the key 
                if (tlq.Primary_by_Consultant__c == FALSE){
                OppSet.add(tlq.Opportunity__c);
                }
                 
            }
              
               
            // query for the tlqs in the context to update
            List<TL_Quotation__c> tlqlist = [select id, Newest_TLQ__c, Primary_by_Consultant__c, Opportunity__c from TL_Quotation__c
                                            where id NOT IN :myTLQs AND Opportunity__c IN :OppSet and Primary_by_Consultant__c =false];
                for (TL_Quotation__c tl : tlqlist){
                    tl.Primary_Quotation__c = FALSE;
                    tl.Newest_TLQ__c = FALSE;
                }
            
            // commit the records 
            update tlqlist; 
           
    }
}