Safari365 Prod/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ByPassTrigger__c</fullName>
        <label>ByPassTrigger</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OppportunityTrigger</fullName>
                </value>
                <value>
                    <fullName>TH_Quotations</fullName>
                </value>
                <value>
                    <fullName>OPTTriggerHandler</fullName>
                </value>
                <value>
                    <fullName>OPDTriggerHandler</fullName>
                </value>
                <value>
                    <fullName>OSRTriggerHandler</fullName>
                </value>
                <value>
                    <fullName>CTTTriggerHandler</fullName>
                </value>
                <value>
                    <fullName>AccountTriggerHandler</fullName>
                </value>
                <value>
                    <fullName>OpportunityTriggerHandler</fullName>
                </value>
                <value>
                    <fullName>TH_Passenger</fullName>
                </value>
                <value>
                    <fullName>NTSTriggerHandler</fullName>
                </value>
                <value>
                    <fullName>SODTriggerHandler</fullName>
                </value>
                <value>
                    <fullName>PBKTriggerHandler</fullName>
                </value>
                <value>
                    <fullName>TH_ServiceLineItems</fullName>
                </value>
                <value>
                    <fullName>TH_ServiceLineItemChargeType</fullName>
                </value>
                <value>
                    <fullName>TH_PassengerQuotationMapping</fullName>
                </value>
                <value>
                    <fullName>TH_ExposureRoe</fullName>
                </value>
                <value>
                    <fullName>TH_ConsultantTargetMonthly</fullName>
                </value>
                <value>
                    <fullName>TH_Lead</fullName>
                </value>
                <value>
                    <fullName>TH_ConsultantTargetLeadYearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ByPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ByPassValidation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/Test_Trigger_PAD.cls
@isTest
public class Test_Trigger_PAD {
    @isTest
    private static void test() {
        
        Profile p = [select id from profile where name='Standard User' LIMIT 1]; 
        
        User u = new User(alias = 'standt', email='standarduser@testorg.com',emailencodingkey='UTF-8', 
                          lastname='Testing', languagelocalekey='en_US', localesidkey='en_US', 
                          profileid = p.Id, timezonesidkey='America/Los_Angeles', 
                          username='standarduser@seb.com', ByPassTrigger__c ='TH_Quotations;OPTTriggerHandler', ByPassValidation__c =true);
         
        System.runAs(u) {
            System.assert(Trigger_PAD.canRun('TH_Quotations') == false);
            System.assert(Trigger_PAD.canRun('OPDTriggerHandler') == true);
            
            Trigger_PAD.deactivateTrigger('OPDTriggerHandler');
            System.assert(Trigger_PAD.canRun('OPDTriggerHandler') == false);
            
            Trigger_PAD.activateTrigger('TH_Quotations');
            System.assert(Trigger_PAD.canRun('TH_Quotations') == true);          
         }
    }
}