Safari365 Prod/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ProfileImageUrl__c</fullName>
        <label>ProfileImageUrl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileUrl__c</fullName>
        <label>ProfileUrl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>User_Profile_Intro__c</fullName>
        <description>User Profile Intro for members club</description>
        <label>User Profile Intro</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Safari365 Prod/src/classes/DAL_USER.cls
public class DAL_USER {
	
      private static final String CLASS_NAME = DAL_USER.class.getName();
      
      public static Map<Id,User> getUserByIds(Set<Id> userIds)
      {
      	return new MAP<Id,USER>([SELECT
      									Id,
      									EMAIL
      								FROM
      									 User
      								WHERE
      								     ID IN:userIds]);
      }
      
      
      public static User getbyOwnerId(Id userid)
      {
      	return [ SELECT
  			            Id,
  						EMAIL,
  						ProfileImageUrl__c,
  						User_Profile_Intro__c,
  						ProfileUrl__c,
  						MobilePhone,
  						Extension,
  						Phone,
  						Name
  				    FROM
  						 User
  					WHERE
  						 ID =:userid limit 1];
  }
}